### ISSUE TITLE
Add decimal digits to datatype description?

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#1077]
https://github.com/music-encoding/music-encoding/blob/425a49bbfdac18e85744a76cb3b5d6d41607e8e3/source/modules/MEI.xml#L3105-L3120

Shouldn't the description of these decimal datatypes also include the decimal digits? But if so, how many?
E.g. `between 0 and 100.00` resp. `between -100.00 and 100.00`

**Comment by pe-ro** [comment]
Per the regex, any number of decimal digits is acceptable.  To my mind, that's implied by the phrase "decimal number:"

However, there is a problem with the description of data.PERCENT.LIMITED.SIGNED, which should read 'Decimal number between -100 and 100, followed by a percent sign "%".'  It's probably also a good idea to drop "positive" in the description of data.PERCENT.LIMITED so that it reads "'Decimal number between 0 and 100, followed by a percent sign "%".'

**Comment by bwbohl** [comment]
@pe-ro 2 : @bwbohl 1 ;-)

**Comment by bwbohl** [comment]
"Positive" has to be removed from the description
