### ISSUE TITLE
Available values in data.TEXTRENDITIONLIST

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#1102]
I there a difference in using `<rend fontstyle="italic">` or `<rend rend="italic">`?

Some values in `data.TEXTRENDITIONLIST` duplicating font styling properties.

**Comment by rettinghaus** [comment]
pinging @lpugin @kepper @pe-ro

**Comment by pe-ro** [comment]
The duplication occurred because data.TEXTRENDITIONLIST was created long before data.FONTSTYLE.  I'm fine with removing the "italic" and "oblique" values from data.TEXTRENDITIONLIST.  We just need to make sure that the v4-to-v5 XSLT stylesheet translates `<rend @rend="italic"` and `<rend @rend="oblique"` to `<rend fontstyle="italic"` or `<rend fontstyle="oblique"`. @kepper?
