### ISSUE TITLE
Use of a:defaultValue causes problems with schematron for <tempo>

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#1347]
The use of a:defaultValue in the definition of the meiversion attribute causes the schematron associated with `<tempo>` to issue an error for all uses of `<tempo>` in any metadata context; in `<work>` and `<expression>`, for example.

It also violates the principal that default attribute values are to be avoided because they insert values into the document model that aren't explicitly in a document's markup.  MEI adhered to this principal until v. 5.

So, instead of modifying the constraints applied to `<tempo>` in the bibliographic context, I propose to --
- remove a:defaultValue in the definition of `@meiversion`; and 
- replace the schematron dealing the document element and @meiversion with the following constraints:
```xml
<sch:rule xmlns="http://www.tei-c.org/ns/1.0"
  xmlns:rng="http://relaxng.org/ns/structure/1.0"
  xmlns:sch="http://purl.oclc.org/dsdl/schematron" context="/mei:*">
  <sch:assert test="/mei:*[@meiversion]">The document element must have the
@meiversion attribute in order to indicate the MEI version in use.</sch:assert>
</sch:rule>
```
```xml
<sch:rule xmlns="http://www.tei-c.org/ns/1.0"
  xmlns:rng="http://relaxng.org/ns/structure/1.0"
  xmlns:sch="http://purl.oclc.org/dsdl/schematron" context="/mei:*//*[@meiversion]">
  <sch:assert test="not(@meiversion)">Only the document element can have an
@meiversion attribute.</sch:assert>
</sch:rule>
```
and
```xml
<sch:rule xmlns="http://www.tei-c.org/ns/1.0"
  xmlns:rng="http://relaxng.org/ns/structure/1.0"
  xmlns:sch="http://purl.oclc.org/dsdl/schematron" context="/mei:*">
  <sch:report role="error"
    test="not(local-name(.) = ('mei')) and not(@meiversion = '5.0+anyStart')">If the
    document element is any other than mei, the value of @meiversion must be
    '5.0+anyStart'.</sch:report>
</sch:rule>
```

**Comment by bwbohl** [comment]
@pe-ro, thanks for reporting, will have a look into this.

**Comment by pe-ro** [comment]
While we're on this topic, the current Schematron for `<tempo>` --
```xml
<pattern xmlns="http://purl.oclc.org/dsdl/schematron"
  id="mei-tempo-tempo_start-type_attributes_required-constraint-rule-184">
  <sch:rule xmlns="http://www.tei-c.org/ns/1.0"
    xmlns:rng="http://relaxng.org/ns/structure/1.0"
    xmlns:sch="http://purl.oclc.org/dsdl/schematron"
    xmlns:xi="http://www.w3.org/2001/XInclude"
    context="mei:tempo[not(ancestor::mei:syllable) and not(ancestor::mei:work) and 
    not(ancestor::mei:expression) and not(count(ancestor::mei:*) = 0)]">
    <sch:report test="@startid or @tstamp or @tstamp.ges or @tstamp.real">Must have one of the attributes: startid, tstamp, tstamp.ges or tstamp.real.</sch:assert>
  </sch:rule>
</pattern>
```
should be --
```xml
<pattern xmlns="http://purl.oclc.org/dsdl/schematron"
  id="mei-tempo-tempo_start-type_attributes_required-constraint-rule-184">
  <sch:rule xmlns="http://www.tei-c.org/ns/1.0"
    xmlns:rng="http://relaxng.org/ns/structure/1.0"
    xmlns:sch="http://purl.oclc.org/dsdl/schematron"
    xmlns:xi="http://www.w3.org/2001/XInclude"
    context="mei:tempo[not(ancestor::mei:syllable) and not(ancestor::mei:work) and 
    not(ancestor::mei:expression) and not(count(ancestor::mei:*) = 0)]">
    <sch:assert test="@startid or @tstamp or @tstamp.ges or @tstamp.real">Must have one of the attributes: startid, tstamp, tstamp.ges or tstamp.real.</sch:assert>
  </sch:rule>
</pattern>
```
The `<sch:report>` element should be a `<sch:assert>`.

**Comment by pe-ro** [comment]
Correction to the rule:
```xml
<sch:rule xmlns="http://www.tei-c.org/ns/1.0"
  xmlns:rng="http://relaxng.org/ns/structure/1.0"
  xmlns:sch="http://purl.oclc.org/dsdl/schematron"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  context="mei:tempo[not(ancestor::mei:syllable) and not(ancestor::mei:meiHead) 
  and not(count(ancestor::mei:*) = 0)]">
  <sch:assert test="@startid or @tstamp or @tstamp.ges or @tstamp.real">Must 
    have one of the attributes: startid, tstamp, tstamp.ges or tstamp.real.</sch:assert>
</sch:rule>
```

**Comment by bwbohl** [comment]
If @musicEnfanthen and I get it right, the following problems are present with `@meiversion`:

1. Encoding a mei_anyStart file with `tempo` as root makes the `tempo_in_header_disallow_most_attrs` Schematron rule fail because it contradicts the anyStart Schematron rule dictating the presence of `@meiversion` on the root element
2. If any processor processes a file referencing mei_anyStart schema, it will automatically expand/add attributes that have a default value specified in the schema. Consequently, an `@meiversion` with  `5.0+anyStart` will be added to any element without an explicitly encoded `@meiversion`. In the case of the mentioned Schematron rule for `tempo` this will result in validation failing for any `tempo` not in `score` or `part`.
3. Except for mei-basic, none of the schemata prohibit (or at least warn about) the presence of other `@meiversion` on `mei`, `meiCorpus`, `meiHead`, or `music` down the structure of the element-tree. This leads to the general question of whether multiple `@meiversion` should generally be allowed, as it currently is all customizations (except basic) on `mei`, `meiCorpus`, `meiHead`, or `music` or not.

**Comment by bwbohl** [comment]
We put some thought in this and our current take would be to get rid of the `meiversion` `defaultVal`s in source and all customizations AND only allow the corresponding value for that specific customization.
