### ISSUE TITLE
Missing value in COURSETUNING

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#1550]
In `data.COURSETUNING` there is the value `lute.baroque.d.minor` available, but no equivalent `lute.baroque.d.major`.
Are the available values complete and are their spellings correct?

**Comment by rettinghaus** [comment]
pinging @music-encoding/ig-tablature

**Comment by DILewis** [comment]
Hi @rettinghaus, this was something of a fudge. Tuning of the main strings is pretty simple for baroque lute, but for bass courses, it's less obvious. We need to work with specialists to get them defined right. We're confident about the d minor one, but would rather leave further options (of which there will be many) until we can do it right.

**Comment by paul-bayleaf** [comment]
Bug in guitar.open.G

**guitar.open.G** Open G tuning for guitars. D2 G2 D2 G2 B3 D4.

Should be D2 G2 D3 G3 B3 D4

Missing lute.baroque.d.major, suggest

**lute.baroque.d.major** Baroque tuning for lutes with 6 stable courses, and additional bass courses tuned to the key of D major. A2 D3 F3s A3 D4 F4s for the main six courses, and bass courses descending in pitch from G2, F2s, etc., depending on the size of the instrument. 

These are as currently implemented in Verovio branch develop-tab.

**Comment by TimCrawford** [comment]
paul-bayleaf is correct. This is a genuine tuning. The bass courses should descend down to A1 in a D major diatonic scale (i.e. with F and C sharp and B natural)

**Comment by TimCrawford** [comment]
I meant F sharp and C sharp, of course.

**Comment by DILewis** [comment]
To be clear, I wasn't denying that this was a genuine tuning, I was trying to push a discussion of which tunings should have named values to a later date. This is entirely due to lack of expertise amongst those of us working MEI tab (and so a need to consult). 
Happy to include the d major tuning, but don't want it implied that this is the end of the discussion and that the list is now complete (i.e. keeping the list short was not intended to suggest that it was comprehensive yet)
