### ISSUE TITLE
Revise handling of complex slurs and phrase marks

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#249]
Currently, `@curvedir` supports only the values above and below, making it difficult to indicate a complex slur that "meanders" above and below the items it covers. While it can't be used for rendering, a value of 'complex' would still be useful for classification/analytical purposes.

In addition, if `<slur>` were allowed to contain `<curve>`, then slurs that continue across system or page breaks could be represented as multiple "fragments", each with its own attributes. The `<slur>` parent represents the "logical slur", while the `<curve>` children capture the physical marks on the page.

It must also be clarified that `@bulge` must contain one or more **pairs** of signed decimal values, where the first number of each pair represents a percentage of the distance between the end points of the slur/curve and the second represents a height above/below a line drawn between the end points.

**Comment by pe-ro** [comment]
In addition, the values of `@bezier` must be defined to be **offsets** rather than page coordinates.

**Comment by zolaemil** [comment]
slur/curve is a great idea! Also, I very much agree with the introduction of a new value in order to classify "complex" slurs! @curvedir="complex" seems to me a bit clumsy. Perhaps @curveshape would be a better attribute name for the purpose? But not sure what the values would be for this. At Tido, we currently use the terms c-shaped and s-shaped, but not convinced that they are the best choice for the schema, especially if they could classify a multi-s-shaped curve too, if that makes sense...

In addition to the classification, I think what would be really useful is some means to describe what the notes are that are included in the slur. In a c-shaped slur, it is usually pretty trivial, but for an s-shaped one, it's not necessarily obvious, especially if it crosses staves.

**Comment by pe-ro** [comment]
I’ve been mulling over the value “mixed”, meaning a combination of “above” and “below” for @curvedir.  It’s better than “complex” and allows us to keep the same name for the attribute.

<slur> already allows @plist, which is intended to provide a way the events (notes, chords, rests, etc.) encompassed by the slur.

## 

p.

**Comment by zolaemil** [comment]
Yes, I think "mixed" is better than "complex".
