### ISSUE TITLE
<forward> elements sometimes ignored

### ISSUE THREAD

**Issue by rigaux** [music-encoding/music-encoding#257]
Hello there,

Thanks for the great tool. We converted our MusicXML collections to MEI. There seems (unless we misunderstood sth) to be an issue with <forward> elements. To give you an example: here is a piano score.

http://neuma.huma-num.fr/scorelib/opus?id=methodes:adampiano:092_1

At measure 12, there is a <forward> element in MusicXML, for both voices:

http://neuma.huma-num.fr/rest/methodes/adampiano/092_1/score.xml

The corresponding <space> element is missing in the MEI, for the second
voice:

http://couch.db.huma-num.fr/neuma/methodes:adampiano:092_1/mei.xml

Any help will be much appreciated.

Philippe R.

**Comment by pe-ro** [comment]
Hi Philippe,

The short answer -- 

I believe the MEI generated in this case is sufficiently correct.

The longer answer --

The MusicXML forward/backward mechanism (borrowed from MuseData BTW) has been misunderstood / abused by different implementations of MusicXML.  Since it is often (mis-)handled, dealing with it in a conversion is problematic.  In this particular case, I can't see why it has been used at all.  I don't think it's intuitive to represent the bass in m. 12 as conceptually on the upper staff but physically written on the lower one when it could just as easily (and more clearly) be represented as existing at the outset on the lower staff.

The real issue is that MusicXML assumes that every measure must be metrically complete while MEI does not. In MEI, only space that begins a measure must be accounted for.  This is analogous to the "push code" of DARMS.  The missing <space> in m. 12, staff 2, layer 1 corresponding to the <forward> element in MEI is not a huge problem as it can be assumed to be filled with space/nothing.  The handling of m. 13 is more important than m. 12 -- it is metrically complete; that is, the beamed 8th notes on staff 1 and the quarter rest on staff 2 are accurately represented as beginning on the 3rd beat.  Since both staves have space/nothing on the first 2 beats, for display purposes this space can be "squeezed out"; that is, not rendered.

**Comment by rigaux** [comment]
OK, thanks for the prompt answer. So, bottom line, we can take as a rule that any incomplete measure in MEI has to completed by silence/space. Let's do it.

**Comment by pe-ro** [comment]
Hmmm ... This one's more of a problem.

The MusicXML -> MEI stylesheet actually consists of two passes -- process and post-process steps, if you will.  In both the examples you provided, the grace notes are present at the end of the process phase, so obviously they're being removed in the post-process pass.  Since @kepper wrote that part of the stylesheet, he's probably the best equipped to fix it.
