### ISSUE TITLE
Remove older sample encodings

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#271]
The sample encoding directory is quite large. Since we don't ship ways of generating MEI 2012 and MEI 2013 (i.e., older versions) in the directory, we don't really need to keep these old collections around in the repo. 

I would suggest the following:

1) Move `MEI 2012` and `MEI 2013` sample encodings to their own repository (sample-encodings). 
2) Rename the new `MEI 2015` to `MEI 3.0.0`

We might also consider moving all the sample encodings to a separate repo too.

**Comment by pe-ro** [comment]
Random thoughts --

I agree that it might be a good idea to move all the sample encodings to a separate repo. It's still useful, I think, to provide a set of examples with each release, but that could just as easily be accomplished by providing a link to them.  We could even maintain only the ones that conform to the latest spec. My major concern is that we don't duplicate files unnecessarily during the testing phase of each new release.

It's also important that we present the highest quality encodings that we can as examples. Unfortunately, not all the current examples are as good as they could be.  That's understandable, of course, since most of them were generated by hand.  Still, we need to make concerted efforts to make sure we're putting our best foot forward.

I don't think the current organization into nested folders is the best way to go.  I'd rather see a smaller set of directories and a feature index that references the file(s) that exemplify each feature.

**Comment by pe-ro** [comment]
Another thing -- in some cases, it might be best to compose and validate highly-targeted examples against the mei-all_anyStart RNG.  That will eliminate the need for the "extra baggage" of a header and contextual markup if it's not central to the example.

**Comment by ahankinson** [comment]
How about this as a course of action:
- Move all the sample encodings into a separate repository
- Create a 'samples' directory in music-encoding repository
- Move a few selected examples (chosen to exemplify particular features) into the music-encoding samples.

For the 'another thing' -- can this be the role of the tests? I think any 'targeted' encodings would be ideal for testing against since they're small and purpose-built.

**Comment by pe-ro** [comment]
Yes, precisely what I had in mind, although I think we still need a mixture of targeted and general examples.  The test files can be the targeted examples, but how can we make sure to preserve them once the testing of a new release is complete?  Would it work to put all the files (targeted and general) in a single directory and have the build script look for the test files there?  But, if we do that, how can we maintain a separation between files created to test the latest release and those that demonstrate MEI generally?  Do we need 2 directories/locations?

**Comment by ahankinson** [comment]
I don't know that we need to explicitly preserve them once the testing of a new release is complete, since we can always go back and see the state of a repository at any point in time. (e.g., here's the 2.0.0 release: https://github.com/music-encoding/music-encoding/tree/1233176080667060f375ed11ce92d4994fd9326c)

I can also change the build script to validate both the targeted (testing) and general (examples). It's fairly common for a repository's unit tests to also be a resource for people looking to implement a specific feature, so I don't think we lose anything by using the tests for two purposes.

I think two directories (tests and samples) would be fairly clear.

**Comment by pe-ro** [comment]
Is it useful to have access to the testing files even after a release, for example at this point for the 2.0.0 release?  Would it be helpful to move the testing files to the example directory just prior to a release as a way of preserving them? @lpugin?  @kepper?

I think we should continue to provide PDFs (or other image formats) for examples whenever possible.  Anyone have any objections?

**Comment by lpugin** [comment]
Would it make sense to make a "release" of the test files for each release we make of the schema and once they are ready?

Having the PDFs is very useful, I think

**Comment by ahankinson** [comment]
The sample encodings have been moved to music-encoding/sample-encodings. Closing this issue.
