### ISSUE TITLE
Confusing notes and descriptions for <appInfo> and <application>

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#273]
The notes in both `appInfo` and `application` state:

""Application" in this context is not to be confused with software which was used to create the MEI file. The latter may be recorded in the projectDesc element."

While the description for both of them say:

"Provides information about an application which has acted upon the current document."

These seem to me to be contradictory. I'm assuming the 'notes' directive refers to e.g., oXygen, where you don't need to record the oXygen version info, and instead do it in the `projectDesc,` but for software that is encoding MEI, I'm thinking that `application` and `appInfo` are both useful.

**Comment by pe-ro** [comment]
The distinction between agents that created the current file and those that "acted upon it" at a later time was borrowed from TEI.  I agree that for our purposes the distinction is confusing and not very useful.  Would it be sufficient to simply remove the remarks provided for `<application>`?  I think the result would simply be that information about any application connected to the document would end up in `appInfo/application`.

However, as a counter example, the MusicXML to MEI stylesheet writes information about itself to `<revisionDesc>`, not `<appInfo>`, as this seems to me like a more logical place for this kind of thing. So, rather than making a distinction between `<profileDesc>` and `<encodingDesc>`, this supposes a distinction between `<encodingDesc>` and `<revisionDesc>`.  I don't think, however, that there would be any harm in putting the application information related to conversion in `<encodingDesc>`, or even in both places.  The major difference is that `<appInfo>` is more data-like (and therefore more amenable to machine processing), while statements in `<revisionDesc>` are text-y (and therefore better read/interpreted by humanoids).

**Comment by ahankinson** [comment]
Right now I'm recording the Sibelius to MEI plugin info in the `<appInfo>` block along with the date and time it was exported. I want it to be more 'data-like' in that I can envision using it to check for known bugs later (i.e., if v. 2.1.0 had a bug with encoding beams, this would provide a quick way to see if a particular encoding has some expected gotchas.)

But the bug report is really not about changing the schema, or even about encoding this info -- it's more to clarify the documentation so that the two statements to seem to be contradictory.

**Comment by pe-ro** [comment]
OK, so what's your recommendation on clearing up the contradiction?  Will eliminating the offending statement do the trick?

**Comment by ahankinson** [comment]
Yeah, remove the language that seems to imply that "`application` isn't really for data about applications."

**Comment by ahankinson** [comment]
I'm going to close this one since it seems it was fixed in 2a13dd5bb2d99b90865754f7aa994ff82efbc501
