### ISSUE TITLE
Pitch extremes: highest/lowest possible

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#278]
Modern composers sometimes write isolated notes in which the pitch is not precisely specified, but rather as "highest note possible"  or "lowest note possible".  MEI lacks a way to capture these pitch extremes.  One method would be to make the `att.pitched` class a member of a new class, `att.pitchextremes`, which has one attribute, `@extremis` that takes one of 2 values -- "highest" or "lowest".  Doing so, however, would make this attribute available on other members of att.pitched , not just `<note>`.  So, it's probably better to simply add the `@extremis` attribute directly to `att.note.log`.  A Schematron rule may be added to disallow other pitch-related attributes in the presence of `@extremis`.

**Comment by kepper** [comment]
Sounds good. Does it make sense to connect this somehow to a specification of an instrument's range (in order to say what "highest" technically could mean)? Isn't Goldsmiths working in this direction, @ironchicken? But even if there's no immediate connection, it could be beneficial to think about this connection – even if we wouldn't want to provide this connection on every single such note, but probably at the staffDef or so. Anyway, I like this one :-)

**Comment by ironchicken** [comment]
Yes, we've been working on improved semantics for instrumentation including the idea of instrument configurations. We've been working specifically on the tunings of stringed instruments. Our "configurations" might be a slightly different concept to the question in hand: configurations implies that they are normally variable properties of an instrument. The concept here is more like instrument affordances or constraints. But I think it still fits in with our stuff at some level of abstraction.

One thing we've been discussing (but haven't prototyped at all), is the idea of linking to instrument configurations rather than embedding them in documents. For instrument affordances or constraints, this might be even more appropriate as, in principle at least, they must be even less variable than configurations. This would assume some external (Linked Data?) authority on instruments.

**Comment by ironchicken** [comment]
The schema we worked on is here https://github.com/TransformingMusicology/mei-tmus/blob/master/schemata/instruments.odd

**Comment by pe-ro** [comment]
"highest/lowest possible" indicates an indeterminate pitch (see Gould, p. 12), not the highest named pitch on an instrument.  In my experience, this indication is primarily used for wind instruments where the "highest note possible" depends on the player's abilities and for string instruments where the "lowest note possible" depends on how much a string is de-tuned; that is, by loosening the string using the tuning peg.

Even when the nominal pitch range of an instrument (such as the piano) can be determined, the actual range depends on the individual instrument, not the class of instruments called "piano".  In other words, the range of "a piano" has changed over time.  I'm not sure how useful it is to encode this information in MEI.  Is it necessary to say that a particular work was written for instrument with a 9 octave range when only 4 octaves are actually used?  How accurate could this kind of information possibly be, given an astronomically large number of instruments and instrument makers?

**Comment by ironchicken** [comment]
No such resource of instrument configurations, or affordances/constraints exists. And you're right, it would be very significant undertaking to create one. But to start one that's open ended would not be insurmountable, although would require the resources of a small team.

However, it seems that we should be able to go ahead with the main suggestion of adding `@extremis` to `att.note.log`.
