### ISSUE TITLE
Tuning / intonation

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#279]
MEI currently allows specification of tuning  / intonation at the score level. It would be helpful to allow the `tune.*` attributes at the staff and note levels as well.  This would facilitate encoding these characteristics when different instrumental or vocal resources employ different tuning systems or for momentary intonation changes on individual notes.  In the latter case, intonation is usually expressed as some kind of relative deviation from the norm rather than absolutely using a precise frequency; that is, something `@tune.Hz` can capture.  A new attribute, perhaps called `@tune.rel`, should be sufficient.  `@tune.rel` should likely use cents.  Directives, like "10 cents sharp" or various symbolic representations, should continue to be recorded in `<dir>`.  This proposal doesn't address change over time, only momentary, discrete modifications.  A control event that specifies the range of its operation (using `@tstamp` and `@tstamp2`, etc.) is required for that.

**Comment by kepper** [comment]
Sounds reasonable. From my current experience with Freischütz, I would like to see this on layerDef as well – when two differently tuned horns share a staff, they have different trans.diat and trans.semi attributes, which aren't allowed at layerDef in 2.1.1. Since they don't really play together on that staff, but rather alternate, one might argue that there should be a redefining staffDef for each change, but this results in loosing the overview of all participating instruments at the beginning of the movement – where the labels reside. This tuning business seems to be a similar case, does it?

**Comment by pe-ro** [comment]
I think "tuning" and "transposition" are different beasts and conflating them would be abuse  of `@tune` attributes.
