### ISSUE TITLE
Add attribute to capture horizontal position

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#284]
MEI already has `@loc` and `@ploc` attributes for recording the vertical position of some items. Adding `@hloc` would provide a method for recording the horizontal position of an item as measured from the left margin of the page (ala' SCORE).  [Note: the name `@loc` should be changed to `@vloc`] These attributes (`@hloc` and `@vloc`) can be used to provide explicit rendering information. Their values can be ignored by processors that impose their own layout, say for display on the web.  When  `@hloc` and `@vloc` are present, `@ho` and `@vo` can be defined as offsets from their values. When `@hloc` and `@vloc` are _not_ present, `@ho` and `@vo` can retain their current definition as offsets from programatically-determined positions.

**Comment by zolaemil** [comment]
I was thinking about these positioning attributes the other day. Despite not being very useful for dynamic display, I can see that `@hloc` could be useful to capture positioning information in the horizontal axis from a printed source.

Regarding `@vo` and `@ho` attributes, I am not really sure what they are useful in the first place, for 'programatically-determined position' is practically an undefined position. (Unless they are meant to be used in a context-specific way, e.g. exporting from a particular software would use these attributes to relate to the positions calculated by that particular program. In my view, such encodings should be as short-lived as possible...)

**Comment by ahankinson** [comment]
`@facs` already defines a zone on a surface, so if you wanted to align with an image of a digitized printed source you would use the `@facs`/zone/surface functionality.

`@hloc` would have to be confined to 'dynamic' (i.e., engraved) presentation, perhaps as a way of "locking" elements at a specific spot on the staff.

**Comment by pe-ro** [comment]
As is many times the case, perhaps it's the definition ("programatically-determined position") that's problematic, not the thing itself.  This phrase was an attempt to convey the idea that the position of the thing bearing `@ho and/or @vo` is not absolute.  For example, `<note ho=".5"/>` is meant to be a way to say "place this note slightly to the right of where it would otherwise have been located".  The place where it "would otherwise have been located" is in fact determined by the layout engine in use.

**Comment by pe-ro** [comment]
Yes, `@hloc` is intended to "lock" elements at a particular horizontal location.

I hope to be able to support files that "lock" items to particular locations as well as completely dynamic layout.  One probably would not employ both methods simultaneously, however.

**Comment by ahankinson** [comment]
`@loc` is currently defined with respect to the staff lines. So `@loc=1` would be something that is located on staff line 1.

What would the unit be for `@hloc`? Is it `@hloc=5` which would be 5 staff-line height measurements? or `@hloc=5mm` which would lock it 5 mm from the edge of the staff?

**Comment by pe-ro** [comment]
Not completely determined yet, but I think the reference point has to be related to something that doesn't move, something related to the page, not the staff.  SCORE uses the left edge of the page (or the left page margin, I can't remember which). The values would follow the pattern of other measurements; that is, `(\+)?\d+(\.\d+)?(cm|mm|in|pt|pc|px|vu)?`

Just for consistency's sake, it might be good to rename `@loc` to `@vloc`.

**Comment by pe-ro** [comment]
If the left edge of the page were chosen as the reference point, one could never use negative values for `@hloc`.  If the left page margin were used, then both positive and negative values have to be allowed.  I don't see any reason to prefer one over the other, but I'm willing to be convinced otherwise.

**Comment by ahankinson** [comment]
What if there is no page?

**Comment by pe-ro** [comment]
I'm not sure what you mean.  The notation has to be displayed on a page/surface/view port, whatever you want to call it, that has dimensions.  So, there's always a page in some sense.

**Comment by pe-ro** [comment]
If the notation is intended for display, that is.

**Comment by pe-ro** [comment]
Of course `@hloc` has to be optional, for the case when "fully automatic" layout is desired.  Even when present, renderers could choose to ignore it.  But doing so would "mess up" the layout intended by the encoder, so it might be a good idea for software to ask before throwing away any positional stuff in the file.

**Comment by ahankinson** [comment]
It does have dimensions, but they're not always satisfactory dimensions to work in. Pixels, SVG units, etc. are all rendering-level measurements, but it seems unsatisfactory to specify 'locations' in terms of absolute units. 

I guess what I'm trying to say is that if you're looking to fix an object's horizontal position on the page, pixels or millimeters are poor units to do it in since screens don't do millimeters well, and paper doesn't do pixels well. If you're looking at fixing it in musical terms then that would be better from a proportional point of view ("symbol X is always **y** half-staff-height units from somewhere.")

But neither of those seems satisfactory. In a computer graphics sense the 'origin' is simply a convenient starting point. I can have a fixed Origin that actually means nothing to the music display. For example, I could want to draw some controls on the same canvas that I'm rendering the music on. So the "0" origin, and the "horizontal position from the 0 origin where the application starts drawing music" is defined at an application-specific level and actually has little bearing on any notion of where the "page" edge is. The page edge in this case is virtual. So setting something to be "x" pixels from the origin means nothing. Even if you were to 'assume' a margin, an application might actually draw music with a hard edge on the margin and simply "fake" a page margin. Saying a symbol is 10mm from the page edge is meaningless in this case. Even saying something is 10 "units" from the edge is meaningless, because the distance between the edge of the surface and the edge of the music (i.e., the staff) will be different in every application.

So, in sum: If we're going to go this way, it would be better to come up with some device-independent means of measuring `@hloc` that does not depend on measured units, nor an actual page edge.

**Comment by zolaemil** [comment]
> @loc is currently defined with respect to the staff lines. So @loc=1 would be something that is located on staff line 1.

For the record `@loc` is defined in half-staffspace units with bottom staff line being 0.

**Comment by ahankinson** [comment]
OK, thanks for correcting me!

**Comment by zolaemil** [comment]
Agreeing with all the points Andrew made,
1. I support to keep on the path of using musical units, i.e. spaces or half-spaces.
2. I strongly suggest defining the origin well, or provide a generic mechanism to define the origin well.

Margins, "programatically determined" or positions where things "normally" would be, aren't very useful for processing, staves are much better.

**Comment by pe-ro** [comment]
I'm not sure if @ahankinson will find this satisfactory, but how about adding `@page.origin` attribute sound, where "page" is defined much like `<surface>`; that is, "a writing surface [defined] in terms of a rectangular coordinate space"?  This definition permits a "page" to be a physical, printed page or a non-physical display space, i.e. a "view port".  

`@page.origin` is intended to take one of the following values: topleft, topright, botleft, botright.  So-called "absolute" values, like those in `@x` and `@y`, could be expressed relative to this point (0,0).  The attributes `@page.height`, `@page.width`, etc. can stay as they are; that is, their values can be given in several units, "(cm|mm|in|pt|pc|px|vu)".  Of course, conversion between the various units hinges on the existence of `@vu.height` or the selection of a reasonable default in its absence.  

Transformation between encodings using different values for `@page.origin` is possible as long as some origin is specified.  This argues for either making `@page.origin` mandatory or providing a default/conventional value.  We probably should make the default origin be whatever point Verovio is using.

I think this gives us a way to more precisely record absolute, page-based location info.  Relative positioning is addressed elsewhere, #357 for example.

**Comment by pe-ro** [comment]
@music-encoding/core-contributors, @craigsapp, Are we good to move forward on this?

**Comment by craigsapp** [comment]
It is tricky, so I will complain after you make a specification :-)

The closest way to do SCORE's system for `@hloc` would be as a percentage value between the left/right margins of the music.  SCORE uses the range for 0-200 instead of 0 to 1 or 0 to 100, mostly because this makes horizontal vu's close to vertical vu's at the default scaling (the ratio between the two is 7/6 with the horizontal units slightly longer at 100% scaling, and exactly equal at 87.5% scaling). 0 is the left system barline position, not including brackets or accolades occurring to the left of the system barline.

Mostly how you describe hpos will depend on what you want to space on the page with it: work titles, page numbers, composer's names, footnotes are the things that I can think of that would need to use this attribute.

This system is not aware of the page size or page margins, so not really page specific, although it can be used to approximate page-level positioning.  For example, if you want a page number centered on the page, then it could be centered at 50% of the musical width (or at hpos 100 in SCORE).  As long as the musical content is full-width on the page with equal margins on both sides of the music, the page number would be centered.  If you have unequal margins to allow for a gutter margin (extra space to allow for binding), then this system is superior, since you want the page number centered above the music, not centered on the page which includes a gutter margin.

Likewise the composer's name is often left-justified at 100% to the right above the music (200 units in SCORE).  The size of the page or the margins of the page do not need to be known if the percentage system is used.

Using vu for horizontal positions would not work, since it would be impossible to "lock" anything at a horizontal position when changing the scaling or width of the music.

**Comment by pe-ro** [comment]
> The closest way to do SCORE's system for `@hloc` would be as a percentage value between the left/right margins of the music. ... This system is not aware of the page size or page margins, so not really page specific, although it can be used to approximate page-level positioning.

I'm confused -- how can `@hloc` be a percentage of the distance between the left/right music margins, if the page margins (which I assume are the basis for the music margins) aren't known?

I've been using a mental model of a page that looks like this --

![image](https://cloud.githubusercontent.com/assets/5712877/21912278/eec339a6-d8f2-11e6-9e8d-c3d6d9c05f53.png)

where the page/screen/viewport size and the margins are specified.  The remaining space is for the content.

This seems like a reasonable model to me.  Is it not?  If not, why not?  If so, can we use this as the basis for discussion of page-based placement?

**Comment by kepper** [comment]
might be related to page-based discussions, in which context this will come up again.
