### ISSUE TITLE
9 flats

### ISSUE THREAD

**Issue by ran-mo** [music-encoding/music-encoding#286]
In order to encode some harmonic studies from Max Reger, I need to encode a piece with a key signature of 9 flats (f sharp). Currently, it's not possible to do that with `@key.sig`, but only with the `<keySig>` element. It would be much simpler to have this functionality on `@key.sig` as well.

<img width="443" alt="nineflats" src="https://cloud.githubusercontent.com/assets/14043371/11685679/2558f310-9e7b-11e5-807b-14a81232d05e.png">

**Comment by ahankinson** [comment]
Hi Ran-mo! Thanks for bringing this up. I might suggest that you contact our mailing list to extend this discussion, as there are quite a few more people there who would be able to advise on this.

From a preliminary look, though, it seems that "theoretical keys" are non-standardized across repertoires, so a value of '9' in `@key.sig` would not be unambiguous to which flats are present in the key signature. In this case it is preferred practice to use `<keySig>` since this allows for more precise enumeration of the accidentals present in the signature.

**Comment by pe-ro** [comment]
Just a small clarification -- the **visual appearance of key signatures** for "theoretical keys" are non-standard, but going around the circle of fifths beyond the usual 7 positions is fine.

Since `@key.sig` is a bit of a misnomer anyway (it's really about key, not key signature), then I don't see any harm in allowing values up to and including 12.  It is, however, as Andrew points out, a good idea to use `<keySig>` if you want to specify more precisely which accidentals appear in the key signature.  This is really no different than usual as `@key.sig="1f"` doesn't tell you where the flat is supposed to be placed.

**Comment by ahankinson** [comment]
I will admit that all I know of this topic is what I read on Wikipedia, but it was the examples there that gave me pause.

https://en.m.wikipedia.org/wiki/Theoretical_key

Ordering and content is not necessarily obvious given just a single integer.

In 99% of the use cases for key signatures it can be covered by the usual 7 positions. Should exceptions need to be made I understand that is what the keySig element is for.

**Comment by pe-ro** [comment]
Yes, order and content is not necessarily obvious given a single integer.  That's true whether the integer is '1' or '12'. :-)  So, I don't see any problem with also allowing integers 9-12.  `<keySig>` isn't there to address exceptions in `@key.sig`.  It's there to enhance the info that's in `@key.sig` in terms of order and content.

**_Not**_ allowing integers 9-12 in `@key.sig` creates inconsistency.  For example, you can put "1f" in `@key.sig` and use `<keySig>` to say that the flat is displayed below the staff, not on the 3rd line.  But you can't do the same if you have more than 7 flats -- you can only use `<keySig>`.  You can't use `@key.sig` to provide any info about where the key is on the circle of fifths.

Would it help make things clearer if `@key.sig` were renamed `@key`?

**Comment by pe-ro** [comment]
Another possible substitute for `@key.sig` is `@key.fifths`.

**Comment by ahankinson** [comment]
I would strongly advocate against removing or altering`@key.sig`. It may not be philosophically accurate, but it is intuitive and easy to understand.

Like I said, `@key.sig` as it is covers 99% of the common use cases. 

That said, _If_ we were to change `@key.sig` I would recommend that it be pushed off two releases in the future. Almost every piece of software and encoding uses it, so we would need a long lead time for this change. This would work by marking it deprecated in the next release (4.0?) and then removed in 5.0.

But I really, **really** would prefer that it stayed, and that <keySig> be recommended for extended uses.

**Comment by pe-ro** [comment]
Adding new values (that is, `8, 9, 10, 11, 12`) to `@key.sig` doesn't break any software that only uses the currently available subset of the full range of values (`1-7`, for example).  What's the issue with making this change?

**Comment by ahankinson** [comment]
What does `@key.sig="1"` mean? Don't you need to qualify it with s or f?

For that matter, wouldn't we have to allow 9f to differentiate between 9s? And shouldn't it technically be something like 7f2ff?

It just seems like a huge structural change  to accommodate a very niche use case.

**Comment by pe-ro** [comment]
Sorry, I guess I wasn't specific enough.  The full range of values for key.sig is

0 (zero) = no sharps, no flats
mixed = mixed sharps and flats
1-12 [fs] = steps around the circle of 5ths; f = flats (counter-clockwise), s = sharps (clockwise); for example, "1s" indicates the key of G major or E minor.

The key.sig attribute doesn't actually record the sharps, flats, etc. of the displayed key signature.  Instead, it attribute holds a value indicating the key's position in the circle of fifths. The image at https://en.wikipedia.org/wiki/Circle_of_fifths shows the traditional way of expressing the concept of key, while the table at https://en.wikipedia.org/wiki/Theoretical_key#The_need_to_consider_theoretical_keys illustrates the keys beyond the 7th position; for example, where the keys usually written using sharps are expressed using double flats.  For example, "9f" means go around the circle of 5ths in a clockwise direction 9 fifths, steps, positions, places, whatever.  This puts you in the key of B-double-flat major or G-flat minor (which most sane people notate as A major or F-sharp minor because these are easier to read).

When the value of key.sig is "mixed", the traditional/functional meaning of "key signature" is absent and this circle of fifths business is irrelevant.

Because the point of key.sig isn't to record the sharps and flats in the actual key signature, values like "7f2ff" are NOT necessary.

I'm fine with leting the key.sig attribute keep its name, if you're ok with key.sig **_not actually**_ saying anything about **_the key signature**_.  :-)  But I do think it ought to be allowed to do its job completely; that is, the so-called "theoretical keys" should be accommodated.

HTH,

## 

p.

**Comment by ahankinson** [comment]
How would you encode the example given on the wikipedia page for Db minor? Is that 7f? or 8f?

**Comment by kepper** [comment]
it's clearly 8f.

1f = d
2f = g
3f = c
4f = f
5f = b♭
6f = e♭
7f = a♭
8f = d♭
9f = g♭
10f = c♭
11f = f♭

./@key.sig just doesn't say anything about how it's rendered, it's logical information on which fingers need to be twisted for translating written staff positions in corresponding piano keys (or similar). The whole discussion about values of "9" (without f or s) is probably just a misunderstanding. There should be no value of "9" only, just as there is no value of "5" only…

I'm also in strong favor of keeping the name key.sig for this attribute.

**Comment by pe-ro** [comment]
Closed by [4fe34c9]
