### ISSUE TITLE
Making the distinction between various types of tempo indications

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#293]
It could be valuable to be able to make the distinction between various types of tempo indications. One example is the metric modulations when the tempo indication has typically the form ♩= 𝅗𝅥 
Making the difference between different types of tempo indications will also facilitate rendering decisions. The metric modulation is generally centered with the bar line separating two measures, whilst normal tempo indication as usually left aligned.

**Comment by zolaemil** [comment]
+1

**Comment by pe-ro** [comment]
Since `@type` is generally reserved for _ad hoc_ extension, a new attribute must be added for this purpose (proposed name = _func_). 

I'm thinking that a marking with the form [value] = [value] can use one of the following values --
- "metricmod" (so-called 'metric modulation', where the first value indicates the preceding tempo and the second value represents the succeeding tempo), 
- "precedente" (where the first value indicates the succeeding tempo and the second value represents the preceding tempo.  (See Gould, p. 185 for an explanation of these two.)

A marking that indicates an instantaneous, discrete tempo (either a word or phrase like "Adagio" or a metronome marking like ♩=70) can use the value
- "discrete"

while a marking that indicates a gradual tempo change (such as "accel.", "rit.", etc. will use the value
- "continuous"

We can revisit continuous markings later if there's a need to specify machine process-able starting and ending metronome or MIDI values.

Sound good?
