### ISSUE TITLE
data.MIDITEMPO

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#295]
The datatype data.MIDITEMPO is defined incorrectly and its value range is too restrictive.  Therefore, the explanation for `@midi.tempo` is also incorrect.  Rather than "number of quarter notes per minute", it should be defined as "the number of microseconds per quarter note" (per the MIDI file specification at http://www.somascape.org/midi/tech/mfile.html).  At 120 beats-per-minute (and where a quarter note gets one beat), the value of data.MIDITEMPO would 500,000.

**Comment by pe-ro** [comment]
To be included in the next revision --

```
<macroSpec ident="data.MIDITEMPO" module="MEI" type="dt" mode="delete"/>
<macroSpec ident="data.MIDIBPM" module="MEI" type="dt" mode="add">
  <desc>Tempo expressed as "beats" per minute, where "beat" is always defined as a quarter
  note, *not the numerator of the time signature or the metronomic indication*.</desc>
  <content>
    <rng:data type="positiveInteger">
      <!-- The range is taken from Mup. -->
      <!--<rng:param name="minInclusive">10</rng:param>
      <rng:param name="maxInclusive">1000</rng:param>-->
    </rng:data>
  </content>
</macroSpec>
<macroSpec ident="data.MIDIMSPB" module="MEI" type="dt" mode="add">
  <desc>Tempo expressed as microseconds per "beat", where "beat" is always defined as a
   quarter note, *not the numerator of the time signature or the metronomic
   indication*.</desc>
  <content>
    <rng:data type="positiveInteger"/>
  </content>
</macroSpec>
<!-- replace midi.tempo with midi.bmp and midi.mspb -->
<classSpec ident="att.miditempo" module="MEI.midi" type="atts" mode="replace">
  <desc>Attributes that record MIDI tempo information.</desc>
  <attList>
    <attDef ident="midi.bmp" usage="opt">
      <desc>Captures the number of *quarter notes* per minute. In MIDI, a beat is always
      defined as a quarter note, *not the numerator of the time signature or the
      metronomic indication*.</desc>
      <datatype>
        <rng:ref name="data.MIDIBPM"/>
      </datatype>
    </attDef>
    <attDef ident="midi.mspb" usage="opt">
      <desc>Records the number of microseconds per *quarter note*. In MIDI, a beat is always
       defined as a quarter note, *not the numerator of the time signature or the
       metronomic indication*. At 120 quarter notes per minute, each quarter note will last
       500,000 microseconds.</desc>
      <datatype>
        <rng:ref name="data.MIDIMSPB"/>
      </datatype>
    </attDef>
  </attList>
</classSpec>
<!-- Clarify documentation on @mm. -->
<classSpec ident="att.mmtempo" module="MEI.shared" type="atts" mode="replace">
  <desc>Attributes that record tempo in terms of beats per minute.</desc>
   <attList>
     <attDef ident="mm" usage="opt">
       <desc>Used to describe tempo in terms of beats (often the meter signature denominator)
        per minute, ala M.M. (Maezel's Metronome). Do not confuse this attribute with
        midi.bmp or midi.mspb. In MIDI, a beat is always defined as a quarter note, *not the
        numerator of the time signature or the metronomic indication*.</desc>
       <datatype>
         <rng:ref name="data.TEMPOVALUE"/>
       </datatype>
     </attDef>
     <attDef ident="mm.unit" usage="opt">
       <desc>Captures the metronomic unit.</desc>
       <datatype>
         <rng:ref name="data.DURATION"/>
       </datatype>
     </attDef>
     <attDef ident="mm.dots" usage="opt">
       <desc>Records the number of augmentation dots required by a dotted metronome
         unit.</desc>
      <datatype>
         <rng:ref name="data.AUGMENTDOT"/>
      </datatype>
    </attDef>
  </attList>
</classSpec>
```

**Comment by pe-ro** [comment]
Closed by [6f09893]

**Comment by craigsapp** [comment]
random comment on this thread:

> (per the MIDI file specification at http://www.somascape.org/midi/tech/mfile.html).

That looks authoritative :-)  Here is the official source:
    https://www.midi.org/specifications/item/the-midi-1-0-specification
The full spec is now free (originally was $50 for a paper copy), but you do have to register to see it.

> At 120 beats-per-minute (and where a quarter note gets one beat), the value of data.MIDITEMPO would 500,000.

MIDI file tempos are not in terms of beats, but in terms of quarter notes (as you note).  So a MIDI meta-message tempo of 500000 microseconds is "120 quarter-notes-per-minute".  This is sometimes equivalent to "120 beats-per-minute", but they are not the same thing. 

In the MEI documentation extract:

> Tempo expressed as "beats" per minute, where "beat" is always defined as a quarter note,

This statement is not true, so it would be useful to clarify with the following discussion.  
MIDI file tempos are exclusively expressed as "quarter-notes-per-minute" and not in "beats-per-minute".  You are conflating the observation that the conversion rate between them is often one-to-one, such as for 
4/4 time signatures, but this is not always true, particularly when the time signature denominator is not 4.

To convert tempos from QPM into BPM within a MIDI file, there would have to be a time signature meta message before or at the same time as the tempo message (4/4 time signature is a reasonable default assumption if there is no time signature).  Time-signature meta-messages contain four data parameters
- time units per measure (beats if a simple meter, but not if a compound meter)
- log_2(rhythmic value for the time units).
- MIDI clock ticks per metronome beat (default 24 = quarter note)
- number of 32nds per quarter note (default 8 32nd per quarter note)

The MIDI clock ticks is the most important piece of information for defining the beat.  "24" means a quarter note, "12" means eighth note, "36" means dotted-quarter note, "48" means half note, and so on.

I don't know what changing the number of 32nds per quarter would mean (the last value), as I have not see a MIDI file that ever does that...  In theory it can be used to do similar things to the clock ticks, but by modifying the definition of a quarter note.   For instance, you could set this parameter to 32 for Renaissance music, since the beat is typically at the whole-note level.  The delta ticks in the data would represent quarter notes, but the time signature would say to treat them like (modern) quarter notes.

Basic time signature example: 4/4 would be these four parameters:
- 4        = four beats per measure
- 2        = two to the 2 power = 4 for the denominator
- 24      = beat at quarter note rate
- 8        = the world is sane

2/2 (cut-time) would be:
- 2
- 1  (2^1 = 2)
- 48
- 8

The bpm tempo would be twice as slow as the qpm tempo since the clock ticks parameter is double the default for quarter notes.  If the tempo is 500000 usec, that would be 120 qpm, but 60 bpm:

```
     1000000 / 500000 * 60 = 120 QPM * 24/48 = 60 BPM
```

6/8 (compound time):
- 6
- 3    (2^3 = 8)
- 36
- 8

In this case the clock ticks at 36 represents a dotted quarter note, so the beat is a dotted quarter note, and a tempo of 120 quarter-note-per-minute would be translated into 80 beats-per-minute:

```
       1000000 / 500000 * 60 = 120 QPM * 24 / 36 = 80 BPM
```

If the 6/8 were representing a simple meter:
- 6
- 3
- 12
- 8

and the BPM tempo per eighth-note beat would be:

```
         1000000 / 500000 * 60 = 120 QPM * 24 / 12 = 200 BPM
```

Perhaps adding these examples to the documentation (or summarizing them) would help clarify the subtleties.

**Comment by pe-ro** [comment]
Thanks for the clarification.  I struggled to find the actual spec and therefore had to rely on some fairly shady secondary sources.  I'll reopen this issue to make sure the Guidelines get revised.

**Comment by craigsapp** [comment]
Yes, most MIDI documentation does not note the subtlety very well, so it is difficult to track down the correct interpretation.

Here is the basic information you usually see:
![screen shot 2016-06-28 at 12 36 47 pm](https://cloud.githubusercontent.com/assets/3487289/16429719/1e75ab00-3d2d-11e6-8128-d7acec872d1a.png)
this is taken from a random webpage, but it looks like a close rip-off of the official standard.

The description is trying to explain that the beat (metronome click) for 6/8 is at every dotted-quarter note; therefore, the MIDI clocks in a metronome click should be set to 36, since 24 MIDI clocks represents a quarter note.

The 32nds per quarter note field can also influence the metronome click calculation, but that number should be left alone and assumed to always be 8 from an MEI point of view.

**Comment by pe-ro** [comment]
Closing this. Will deal with the documentation issues later.
