### ISSUE TITLE
meiHead model wrong?

### ISSUE THREAD

**Issue by kepper** [music-encoding/music-encoding#297]
the content model of `<meiHead>` seems to be wrong, as it allows `model.headerPart_sequenceOptional`, which I believe should be just `model.headerPart` (there is no model with the long name). 

https://github.com/music-encoding/music-encoding/blob/develop/source/specs/mei-source.xml#L15997

**Comment by pe-ro** [comment]
It's not incorrect, but it is somewhat misleading.  model.headerPart_sequenceOptional and model.encodingPart_sequenceOptional aren't defined anywhere in the schema, but are supplied by the ODD -> RNG stylesheet instead.  In other words, these are shortcuts that get defined explicitly later.  I've noticed this approach has an odd quirk (no pun intended!) in that the order of the expansion matches the order in which the members are defined in the schema.  Since it causes confusion, it's better to expand these references.
