### ISSUE TITLE
Add a class for things that can be inside a chord

### ISSUE THREAD

**Issue by ironchicken** [music-encoding/music-encoding#298]
At the moment the permissible contents of `<chord>` elements is `<note>`, `<artic>` and two generic models. I'd like to suggest that instead of the two specific elements, we have a `model.chordPart` as the principal content of `<chord>` (`<note>` and `<artic>` would then be members of this class).

This way, if I want to be able to add new elements to `<chord>`s in my own extensions I can just add them to the `model.chordPart` class, rather than having to modify the `<chord>` elementSpec.

Here's a patch:

[mei-source.xml.patch.txt](https://github.com/music-encoding/music-encoding/files/226396/mei-source.xml.patch.txt)

**Comment by ahankinson** [comment]
Hi Richard,

We prefer to receive proposals for changes as pull requests so that they may be reviewed and commented on with the collaboration tools available on GitHub. We have details for this process in our  [Contributing](https://github.com/music-encoding/music-encoding/blob/develop/CONTRIBUTING.md) guidelines. 

I would invite you to submit your patch as a pull request, and we can review your proposal and take it from there.

Thanks!
