### ISSUE TITLE
Separate MEI Core into modules

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#301]
Opening for discussion.

`mei-source.xml` is currently over 20,000 lines long. A few years ago @raffazizzi and I prototyped a method of separating MEI Source into different files, each containing a separate module. We were able to do this and still maintain all of the fun and fancy code completion tools in oXygen.

I think this might prove to be a bit less intimidating for moderately-experienced people who know enough to contribute to the core, but can't quite navigate all of MEI in one file.

**Comment by zolaemil** [comment]
It could also help development tools like github handling diffs. We've had problems when the diff was too bit for github to display.

**Comment by pe-ro** [comment]
I see the advantages of breaking up mei-source into more manageable units. But, I'm not sure that splitting it up by module is the best way to go because it presumes that declarations never move.  It's fairly rare, but moving a declaration from one module to another is sometimes necessary.

It would be going too far to put every declaration in a separate file, so I think a reasonable compromise might be to put **each category** of declaration in a separate file; that is, one file for macroSpec, another file for classSpec, and another file for elementSpec declarations.

The moduleSpec and constraintSpec declarations could be separated out as well, but I don't think the schema needs to that atomistic yet.  Management of the _'inclusions-within-inclusions'_ nature of that could be difficult.

**Comment by ahankinson** [comment]
I suggested a by-module separation because I thought it might help with the development of customizations. Adding a new module (e.g., Turkish Makam or Page-based layouts) or editing an existing module (e.g., neumes) would be a lot easier if we could develop this independently and keep all of the elements, attributes, and data types for that particular module together.

From what I understand, in your suggested method I would still have to spread my work over all of MEI, keeping all of the elementspec / macrospec / etc. files open and putting the appropriate definitions in there (somewhere). 

I don't foresee a big problem with moving declarations. Since oXygen and the other tools see the entire spec regardless of which file its contained in, then there shouldn't be a problem with usage and type-ahead completion, and a quick project find can still bring you to the definition.

**Comment by ahankinson** [comment]
@raffazizzi Do you still have the stuff you wrote for this when we looked at it back in Charlottesville?

**Comment by pe-ro** [comment]
Currently, develop/source/driver.xml includes the schemaSpec by using an external entity reference --
```
<!ENTITY schemaSpec SYSTEM "specs/mei-source.xml">
```
and then later --
```
&schemaSpec;
```
We can continue this pattern by creating a separate directory under /source/specs for each module and modifying mei-source.xml to have the following structure --
```
<div>
  <schemaSpec>
    &module_MEI;
    &module_MEI.analytical;
    etc.
  </schemaSpec>
</div>
```
Each included module file would provide a moduleSpec element, followed by macroSpec, classSpec, and elementSpec elements related to the module.

We can use ENTITY declarations/references first and replace them with XInclude later, if necessary.

It should be relatively easy to write an XSLT that replace the current mei-source.xml file with one that "calls" the other module files.

**Comment by ahankinson** [comment]
Bumping up the priority on this one since our discussions at MEC 2017.
