### ISSUE TITLE
Pedal member of att.timestamp2.musical

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#305]
Following up on the discussion we had about trying to make pedal markings consistent down / up sequences, wouldn't it be simple to make pedal member of att.timestamp2.musical for making it possible to encode the start and end (with ids or tstamps) in one single element? This would also make it possible to render them with a line and to automatically add pedal remember indication at the beginning of a system. I think we could have this and still allow pedal marking as they are now.

**Comment by pe-ro** [comment]
Possible, but it would only work for pedal down/up pairs.  This highlights a couple of issues:
- Sometimes pedal markings are illogical; that is, a pedal down mark may be followed by one or more pedal down indications without any intervening pedal up marks.
- Intermediate (i.e., half pedal) markings wouldn't fit this approach.

**Comment by lpugin** [comment]
- This would not mean that having only tstamp would not be possible for illogical markings. I think we have the same with dynam. They support tstamp2 but do not require it.
- We would need to think about intermediate markings. An intermediate marking could be the end / start of two successive pedal elements. Or we coud imagine having one long pedal marking (with tsamp and tsamp2) and the intermediate ones with only tsamp

**Comment by pe-ro** [comment]
There's some legitimacy to your first point above, but not the second.  In cases where there are intermediate markings, then the start / end of the sequence of pedal indications have to be separate elements that use only `@tstamp`.  For example,

Actually, I'm not so sure of this, but just for the sake of argument, let's assume `<pedal tstamp="1" tstamp2="1m+4"/>` is a useful substitute for a single, regular (down-up) pedal marking pair.

But marking the extent of a sequence (>3) of pedal marks this way, then indicating intermediate marks using only tstamp -- `<pedal tstamp="2" dir="bounce"/>` is problematic.  For instance, if the the initial mark is recorded in m. 4 and the intermediate mark is in m. 5, is the value '2' relative to the measure where the pedal element is encoded or the initial pedal element in the sequence? If it's relative to the sequence, how is membership in the sequence to be recorded?  The discussion about linking pedal marks is similar to that around linking/grouping dynamic marks -- they can't be children of something like `<pedalGrp>` because they cut across the measure hierarchy.

Another possible solution (though not a good one) would be to allow intermediate markings as **children of the pedal element**, something like --

```
<pedal tstamp="1" tstamp2="1m+4">
  <pedChange tstamp="1m+1"/>
</pedal>
```

This would capture the start and end of the sequence on `<pedal>` and location of bounce or half-pedal intermediate marks relative to `@tstamp` on their parent.  But, this is still only useful when there's a regular `down, [bounce|half]*, up` pattern to the markings unless `<pedal>` is allowed to contain `<pedal>` (so that **irregular** sequences can be recorded).  Allowing this kind of markup would introduce a much higher order of complexity than the current method.

I think the best we may be able to achieve is to keep the pedal situation the way it is currently (where tstamp is always relative to the current measure), but use an attribute to group them.  For example, 

```
<pedal tstamp="1" dir="down" grpname="pedseq1"/> <!-- in m. 1 -->
<pedal tstamp="1" dir="bounce" grpname="pedseq1"/> <!-- in m. 2 -->
<pedal tstamp="1" dir="bounce" grpname="pedseq1"/> <!-- in m. 3 -->
<pedal tstamp="1" dir="down" grpname="pedseq1 pedseq2"/> <!-- in m. 4 -->
```

This would make it easier to make sure the sequence of markings ended up in the same place relative to their staff (vertically, that is) while also making it possible to calculate/infer the time extent of the group -- in this case from m. 1, beat 1 to m. 4, beat 1 (or to be exact, just prior to beat 1, since the last member of the group is another "down".)  

BTW, I think `@grpname` (or `@groupname`) is better than `@grpid` (or `@groupid`) as the latter implies some kind of uniqueness that the former doesn't.  Also, regardless of its name, the grouping attribute may have multiple values since an element can be a member of several groups.

**Comment by lpugin** [comment]
> But marking the extent of a sequence (>3) of pedal marks this way, then indicating intermediate marks using only tstamp -- <pedal tstamp="2" dir="bounce"/> is problematic. For instance, if the the initial mark is recorded in m. 4 and the intermediate mark is in m. 5, is the value '2' relative to the measure where the pedal element is encoded or the initial pedal element in the sequence?

It is not problematic once it is decided. I would vote for making it relative to the measure is occurs, as for a normal tstamp. This also avoids the issue of the membership to the sequence

So it would be

```
<pedal tstamp="1" tstamp2="3m+4">
```

In the next measure, where we have a bounce...

```
<pedal tstamp="2" dir="bounce"/>
```

There is no need to encode a membership since the bouncing mark occurs within a pedal event. This is actually quite similar to what we have now (e.g., you leave it to the renderer) except that we can encode the start and the end with one single element. Now if you don't want to do it you just do

```
<pedal tstamp="1" dir="down">
```

In the next measure

```
<pedal tstamp="2" dir="bounce"/>
```

And up two measures later

```
<pedal tstamp="4" dir="up">
```

**Comment by pe-ro** [comment]
Mixing of these two pedal markup styles (your first 2 examples vs. the last 3) would always be a possibility because the current method (as in your last 3 examples, or is that a single example?) must be preserved in order to capture illogical pedaling.  Are you ok with that?

**Comment by pe-ro** [comment]
At least now there's only one way to create pedal marks.  I thought having one way to do things was a high priority. :-)

**Comment by lpugin** [comment]
It depends ;-) One way we could see this is to say that using the markup with tstamp / tstamp2 is recommended when the pedals are represented with a line (a line always stop somewhere, so I assume we cannot have illogical pedal marks with lines, can we?) and that the current markup (with tstamp only) is recommended with atomic pedal marks. Then of course illogical markup is possible. 

This also aligns with the idea is that in MEI we usually avoid to encode the start and the end of something with two elements but instead use one with a start and an end (ids). At least I thought this was a high priority... ;-)

**Comment by pe-ro** [comment]
Conflicting priorities, whodathunkit?  ;-)

I agree that "illogical" pedal marks aren't possible when there are lines.

Is there good use for Schematron here?  That is, a test that a sequence of pedal marks intended to be rendered with lines be "logical" -- have a "down" and an "up"?  If that's the case, do we still need `@tstamp` and `@tstamp2`?

I'm not trying to be obtuse, just exercising the various possibilities. :-)

**Comment by lpugin** [comment]
There are always various possibilities. I cannot say much about a possible good Schematron rule here, but `@tstamp2` and adjusting the guidelines would do it. I find it simpler to have the start and end in one element and quite MEI-like.

**Comment by lpugin** [comment]
Actually we already have `@endid` on pedal. What purpose does it have?

Another way I can imagine would be to enforce the presence of a `@next` when a pedal mark is intended to be rendered with a line. This would probably make a Schematron rule easier to define. It could also check that an up mark has no next. Something like:

```
<pedal tstamp="1" xml:id="p1" dir="down" next="#p2">
<pedal tstamp="2" xml:id="p2" dir="bounce" next="#p3"/>
<pedal tstamp="4" xml:id="p3" dir="up"/>
```

**Comment by pe-ro** [comment]
`@endid` marks the end of the pedal mark. This is all the more reason to add `@tstamp2`, isn't it?

We can't force `@next` to be present if the analytical domain can be removed/ignored.  But the addition of `@tstamp2` is sufficient, isn't it?

**Comment by lpugin** [comment]
Yes, I think so.

**Comment by pe-ro** [comment]
Consider it done.

**Comment by lpugin** [comment]
Great!
