### ISSUE TITLE
Add schematron warning rule to check that startid is not used with tstamp

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#310]
Follows discussion https://github.com/music-encoding/encoding-tools/issues/3

Also applies to endid and tstamp2

**Comment by pe-ro** [comment]
@lpugin: Should `@dur` be disallowed if either of `@endid` or `@tstamp2`  is present?

**Comment by lpugin** [comment]
@pe-ro : yes, I think so.

**Comment by rettinghaus** [comment]
As `@tstamp`is more _human readable_ than `@startid` it can be desirable to encode both. If they don't match it lies in the responsibility of the encoder. I think it would make more sense to have a simple tool that checks plausibility than to have a schematron warning.

**Comment by lpugin** [comment]
If it is for improving human readability, then I would recommend to use XML comments.

**Comment by pe-ro** [comment]
I'm going to flip-flop here, as I tend to agree with @rettinghaus.  Although I don't have time to do it at the moment, this has got me wondering if it would be possible for schematron to do the plausibility check and warn if `@startid` and `@tstamp` conflict. Hmmm ...

**Comment by kepper** [comment]
I've done this kind of thing in XSLT, so it should be possible to do it in Schematron. It wouldn't be cheap to compute, though… Maybe a simple once-per-file schematron check somewhere (maybe on the music element?) that just warns about the simultaneous presence of startid and tstamps and asks the user if that is intended is sufficient as first indicator of a potential problem. A dedicated XSLT (or web service, or whatever) could then be used to pull out the real problems…

**Comment by pe-ro** [comment]
Thanks for the confirmation/suggestion.  However, I'm still leaving the priority set to "Low" and the milestone as "Someday". :-) 

 In the meantime, as @rettinghaus suggested, it's up to the encoder to make sure there are no conflicts.

**Comment by lpugin** [comment]
As @kepper pointed out it would not be easy to have contradicting information be highlighted via Schematron. So I personally think a warning for making people aware that it is not a good practice to use both would be a good compromise. If people want to have both and are annoyed by the warning they can make a customization to remove it. But if this is not a good idea we should just close the issue.

**Comment by pe-ro** [comment]
How about a mild warning, something along the lines of `Only one of `@tstamp` and `@startid` is necessary.`?

**Comment by kepper** [comment]
I would add a "usually" to that sentence (because sometimes it does make sense, even though it causes problems for generic tools). If some day we have a web service to check for problems resulting from contradictory information, we may add a reference to that. However, a single mild warning (= not on every occurrence) seems appropriate to me…

**Comment by pe-ro** [comment]
I disagree.  A warning on every occurrence is necessary to pinpoint the location of the error(s).

**Comment by kepper** [comment]
I see your point, but I'm not so sure. Even with only a warn-level statement, the file isn't technically valid (Oxygen doesn't show a green box, but a yellow one). If you get a warning on every occurence, these warnings may occlude other (warn-level) problems in the file. Or, to use a german saying, you might not be able to see the wood because of all the trees around. 
However, I think it's possible to get the best of both worlds. Why not have a single warning for the whole file, which
- suggests a way to spot all those occurrences ("use the following xpath to identify potentially misleading elements: `//*[@tstamp and @startid]` ")
- references a more thorough description of the problem somewhere in the guidelines. There, we can explain why those contradictions may cause problems and how to deal with them (use my FreiDi XSLT or similar)
- suggests a way how to prevent this warning in case that the encoding has those concurring attributes on purpose

The last point leads us back to the idea of a more formalized `<encodingDesc>` element. I have no idea how this should look ile (yet), but I imagine something that says "it's ok to have those two attributes side by side, and I won't blame generic tools when they fail", or maybe even an additional indication which attribute should be prioritized by generic tools. In essence, the schematron in question would only trigger when both attributes rival somewhere, and no general statement in the header explains the situation.

**Comment by rettinghaus** [comment]
I'm still not there! Let's take a step back on this problem. Basically this wouldn't be a thing for the encoder to bother as long as every software would know how to handle contradicting statements. 
Imagine some nonsense like: 

> `<ornament startid="wurst" tstamp="523" tstamp.ges="2.4">`  

How should software react to this one? So the guidelines should IMHO clearly state what software is expected to do in such cases. Something like: 

> … If `@tstamp` and `@startid` are used together interpreters will prefer `@startid`.

And of course a fallback rule should be defined. First try startid, second tstamp, finally tstamp.ges.

**Comment by lpugin** [comment]
I doubt there will ever be an agreement on what the order should be but we can try. If you use both this is already a Sonderfall so I imagine that the order of precedence desired will always depends.

**Comment by kepper** [comment]
I understand your motivation, but I don't believe that MEI can take a general decision on the order of things. If we could do that, we're pretty close to thrashing the other options right away. For one project, it might be perfectly reasonable to prefer `@startid` over `@tstamp` (while using both), while another project might do it just the opposite. My suggestion is to add a (machine-readable) way to express how an encoding is meant. For the time being (and in the future, for projects that don't use these possibilities…), I believe the only way is to break nicely – take a decision of your own, try to make the best of what you get then, and output a warning that helps users to revise their encoding in case they don't like what you did. I would turn the argument around: It's upon you to provide sufficient documentation for your tool that users will easily know about it's assumptions and requirements. You could even provide a Schema (preferably written in Schematron, as you can have multiple of them) that checks for compatibility. Then, it's up to the user of your tool to make sure her files comply to that…

**Comment by rettinghaus** [comment]
I'm totally with you @kepper ! Although I still think best approach would be having a default code of conduct (that could be easily overwritten by encodingDesc).

**Comment by pe-ro** [comment]
A machine-readable/-actionable encodingDesc is some ways off in the future.  But, we can provide a warning when potentially conflicting attributes are present right now with little effort.  

BTW, contrary to what @kepper says, a file with warnings is not invalid.  The point of warnings is that they alert the encoder to problems without invalidating the file.

The desire not to hide the trees in the forest is understandable, however, a single warning at the top of the file, even with instructions on how to find each individual problem, is not helpful to the novice or naive encoder.  I believe it's best to locate a trouble spot as precisely as possible; that is, to raise a warning for every offense.  The fact that oXygen will light up like a Christmas tree when there's a lot of offenses is a good thing.  It's an immediate signal that the file has a large number of problems.

**Comment by lpugin** [comment]
Is there a way to pass a parameter to a Schematron schema? For example, a way to say "please to not raise the warning for conflicting ids", maybe with a rule id to deactivate? This would be similar to what can be done with compiler warnings. If this is possible, then we can have warning for all cases by default and leaving people turning this off if they do want to keep both values and want to make sure the warnings do not hide another tree.

**Comment by kepper** [comment]
But the mere fact that both attributes are present isn't necessarily a problem. One reason to have them both is actually to simplify processing, when one tool expects `@tstamp`, and the other operates on `@startid`. It's just that there is the _potential_ for contradictory information. At the same time, both attributes allow to encode nonsense on their own, even when being used solely (think of too high values as tstamps or startids pointing to stuff like layers). There's nothing wrong with lighting a Christmas tree when there are actual errors or problems, but I would suspect that in this case, we end up with at least 90% false positives – people won't be wrong every single time, and if they are, they have much bigger problems to start working at… 

Of course you're right about validity / invalidity, but the distinction seems a bit technical, especially when you try to argue with novices and naive encoders. Admittedly, in case the naive encoder is some piece of software, it may actually make a difference, but in that case, it's the programmer's job to make sure tstamps (or startids, depending on where it starts) are calculated properly. A single indication that this combination may cause problems should be sufficient in that case as well, I believe.

**Comment by kepper** [comment]
> Is there a way to pass a parameter to a Schematron schema?

What we can do quite easily is to put these rules into a separate Schematron file that people may or may not add to their instances. If you want to keep these rules in the main schema, the only solution I know is to check for something in the MEI instance, hence my suggestion of a more structured encodingDesc. However, I'm well aware that this is a huuuuge can of worms, and I'm not saying we should open it right away without thorough consideration of all the consequences.

**Comment by lpugin** [comment]
> One reason to have them both is actually to simplify processing, when one tool expects @tstamp, and the other operates on @startid.

Since when do we try to simplify processing ;-) ? This is the whole point. It is double encoding, which is for me an extremely bad practice. It can simplify your life right now but will surely create problems later. Along the same lines: having `@pname` and `@oct` and at  the same time `@ploc` and `@oloc` would greatly facilitate processing but would be equally bad for me.

**Comment by kepper** [comment]
We're not trying to do much anything about processing _as MEI_. However, individual projects may (or may not) have perfect reasons to do just that, either during the whole lifetime of a file or just for some steps in the workflow. If we really want to start to patronize ours users, we should focus on making them use customized schemata for each step in their workflow. Obviously, this is wishful thinking, and we can't do much more than suggestions and simplifying the process, but the same applies to processing. We can indicate the potential problems of certain attribute (or other) combinations, but we have to live with the fact that our users may be smarter than we are. We (this time wearing the software developer's hat) just have to be equally clear that our tools won't accept everything under the sun, with clear indications of what is compatible and how we interpret unclear situations. I believe the best deal is that we don't restrict the user to the most common way to do things, and we don't blame the software for not being able to cope with that. In the Freischütz data set, by intention we provide not only our (custom) raw files, but also exports that can be used more easily. I strongly believe that only the users / projects have sufficient knowledge about their data to ensure compatibility with _generic_ tools like Verovio or similar.

**Comment by lpugin** [comment]
OK, I do not think we will reached a consensus here. I would suggest to close the issue. It can always be re-opened some day.

**Comment by pe-ro** [comment]
Closing now -- 3, 2, 1, boom!

**Comment by lpugin** [comment]
@kepper : one more general comment (not directly related to this particular issue that is now closed)

> If we really want to start to patronize ours users, we should focus on making them use customized schemata for each step in their workflow. Obviously, this is wishful thinking, and we can't do much more than suggestions and simplifying the process, but the same applies to processing.

I think the opposite way. That is for us to think what are the areas where we can reasonably make the MEI schema more constraining or provide more feedback about issues related to the same information being provided twice. This issue was one example and I assume that having only one of either `@startid` or `@tstamp` is a valid approach in more than 90% of the cases - at least. (I just came across another one with `@artic` on note together with the same in an `<artic>` child.) Then customization can come in the game for more advanced projects that can remove some of these constraints. Encouraging users to create customizations for such cases is hopeless and not very productive. It will never happen anyway. Oppositely, it would not cost much for specific projects to have a customization if they need some more freedom.

**Comment by kepper** [comment]
@lpugin, I apologize that my tone was too harsh. 

I completely understand your position, and (according to my job description) 40% of me fully agree. I think this is the eternal difference between a software developer perspective and a modelling perspective. As a software developer, I'd like to cover as close to 100% of the standard as I can get. If information is redundant at first sight, that's a problem, because the decision that I need to take might be different than the encoder's original intention. As I cannot get closer to the 100% on that path, it seems natural to further restrict the standard, which, in a way, is like defining 80% as the new 100%. Ultimately, this puts the burden of becoming compatible onto the encoder. In reality, nothing really changed, it's just a matter of words and definitions. 
If I take a modelling perspective (which would be much more in line with the TEI), the situation seems quite different. In this world, there is no "correct" or "generally good" model: The quality of a model is measured in how well it allows to capture and address the research question at hand. While we don't seem to have the same variety of research questions in MEI that TEI is facing, we're still all but uniform. While I wholeheartedly agree that we should seek to remove redundancy and simplify MEI where possible, I believe we need to protect the possibility to use MEI in creative ways for research – otherwise, it'll be no more than a (potentially) better designed MusicXML. Coming back to the percentages, in this world 100% aren't sufficient either. Every project I worked in extended MEI by inventing a bunch of new elements and attributes. Some of them turned out to be useful additions to generic MEI and eventually ended up in the standard, others were to specific for such an inclusion. In a way, this is already the situation that you recommend – we extended the standard for project-specific reasons. In essence, we just disagree on where to draw the line. 

To put it differently, we're discussing if MEI should aim for interchange vs. interoperability. I recently found a very helpful article on that: http://dh2015.org/abstracts/xml/HOLMES_Martin_Whatever_Happened_to_Interchange_/HOLMES_Martin_Whatever_Happened_to_Interchange_.html. Following Holmes' definitions, I believe that MEI is (and should be) focussed on interchange. However, we need to define subsets of MEI for interoprability, and it is the responsibility of each project or user to ensure interoperability (both with other projects and generic tools) by mapping its internal MEI data to these subsets. Of course the definition of what is 100% has to be subject of discussion, and I'm sure we'll have this kind of discussion over and over again. However, first we need to reach a consensus if MEI is meant for interchange or interoperability. 

P.S.: The fact that we're failing to make people use customizations is indeed a major issue, and I believe we need to address that rather sooner than later – but its a separate issue…
