### ISSUE TITLE
Coloring figured bass

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#337]
Neither `<f>` nor `<fb>` allows `@color` but should.

**Comment by pe-ro** [comment]
@rettinghaus: Elements that don't necessarily have textual content, like `<accid>` allow the use of `@color`.  However, those elements that contain text, like `<f>`, allow **_the content**_ to have color, not **_the container**_.  For example, to create a red figure, use

```
<fb>
    <f><rend color="red">6</rend></f>
    <f>4+</f>
    <f>&#x266E;3</f>
  </fb>
```

Of course, that's not the least verbose solution when the entire figure is colored, so allowing `@color` on `<fb>` and/or `<harm>` may be a good idea.  It may be better to address this issue, however, in the larger context of a style language addendum to MEI.  It may take a while to get to that discussion, but unless you have specific examples you're attempting to encode, I'd prefer to wait rather than make changes that have to be undone after those negotiations.

**Comment by rettinghaus** [comment]
@pe-ro: I got this, and `<rend>` would do just fine. But I was wondering if this wasn't an unnoticed inconsistency as `<verse>` allows `@color`. Also <fb> doesn't necessarily have textual content if you use `@extender` and in that case you could't style that line.

**Comment by rettinghaus** [comment]
… and for now it isn't connected to an actual encoding problem.

**Comment by pe-ro** [comment]
Precisely -- `<verse>` allows `@color` because it doesn't have textual content.  `<syl>` doesn't allow `@color` because it has textual content, where `<rend>` can be employed.  In your case, `<fb>` is analogous to `<verse>` and `<f>` is similar to `<syl>`.  So, yes, there's some inconsistency here and it would be good to resolve it.  But, the question is how and when to carry out that resolution: by adding `@color` to `<fb>` or taking a larger view (and more comprehensive action) regarding styling and rendition in general.

It's true that currently an extending line can't be styled differently from the thing it's attached to.  But, new attributes, `@extender.color`, for instance, can be added to the `att.extender` class.  We'll get to that someday.  :-)

**Comment by ahankinson** [comment]
Can this issue be closed now?

**Comment by pe-ro** [comment]
@ahankinson: Yep.  Closing now.
