### ISSUE TITLE
Making rend attribute part of an attribute class

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#344]
Is it correct that `@rend` is not part of an attribute class but is defined directly in `rend` and `del`? If yes, is there any reason why not to have it part of a attribute class? Can we change this?

**Comment by pe-ro** [comment]
I don't immediately see any reason why `@rend` can't be placed in an attribute class.  Does `att.textrend` sound like a good name for the class?

**Comment by lpugin** [comment]
It does for me. Thanks!

**Comment by kepper** [comment]
I wonder if att.textrend is a good name for using it on del. At the same time, we could have a separate attribute class there, since "bold" or similar are not very useful suggestions for a deletion anyway ;-)

**Comment by pe-ro** [comment]
Who's to say how deletions should be rendered?  We must remember that we're not only trying to enforce a certain set of expectations on the rendered output, we're also attempting to capture any non-standard practices.  I wouldn't personally choose to render deletions as **bold text**, but someone else might/may have.  ~~Strikethrough~~ is a convention that doesn't always hold true.

**Comment by pe-ro** [comment]
Related to this -- multiple schemas may be used during the life-cycle of a document.  At least 2 are often necessary: a tighter one for document authoring and a looser one for document display.  We must be careful not to turn MEI into solely one or the other.  That's what customizations are for.  For example, I think of MEI Go! as an authoring schema where one could coerce users into using only ~~strikethrough~~ for deletions.

**Comment by kepper** [comment]
As long as we don't suggest values for rend, it doesn't make a difference anyway. If, however, we have some more detailed documentation on att.textrend (or whatever it may be called), we should keep in mind that it's not only the rendition of texts that we're describing, but also of deletions. That's all I'm trying to say :-)

**Comment by pe-ro** [comment]
This is an argument for the _status quo_; that is, separate definitions of `rend/@rend` and `del/@rend`, even though presently they point to the same data.TEXTRENDITION datatype declaration.  If we were to create a datatype for the values of `del/@rend`, the only way to invoke it would be if there were different attribute definitions.

Another approach, as I believe Laurent was suggesting, is to treat `@rend` the same everywhere even though some values may not make sense in all situations.  In my earlier comments I was attempting to say that we can't know how deletions have been rendered in all cases. (And this is what `@rend` captures -- how the deletion is rendered in the original document, not how it should appear in the output.  That's the role of a possible future `@style` attribute.)

Related to this change, I now believe the values of `add/@method` are too generic; that is, they're really an attempt to type/classify the addition.  Now that `@type` is available universally (or soon will be), it can be used here, so I propose to replace `add/@method` with `@where` (so named because "place" is already in use) for recording the placement of the addition.

The reason this is related to the `@rend` question is because the goal is to clarify the distinction between where the addition is located and how it's rendered.  Of course, the rendition of `<add>` and `<del>` elements can be captured by a `<rend>` child element or by the `@rend` attribute (but only in the case of `<del>` at the moment -- a circumstance that the addition of `@where` makes it possible to resolve).  

Suggested values for `@where` will be: 
- above     (above the line)
- below     (below the line)
- botmar   (at the foot of the page)
- topmar   (at the top of the page)
- leftmar   (at the left of the page)
- rightmar (at the right of the page)
- opposite (on the opposite, i.e. facing, page)
- overleaf  (on the other side of the leaf)
- end         (at the end of e.g. chapter or volume)
- inline      (within the body of the text)
- inspace   (in a predefined space, for example left by an earlier scribe)

These values (except for "above" and "below") apply equally to musical text and "wordy-like" text.  But, placement on another staff isn't addressed here.  Let's get the relatively simple stuff out of the way first.  :-)

**Comment by kepper** [comment]
> Am 19.10.2016 um 00:02 schrieb pe-ro notifications@github.com:
> 
> This is an argument for the status quo; that is, separate definitions of rend/@rend and del/@rend, even though presently they point to the same data.TEXTRENDITION datatype declaration. If we were to create a datatype for the values of del/@rend, the only way to invoke it would be if there were different attribute definitions.
> 
> Another approach, as I believe Laurent was suggesting, is to treat @rend the same everywhere even though some values may not make sense in all situations. In my earlier comments I was attempting to say that we can't know how deletions have been rendered in all cases. (And this is what @rend captures -- how the deletion is rendered in the original document, not how it should appear in the output. That's the role of a possible future @style attribute.)

At this point, I have no real preference on either approach, but admittedly, I'm not absolutely aware of everything related to this issue right now. I'm still a little uneasy about allowing all rendition values for deletions, but we all know that we can't lock down MEI to disallow abuse – be it intentional or not. I guess either solution is fine with me…

> Related to this change, I now believe the values of add/@method are too generic; that is, they're really an attempt to type/classify the addition. Now that @type is available universally (or soon will be), it can be used here, so I propose to replace add/@method with @where (so named because "place" is already in use) for recording the placement of the addition.
> 
> The reason this is related to the @rend question is because the goal is to clarify the distinction between where the addition is located and how it's rendered. Of course, the rendition of <add> and <del> elements can be captured by a <rend> child element or by the @rend attribute (but only in the case of <del> at the moment -- a circumstance that the addition of @where makes it possible to resolve).
> 
> Suggested values for @where will be:
> 
>   • above (above the line)
>   • below (below the line)
>   • botmar (at the foot of the page)
>   • topmar (at the top of the page)
>   • leftmar (at the left of the page)
>   • rightmar (at the right of the page)
>   • opposite (on the opposite, i.e. facing, page)
>   • overleaf (on the other side of the leaf)
>   • end (at the end of e.g. chapter or volume)
>   • inline (within the body of the text)
>   • inspace (in a predefined space, for example left by an earlier scribe)
> These values (except for "above" and "below") apply equally to musical text and "wordy-like" text. But, placement on another staff isn't addressed here. Let's get the relatively simple stuff out of the way first. :-)

I agree – we don't have to build Rome on the very first day. However, I wonder who will be using those values. If I'm trying to encode the text, it doesn't matter much where the addition is placed. If, however, I'm trying to encode the document, the information provided by these values is probably not sufficiently precise: which page is meant by "end", or where exactly on the backside of the leaf is it placed? Of course it's possible to combine this @where with @facs, in which case @where is a kind of semi-semantic explanation that saves the user from analyzing the facsimile to qualify the position of the addition from <zone>s only…

Just for giggles, what about an attribute @relativeTo which points to some other element – a measure, a staff, a pgFoot. From there, visual offsets or similar could be used. Of course this will result into defining an origin, bounding boxes and all these things (not that we haven't discussed them elsewhere already…), but one could have the "semantic" connection offered by the value list above, and enrich from there with visual information as needed.

I'm not saying this is any better, I just want to see some alternatives – they help me better understand the problems and benefits of this…

**Comment by pe-ro** [comment]
> I agree – we don't have to build Rome on the very first day. However, I wonder who will be using those values. If I'm trying to encode the text, it doesn't matter much where the addition is placed. If, however, I'm trying to encode the document, the information provided by these values is probably not sufficiently precise: which page is meant by "end", or where exactly on the backside of the leaf is it placed? Of course it's possible to combine this @where with @facs, in which case @where is a kind of semi-semantic explanation that saves the user from analyzing the facsimile to qualify the position of the addition from <zone>s only…

`@where` is not a complete rendering solution, nor is it intended to be.  As you point out, other mechanisms should be employed for detailed placement.  `@where` provides semantic information that I  believe could be useful for textual analysis.  It separates semantic info from layout/physical description captured in `@rend` or `@style` (planned in future versions of MEI to capture output rendition) and provides a measure of compatibility with TEI's `@place` attribute.

> Just for giggles, what about an attribute @relativeTo which points to some other element – a measure, a staff, a pgFoot. From there, visual offsets or similar could be used. 

Relative placement can already be handled using `@startid` and one of: `@ho` (horizontal offset), `@to` (time offset), `@vo` (vertical offset) -- or for those entities (like a hairpin) that need to indicate both starting and ending offsets, a `@startho`, `@startto`, `@startvo` and `@endho`, `@endto`, or `@endvo` pair.  These could be applied to `<add>` at some point.  Until then, `@where` may be sufficient for many people's needs.

**Comment by lpugin** [comment]
Sorry, I am a bit lost in this discussion. Is the idea to have `@rend` to be of a different type in `del` and in `rend`?

**Comment by pe-ro** [comment]
I would prefer that `@rend` NOT have different values in `<del>` and `<rend>`.  The only way to allow them to have different value lists is to have 2 definitions of `@rend` -- either directly within `<del>` and `<rend>` or by having 2 different attribute classes, which the elements refer to.  I'd rather have one definition and, if necessary, create schematron rules that disallow certain values in each element.  I say "if necessary" because it's also possible for software to ignore meaningless values.

**Comment by lpugin** [comment]
Having one single attribute class seems OK to me, but again I cannot fully judge of the implications in the use of the related elements.
