### ISSUE TITLE
Dotted Glissando?

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#356]
I'm not sure if this is just a bit of notation I'm not familiar with, or if the `<gliss />` element is a member of a class that it shouldn't be, but should `@dots` be available on `<gliss />`?

**Comment by pe-ro** [comment]
If you look carefully, you'll see that `@dots` is in the logical domain; that is, it's provided via `att.gliss.log`.  So, `@dots` is about recording the duration of an event.  That kind of event, a glissando in this case, may or may not have dots actually displayed.  For example, `<gliss type="myGliss" dur="2" dots="1">gliss.</gliss>` indicates a glissando with a duration of 3 beats (in 4/4), but glissandi never have augmentation dots in the notation.

**Comment by ahankinson** [comment]
Hm. In that case, since it's a performed but not notated duration, wouldn't a decimal value in `@dur.ges` be most appropriate?

**Comment by ahankinson** [comment]
`<canOfWorms>` 😄

**Comment by kepper** [comment]
or, is it reasonable to think of a gliss as control event, not as event? So don't use dur, but startid / endid  instead?

**Comment by pe-ro** [comment]
`<canOfWorms/>` is accurate. :smile:

As Jo suggests, one should use `@startid` and `@endid` instead.  `@dur` and `@dots` are present though to maintain consistency between `<gliss>` and other event-like elements.

Yet another example of why customization is your friend. :)

**Comment by pe-ro** [comment]
This could be an opportunity to think about moving `@dots` into the visual domain, though.

**Comment by ahankinson** [comment]
Yeah, I'm using `@tstamp` and `@tstamp2`, so it's not a big deal. I wasn't sure what a dotted glissando was, though, and if that needed to be addressed.

**Comment by pe-ro** [comment]
@kepper, in CMN a glissando should be treated as a control event.  That's why one should use a `@tstamp` and `@tstamp2` or `@startid` and `@endid` pair.  But, In keeping with MEI's role as a framework (and not a file format), `<gliss>` allows `@dur` and `@dots` attributes for use in mensural-like notations that include glissandi -- pre-modern tablature perhaps or some Asian notation.

Andrew's question, though, makes me wonder if it wouldn't be better to remove `@dur` and `@dots` from `<gliss>` now because they could always be reinstated when the need arose.

**Comment by kepper** [comment]
Actually, I never used gliss so far, and I didn't look into the guidelines on what is allowed and what is not. Your argument sounds reasonable, but instead of removing it completely, can't we include the required classes through some repertoire-specific filter class, that is gliss.log.cmn (or similar)?

**Comment by pe-ro** [comment]
Having thought about it a little more, I'm inclined to leave `@dur` and `@dots` on `<gliss>` in order to be consistent with all the other elements that allow them. However, I think that we should also add remarks to the `att.augmentDots` class that explains that because `@dots` is in the logical domain, using it won't necessarily result in the display of augmentation dots.

**Comment by pe-ro** [comment]
How about --

The `@dots` attribute records the number of augmentation dots necessary to represent a non-power-of-two duration. This is frequently, but not always, the number of dots displayed. For example, `<note dur="4" dots="1"/>` will result in a displayed dot, while `<gliss dur="4" dots="1"/>` will not.
