### ISSUE TITLE
Revise content model of <lyrics>

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#360]
Is there a way to place verse/syl text at time points other than the start of a note?  I would like to display multiple verse syllables attached to a specific note, but with one or more syllables placed at different delays after the start of a note.  This would be something like making a syl/verse a floating element, and I could probably hack functionality by using a text direction or harm element to insert the floating verse-like text, but using the verse/syl system would be a better way. 

`verse@rhythm` seems related to this:

http://music-encoding.org/documentation/3.0.0/verse
> @rhythm (optional) Used to specify a rhythm for the lyric syllables that differs from that of the notes on the staff, e.g. '4,4,4,4' when the rhythm of the notes is '4.,8,4.,8'. Value of datatype string. att.verse.log 

Here is an example of approximately what I want to do, with the word "two" placed a half-note after the start of the note it is attached to:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2016-11-24 00:33:39</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Transcoded from Humdrum with Verovio version 0.9.13-dev-bf3f7d9</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-0000000033479171">
                        <staffGrp xml:id="m-0000000630645581">
                            <staffDef xml:id="staffdef-0000001491850369" clef.shape="G" clef.line="2" meter.count="16" meter.unit="4" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000001273262437">
                        <measure xml:id="measure-L4" n="1" right="end">
                            <staff xml:id="staff-L4F1" n="1">
                                <layer xml:id="layer-L4F1" n="1">
                                    <note xml:id="note-L5F1" dur="1" oct="4" pname="c" accid.ges="n">
                                        <verse xml:id="verse-L5F2" n="1">
                                            <syl xml:id="syl-L5F2">one</syl>
                                            <syl tstamp="3" xml:id="syl-L6F2">two</syl>
                                        </verse>
                                    </note>
                                    <note xml:id="note-L7F1" dur="1" oct="4" pname="d" accid.ges="n">
                                        <verse xml:id="verse-L7F2" n="1">
                                            <syl xml:id="syl-L7F2">three</syl>
                                        </verse>
                                    </note>
                                    <note xml:id="note-L8F1" dur="1" oct="4" pname="e" accid.ges="n">
                                        <verse xml:id="verse-L8F2" n="1">
                                            <syl xml:id="syl-L8F2">four</syl>
                                        </verse>
                                    </note>
                                    <note xml:id="note-L9F1" dur="1" oct="4" pname="f" accid.ges="n">
                                        <verse xml:id="verse-L9F2" n="1">
                                            <syl xml:id="syl-L9F2">five</syl>
                                        </verse>
                                    </note>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

Of course `@tstamp` is not allowed, so won't display as desired in verovio:

<img width="437" alt="screen shot 2016-11-24 at 01 40 19" src="https://cloud.githubusercontent.com/assets/3487289/20593381/0485c32c-b1e7-11e6-903c-c494b9c380df.png">

Here is how it is done in Humdrum (so I am wondering how I can convert such cases into MEI):

```
**kern	**text
*clefG2	*
*M16/4	*
=1-	=1-
1c	one
.	two
1d	three
1e	four
1f	five
==	==
*-	*-
```

Also an example of attaching a verse to a rest (which I cannot also convert):

```
**kern
**kern	**text
*clefG2	*
*M2/1	*
=1-	=1-
1c	one
1r	two
==	==
*-	*-
```

lilypond has a similar capability, by giving durations to the lyrics:

http://lilypond.org/doc/v2.19/Documentation/notation/common-notation-for-vocal-music#manual-syllable-durations

**Comment by rettinghaus** [comment]
We have the `<lyrics>`, but they are not part of timing attribute classes. 
@pe-ro Where is the point in having that without the possibility to exactly point it somewhere? Am I missing something?

**Comment by pe-ro** [comment]
Sorry I dropped the ball on this one.

@craigsapp, `<syl>` is a member of att.visualOffset, meaning that it can have a horizontal offset in either visual or time-based terms.  For example, 
```
<syl ho="2vu">two</syl>
```
indicates that the text should be displaced 2 virtual units to the right (where 1 unit = 1/2 distance between two staff lines), while 
```
<syl to=".25">
```
says the text should be displaced 1/4 of a beat to the right.  Negative values are allowed too.

@rettinghaus, the `<lyrics>` element is intended to be used with sung/singable text that is not written into the notation, as when additional verses to a song are printed at the end.  For example, when verses 1-3 are printed under the notes, but verse 4 comes after the notation --
```
<lyrics>
   <verse n="4">
      <syl synch="#n01 #n04">One</syl>
      <syl synch="#n02">Two</syl>
      <syl synch="#n03">Three</syl>
   </verse>                  
</lyrics>
``` 
The `<syl>` elements can use `@synch` to point to note/notes.

**Comment by rettinghaus** [comment]
@pe-ro If they're "not written into the notation" then the examples given in the guidelines don't make any sense to me. 
* 1st: In Figure 52 they are actually written into the notation 
* 2nd: If `<lyrics>` weren't meant to be used this way, why are they allowed within `<measure>`?

**Comment by pe-ro** [comment]
@rettinghaus, Sorry, I wasn't clear.  I should've said that the "primary" intent of `<lyrics>` is as I described.  However, that doesn't preclude its use as in Figure 52.  Encoding the sung text this way can be helpful for processing them in a "non-notation" setting; that is, they can be more easily extracted for presentation without the staff notation.  

It can also be useful when a source is in a "non-notational" form.  It wasn't uncommon for 18th & 19th c. hymnals to be published that contained only words, not music.  For representation of these sources, it can be more meaningful to associate the words with a measure instead of parsing them out note-by-note.

**Comment by rettinghaus** [comment]
@pe-ro ok, that clear's it up a bit. But if you compare two or three 18th c. hymnals *with* notation you'll notice, that there are barely congruent measures. So encoding them in measures would make the encoder an editor.
And `<lg>` and `<l>` aren't allowed in `<lyrcis>`. To keep the visual expression of the lyrics you would have to double encode them (or use TEI, and that would make using MEI unnecessary).

**Comment by pe-ro** [comment]
@rettinghaus, If `<lg>` were added `<lyrics>` and `<syl>` were added to `<l>`, then MEI's `<lg>` could function they way you're describing --
```
<lyrics>
  <lg>
    <l>
      <syl synch="#n01 #n04">One</syl>
      <syl synch="#n02">Two</syl>
      <syl synch="#n03">Three</syl>
    </l>
  </lg>
</lyrics>
```
This looks like it could be a better model for `<lyrics>`.  Thoughts?

**Comment by rettinghaus** [comment]
@pe-ro looks good to me. This way you could easily choose between processing the visual and the semantically aspects of the lyrics. 
Are all of those elements allowed in `<rend>`? We should make shure they are, otherwise there could be problems.

**Comment by pe-ro** [comment]
@rettinghaus, The basic approach to rendition in MEI is that it must be specified *within* a semantic element, not the other way around.  So, `<syl>` can contain `<rend>`, but `<rend>` can't contain elements that aren't allowed at the text phrase level.  Since `<lyrics>`, `<lg>`, and `<l>` aren't allowed within prose, they aren't allowed in `<rend>`.  This means that groups/ranges of semantic elements can't be marked with a single `<rend>` element, but it prevents complex interaction between `<rend>` and everything else.  Mostly it means that the content model of `<rend>` is less prone to (ab|mis)use.

Is there a problem with this approach in this case?

**Comment by pe-ro** [comment]
@rettinghaus, Finally I remembered the real reason why `<lyrics>` is allowed within `<measure>`.  It's there for the capture of vocal text that isn't directly associated with (i.e., written under) the notes.  For example, in early music there's vocal text (sometimes an incipit, sometimes complete) that the performer is supposed to sing, but there's no indication of how the words fit the music.  Sometimes this feature is carried forward into the modern transcription of the pre-modern notation, so markup for this is needed at the measure level.

It's a kind of directive, and could perhaps be handled by `<dir>`, but I think it's distinctive enough to need its own element.  My original thinking was that `<lyrics>` should have a structure similar to that used for vocal text written directly under the notes; that is, use `<verse>`, etc.  But, the changes outlined above for `<lyrics>`; that is `lyrics (lg+)` and making `<syl>` a member of `model.textPhraseLike.limited` (allowing it to occur within `<l>`), as well as providing better documentation of the use of `<lyrics>`, is a better approach.  This means that text not written under the notes is marked up the same way whether it occurs within or apart from the notation.

**Comment by rettinghaus** [comment]
That sounds good. Thanks!

**Comment by pe-ro** [comment]
Reopening because of the issues raised by the mensural interest group on MEI-L.

I've finally realized that the presence of `<lyrics>` within `<measure>`, etc. (anywhere other than as a descendant of `<div>`) doesn't help to resolve the issue of the capture of vocal text presented as part of the notation, but not written directly under the notes. It's better to create an additional element (or elements) for this purpose.  In fact, several similar elements already exist (dir, tempo, dynam, annot, etc.).  The difference between these and the new element(s) is not their behavior -- they're all just text displayed on/around the staff.  The difference is semantic -- they have different meanings/functions.  I'm asking that those familiar with the mensural repertoire suggest names for the new element(s).  At first thought, "label" might be a good choice for a new element.  But, `<label>` already exists for other purposes and, if our goal is precision, then it's too generic.

Having dealt with non-sung, non-directive, non-tempo-indicating, non-dynamic, non-annotating text, `<lyrics>` can be removed from the schema.  `<lg>` will be used for text (sung or potentially sung) not presented as part of the notation and not directly associated with staff events.  (Think of extra verses of a pop song or hymn following the notation.) `<seg>` (a new element) can appear within `<l>` to permit segmentation of this kind of text into syllables, and each syllable (i.e., seg), can be associated with one or more notes via `@synch` or `@corresp`. `<seg>` can also be used to segment the text in other ways as well, for instance into feet, half-lines, words, etc.

**Comment by rettinghaus** [comment]
@pe-ro could you please give me an example, how to encode "vocal text that isn't directly associated with (i.e., written under) the notes"?
