### ISSUE TITLE
whole-measure rest encoding

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#369]
How should/can the rests in this example be encoded:

<img width="358" alt="screen shot 2016-12-29 at 15 06 20" src="https://cloud.githubusercontent.com/assets/3487289/21556818/0e7d099a-cdd9-11e6-9e86-8eaae952d671.png">

In other words, how to encode that a "1" is shown between the staves.  Would this be a special case of `multiRest`?

Multi-rests probably have a different visual syntax, with duplicate numbers for each staff:

<img width="287" alt="screen shot 2016-12-29 at 15 09 07" src="https://cloud.githubusercontent.com/assets/3487289/21556833/3730f7d4-cdd9-11e6-8ae1-4cd95b6e86c6.png">

**Comment by pe-ro** [comment]
>  Would this be a special case of `multiRest`?

No.  It would be better to use `<mRest>`.  

But, right now, `<mRest>` can't be numbered and there's no way to specify the location of the number.  (`<multiRest>` doesn't have any method of placing its number either.)

So, I suggest we --

1. make `mRest` a member of att.numbered -- this will allow the capture of the number using the `@num` attribute; and 
2. make `mRest` and `multiRest` members of number.placement. This provides the attributes `@num.place` and `@num.visible`.  `@num.place` will keep its current values: "above" and "below".

This will provide the capability to say where the number associated with `mRest` and `multiRest` should be rendered.  However, this assumes the same visual characteristics for both elements; that is, a number rendered above or below the rest *on each staff*.

For the special case of a full-measure rest with a number shown between staves, I think it would be better to use `<mRest>`, but **not** use the `@num.*` attributes, but `<dir>` instead --

```
<measure>
  <staff>
    <layer>
      <mRest/>
    </layer>
  </staff>
  <staff>
    <layer>
      <mRest/>
    </layer>
  </staff>
  <dir tstamp="2.5" place="between" staff="1 2">1</dir>
</measure>
```
I recognize that this is somewhat of a kludge (as "1" is not a performance direction), but since this example breaks tradition, it seems logical that there should be a special case in the markup too.  In another thread we decided to use `<dir>` for other things that aren't strictly performance directions (the Peter & the Wolf example), so I don't feel doing so here is particularly egregious.  A benefit of using `<dir>` is that its contents can be better controlled typographically; that is, using `<rend>`.
