### ISSUE TITLE
Sforzando wedge

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#373]
I am coming across a lot of the following marks in piano music, so it would be good for me to encode them correctly, and/or for MEI to allow them to be encoded correctly.  Here is a demonstration of the notation causing me problems:

<img width="675" alt="screen shot 2017-01-04 at 13 10 38" src="https://cloud.githubusercontent.com/assets/3487289/21659499/e0467f60-d27f-11e6-905b-652a1f8e7297.png">

The wedges on the third beat of each measure are accent marks which affect all notes playing on that beat.  In other words it is an accent which should be encoded as a floating element rather than as a property of a single note or chord.  Is there a way of encoding this currently in MEI?  If not, then it should definitely be added.

In case you are thinking about it, these are absolutely not dynamics hairpins, so don't bother mentioning it :-) . Instead they function similarly to `sf` (sforzandos).  One possibility is that they could be encoded as sforzandos and instead rendered as wedges with some styling attribute (but this is not possible/practical at the moment, I think, since dynamics are encoded as text strings).

These are somewhat similar to `<>` which Joachim Veit brought up a while ago on MEI-L.  In that case it was a hybrid between an accent and dynamics hairpins.  In this case it is purely an accent.

**Comment by pe-ro** [comment]
I agree -- these are not hairpins.  But, they do affect dynamics and therefore fit within the definition and function of `<dynam>`.

As you say, they could be encoded as --
```
<dynam staff="1 2" place="between" tstamp="3">sf</dynam>
```
and rendered as wedges based on the value of `@type` or `@altsym` (if it were made available).

But, I believe the better approach is --
```
<dynam staff="1 2" place="between" tstamp="3"><symbol glyphnum="#xE0000"/></dynam>
```
where the value of `@glyphnum` is a reference to a SMuFL code point or --
```
<dynam staff="1 2" place="between" tstamp="3"><symbol altsym="#mySymbol"/></dynam>
```
where `@altsym` contains a reference to a symbol definition elsewhere, i.e. --
```
<symbolDef xml:id="mySymbol">
  <svg:svg/>
</symbolDef>
```
`<symbolDef>` can contain either SVG or any combination of MEI `curve`, `line`, `graphic`, or `symbol` elements, but it won't permit mixing SVG and MEI elements.  Since this will be the first implementation of this, there may be placement issues associated with `<symbol>` and `<symbolDef>`, but nothing we can't work out.

**Comment by craigsapp** [comment]
That sounds good.  I'll work with @lpugin to implement something :-)
