### ISSUE TITLE
Paradox: <staffDef> may be contained by <staffDef>, but not the other way round

### ISSUE THREAD

**Issue by th-we** [music-encoding/music-encoding#374]
I noticed that the [documentation page for `<staffDef>`](http://music-encoding.org/documentation/3.0.0/staffDef/) says that `<staffDef>` may be *contained by* `<staffDef>`, but it is not allowed to *contain* `<staffDef>`, which is contradictory. How did it slip into its own "contained by" list?

**Comment by pe-ro** [comment]
Hmmm.  That is weird, isn't it?  I'm not sure why the documentation says that staffDef may be contained by staffDef.  It must be due to a weirdness in the creation of the data dictionary. The schema certainly doesn't allow staffDef to be self-nesting.

Since @kepper is responsible for the stylesheet that generates the Guidelines, I've assigned this to him for further investigation.

**Comment by lpugin** [comment]
Along the same lines, `scoreDef` can be contained by `scoreDef` according to the documentation.

**Comment by peterstadler** [comment]
same with `<physLoc>` and `<item>` …
