### ISSUE TITLE
acc-stacc missing from artic@artic

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#375]
How should this be represented with `<artic>`?:

<img width="155" alt="screen shot 2017-01-17 at 15 00 15" src="https://cloud.githubusercontent.com/assets/3487289/22043695/b5dfd262-dcc5-11e6-8983-af4574da9a26.png">

The closest I see is `<artic artic="marc-stacc">`
on the page
http://music-encoding.org/documentation/3.0.0/data.ARTICULATION

But that would be:

<img width="161" alt="screen shot 2017-01-17 at 15 00 18" src="https://cloud.githubusercontent.com/assets/3487289/22043715/d1695206-dcc5-11e6-8be8-5169402863d2.png">

**Comment by pe-ro** [comment]
Now that `@artic` is "multi-valued", you can use --
```
<artic artic="acc stacc"/>
```

**Comment by pe-ro** [comment]
Alternatively, we can add "acc-stacc" as a value.  

Or you can use multiple `<artic>` elements --
```
<artic artic="acc"/>
<artic artic="stacc"/>
```
This last one is best if either/both of the articulation signs need to point to a user-defined symbol or a SMuFL code point (since neither `@altsym`, `@glyphnum`, nor `@glyphname` allow multiple values).

**Comment by bwbohl** [comment]
> Alternatively, we can add "acc-stacc" as a value.

That is obsolete if we can have multi-valued @artic.
Else I’m with @pe-ro.

Remember that we also could have
<note […] artic=“acc stacc” />

**Comment by craigsapp** [comment]
> `<note […] artic=“acc stacc” />`

That is good, but then I would suggest that `marc-stacc` and `ten-stacc` be retired since they are equivalent to `marc stacc` and `ten stacc`.   And/or with a phase-out period where the presence of `marc-stacc` and `ten-stacc` would generate warnings in the schematron validator.

**Comment by pe-ro** [comment]
I'm wondering if we shouldn't go in the other direction; that is, not allow artic to be multi-valued. I can't remember now why we changed that. Multiple values cause problems with altsym, etc.

**Comment by craigsapp** [comment]
Are `@altsym` and `@artic` both useable at the same time? I would think that if `artic@altsym` were present, then `artic@artic` would be ignored.  

http://music-encoding.org/documentation/3.0.0/artic

> `@altsym` (optional) Provides a way of pointing to a user-defined symbol. It must contain an ID of a <symbolDef> element elsewhere in the document. Value conforms to data.URI . att.altsym 

Would that not be "an ID *reference* of a" rather than "an ID of a"?  In other words the ID should be prefixed with a `#`?

It could be up to the person creating the articulation symbol to merge multiple articulations into a single user-defined symbol. 

Or `artic@artic` or `note@artic` could be allowed to contain ID refs in their list which would allow user-defined articulations to be included in the `@artic` list.  This would also allow for altsym ID refs to be used in `note@artic` rather than creating a child `<artic>` to store `@altsym`.

**Comment by craigsapp** [comment]
Another though: is there a difference in meaning to `@artic="ten stacc"` and `@artic="stacc ten"`.  In other words does the order imply the stacking of the articulations:

<img width="276" alt="screen shot 2017-01-18 at 11 35 29" src="https://cloud.githubusercontent.com/assets/3487289/22079906/4898765c-dd72-11e6-859c-fc945dc45b9e.png">

**Comment by pe-ro** [comment]
> I would suggest that `marc-stacc` and `ten-stacc` be retired since they are equivalent to `marc stacc` and `ten stacc`. And/or with a phase-out period where the presence of `marc-stacc` and `ten-stacc` would generate warnings in the schematron validator.

Agreed.

> Are `@altsym` and `@artic` both useable at the same time? I would think that if artic@altsym were present, then artic@artic would be ignored.

I think they should both be allowed at the same time because `@artic` carries semantic info while `@altsym` records visual info.

> Would that not be "an ID reference of a" rather than "an ID of a"? In other words the ID should be prefixed with a #?

That's right.

> It could be up to the person creating the articulation symbol to merge multiple articulations into a single user-defined symbol.

That's a good way around the many-to-one problem.  But we have to make this explicit in the Guidelines/documentation.

> Or `artic@artic` or `note@artic` could be allowed to contain ID refs in their list which would allow user-defined articulations to be included in the `@artic` list. This would also allow for altsym ID refs to be used in note@artic rather than creating a child `<artic>` to store `@altsym`.

I don't think we should go that far. First, this will cause @bwbohl to blow a gasket. :-)  Seriously, it overloads the definition of `@artic`. Second, it blurs the line between using `@artic` for semantic and `@altsym` for visual info.  So, uh, no.

> is there a difference in meaning to `@artic="ten stacc"` and `@artic="stacc ten"`. In other words does the order imply the stacking of the articulations:

Normally, the values in an attribute are unordered because there's no requirement that processors retain the order.  If we want to enforce order, it would be best to 

- use  two `<artic>` elements and provide a way to order them --
```
<artic artic="ten" order="1"/>
<artic artic="stacc" order="2"/>
```
where "1" means "closest to the staff"; or
- continue to allow `@artic` to use multiple values but add attributes (on `<scoreDef>` and `<staffDef>` for sure, perhaps other places as well) for setting the order of articulations (something like `@aboveorder.artic` and `@beloworder.artic` as well setting the order of "stackable" items generally (`@aboveorder` and `@beloworder`).  

These new attributes would be optional, so processors would have to provide reasonable defaults.  It looks like we're already headed in the direction of the second option.

**Comment by craigsapp** [comment]
Not articulations, but how would the order of these two ornament symbols (mordent and turn) be encoded:

<img width="52" alt="screen shot 2017-01-18 at 15 46 21" src="https://cloud.githubusercontent.com/assets/3487289/22087916/a328133e-dd95-11e6-8d0a-88b5171ad4e7.png">

from C.P.E. Bach, Arietta in A Major with 8 Variations, H 351 alt.

**Comment by pe-ro** [comment]
> Not articulations, but how would the order of these two ornament symbols (mordent and turn) be encoded:

Right now, control elements (of which ornaments are a subset) are not ordered.  The encoding order in
```
<turn tstamp="1"/>
<mordent tstamp="1"/>
```
could be significant, if we declare it so.  But, I don't think that's a good approach.  Just as with articulations, it would be better to use an attribute, such as `@order`, to provide a mechanism for explicitly stating the rendering order **on control events that have the same value for `@tstamp` or `@startid`**.  For example, in one edition of the Bach --
```
<turn tstamp="1" order="2"/>
<mordent tstamp="1" order="1"/>
```
but perhaps elsewhere --
```
<turn tstamp="1" order="1"/>
<mordent tstamp="1" order="2"/>
```
Again, "1" is closest to the staff, with higher numbers being farther away.  

`@order` on control elements would override the `@aboveorder` and `@beloworder` attributes set further up in the hierarchy.

Thoughts?

**Comment by lpugin** [comment]
@pe-ro you 

> Normally, the values in an attribute are unordered because there's no requirement that processors retain the order. If we want to enforce order, it would be best to use two <artic> elements and provide a way to order them
```xml
<artic artic="ten" order="1"/>
<artic artic="stacc" order="2"/>
```

Why do we need `@order` and cannot just rely on the order or the elements?

**Comment by pe-ro** [comment]
Order of the elements may not always be significant.  There could be cases where an error is introduced simply through less-than-attentive programming.  Using `@order` is a way to confirm/contradict the encoding order without actually physically re-arranging the elements.  It also provides a way to locally override `@aboveorder` and `@beloworder`.  For example, one might use `@aboveorder` to set the usual order of items, but use `@order` for the occasional deviation from that "norm" (due, say, to a printing error).

**Comment by lpugin** [comment]
I think this is up to us to decide. For examples, MEI assumes the order of the measures to be significant, and the order of the notes in a layer too.

**Comment by pe-ro** [comment]
I didn't intend to say that order isn't important.  I was just pointing out that it's not always significant.  Making it significant can lead to problems.  For instance, in
```
<measure>
  <staff n="1"><!-- some stuff --></staff>
  <staff n="2"><!-- some stuff --></staff>
  <turn tstamp="1"/>
  <dir tstamp="1"/>
  <tempo tstamp="1"/>
</measure>
```
is the turn closest to the staff or farthest away?  We could mandate one or the other, but that might make some existing files display strangely.  In other words, using encoding order places a rendering burden on encoders who may not even care about the so-called "proper" rendering of these things.  The fact that this will occur retroactively makes it worse.

Controlling placement with metadata; that is, attributes, instead of encoding order lets those who don't care about rendering encode the file in whatever order they like and gives those who do care about it more fine-grained control over it.

**Comment by lpugin** [comment]
I agree and I understand. What I am saying is that it would be good to clarify where MEI assumes order to be significant. I assume that the order of the notes in a layer is one case. We could as well decide that order of artic within a note is significant. But if people think is more important to have the flexibility to encode them in a different order, then yes we need an additional attribute for this.

**Comment by pe-ro** [comment]
I think we may be able to say that encoding order is significant for accidentals (from farthest to closest to the note head) and articulations (farthest to closest to the note head).  But I don't think the same can be said for control events (dir, dynam, mordent, etc.)

See the discussion at #390.

**Comment by kepper** [comment]
> Am 27.01.2017 um 22:55 schrieb pe-ro <notifications@github.com>:
> 
> I think we may be able to say that encoding order is significant for accidentals (from farthest to closest to the note head) and articulations (farthest to closest to the note head). But I don't think the same can be said for control events (dir, dynam, mordent, etc.)
> 

+1

**Comment by pe-ro** [comment]
When `@artic` is used on `<note>` it must be allowed to contain multiple values.  But, when it's used on `<artic>` it should only be allowed to contain a single value.  Doing so, will make it easier to deal with order of the articulations.  Am I wrong?

**Comment by lpugin** [comment]
I am not sure. You might want to use `<artic>` for having some signs above and some below, so you would still want to be able give more than one value in `@artic`. Order would still be defined by the order within `@artic`.
```xml
<note>
  <artic artic="marc harm dnbow" place="above"/>
  <artic artic="stacc" place="below"/>
</note>
```

**Comment by pe-ro** [comment]
Then I'll leave well enough alone. 😀

**Comment by pe-ro** [comment]
"marc-stacc" and "ten-stacc" values for `@artic` deprecated by 3ae9ad4.
