### ISSUE TITLE
floating beams on tremolos

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#399]
It would be good to have some attributes on `<fTrem>` to define how beams are / should be engraved. 
Sometimes beams have gaps, so there should be something like `@beam.gap.num` (`positiveInteger`) and `@beam.gap` (`data.PERCENT`).

![](http://lilypond.org/doc/v2.18/Documentation/92/lily-1760624a.png)

Compare the feature in LilyPond:
http://lilypond.org/doc/v2.18/Documentation/snippets/rhythms#rhythms-engraving-tremolos-with-floating-beams

**Comment by pe-ro** [comment]
Normally, this is determined by the rhythmic values involved, but I agree that having these additional attributes make it possible to accurately describe house-style variations and errors; that is, when the source material doesn't match conventional practices.

**Comment by pe-ro** [comment]
Of course these attributes will have to be optional, so a renderer has to provide a fallback when they're not present.

**Comment by pe-ro** [comment]
How about --
```
<!-- floating beams on tremolos, issue #399 -->
<!-- fTrem.vis no longer a member of att.slashCount; @slashCount renamed to @beams -->
<classSpec ident="att.fTrem.vis" module="MEI.cmn" type="atts" mode="replace">
  <desc>Visual domain attributes.</desc>
  <attList>
    <attDef ident="beams" usage="opt">
      <desc>Indicates the number of beams present.</desc>
      <datatype>
        <rng:data type="positiveInteger">
          <rng:param name="minInclusive">1</rng:param>
          <rng:param name="maxInclusive">6</rng:param>
        </rng:data>
      </datatype>
    </attDef>
    <attDef ident="beams.float" usage="opt">
      <desc>Captures the number of "floating" beams, i.e., not attached to stems. The value
        must be less than or equal to the total number of beams present.</desc>
      <datatype>
        <rng:data type="nonNegativeInteger"/>
      </datatype>
    </attDef>
    <attDef ident="float.gap" usage="opt">
      <desc>Records the amount of separation between floating beams and stems.</desc>
      <datatype>
        <rng:ref name="data.MEASUREMENTABS"/>
      </datatype>
    </attDef>
  </attList>
</classSpec>
```
?

Presumably, the value of `@beams` supersedes the calculation of the number of beams based on the enclosed notes' rhythmic values.  `@beams.float` can be used independently of `@beams`; that is, the encoder can rely on the renderer to calculate the number of beams, but explicitly say how many of those beams are detached from the note stems. `@float.gap` can be measured in all the usual ways such things are measured, although virtual units are likely to be the only sensible choice.

Notice that I've finally given up on calling the beam-like things "slashes" and refer to them throughout the specification as "beams"; that is, the former attribute `@slashCount` is now `@beams`.  Sometimes you just can't change existing terminology. 🙂

**Comment by rettinghaus** [comment]
I like it. But I think it could be complicated to give absolute values for `@float.gap` as you would have to set the distance between stems too for it to make sense, or am I missing something? Better would be `data.PERCENT` with 0% for no gaps, 50% for beams taking have the space between stems and 100% for no floating beams at all (even if this wouldn't be so clever). 
And why not stay consistent with naming and call the attribute `@beams.gap` (or `@beams.float.gap`)?

**Comment by craigsapp** [comment]
The gap should be an absolute value (in vus) in most cases rather than a percent.  The stretchiness of the tremolos would need to be in the black parts and not also in the gap sizes.  Otherwise, the gaps would be different sizes based on the spacing between the beamed notes, and this would look bad and be visually confusing.  Unless *I* am missing something here :-)

Here is an illustration of the difference between the two systems:

<img width="938" alt="screen shot 2017-02-09 at 01 53 18" src="https://cloud.githubusercontent.com/assets/3487289/22778141/b172ca3e-ee6a-11e6-84a3-d59099636bb9.png">

The first tremolo is the reference.  The second one keeps a constant fixed size for the gap of 1vu, and the third tremolo has a constant percentage for the gap of 10% of the distance between the tremolo notes.

The constant percentage does not look bad here, but imaging a page full of tremolos with slightly different widths.  I am imagining it to look a bit ugly/amateurish...

The lilypond example is using constant units for the gap spacing rather than percentage:

```lilypond

  \override Beam.gap-count = #3
  \override Beam.gap = #1.33
  \repeat tremolo 8 { a32 f }
  \override Beam.gap = #1
  \repeat tremolo 8 { a32 f }
  \override Beam.gap = #0.67
  \repeat tremolo 8 { a32 f }
  \override Beam.gap = #0.33
  \repeat tremolo 8 { a32 f }
```

`#1.33`, `#1`, `#0.67`, and `#0.33` are in units of staff-line spaces (2 vus).

The case of the `#1.33` gap shows a problem:

<img width="55" alt="screen shot 2017-02-09 at 02 02 12" src="https://cloud.githubusercontent.com/assets/3487289/22778444/ca75eb46-ee6b-11e6-8e7f-7d4fab0748c9.png">

This is way too short (which you are also noticing), and in this sort of case there should be a minimum width assigned to the beam or distance between the two notes of the tremolo (or minimum length of the tremolo beams, such as 2 vus).

**Comment by rettinghaus** [comment]
@craigsapp is right (again). I take back my first point, but still want the naming to be discussed :-)

**Comment by pe-ro** [comment]
There's a progression in my naming scheme; that is, "float.gap" modifies "beams.float" and "beams.float" modifies "beams".  "beams.gap" breaks the relationship pattern in that it isn't clear that it only applies to the floating beams.  "beams.float.gap" is unnecessarily verbose since the "float.gap" applies only to the floating beams.
