### ISSUE TITLE
graces behind notes

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#407]
Sorry to bring grace notes up again, but I think the values `acc `, `unacc`, and `unknown` are *semantically* not sufficiant as you cannot mark them as a "Nachschlag", i.e.

> A grace note which takes its value from that of the note preceding it.

**Comment by craigsapp** [comment]
So these are *Nachschlag*?:

<img width="539" alt="screen shot 2017-02-22 at 08 01 58" src="https://cloud.githubusercontent.com/assets/3487289/23219924/39b27786-f8d5-11e6-80aa-435d7e636297.png">

They could be considered a sub-category of unaccented grace notes...

For example, if they are not at the end of a measure, they behave exactly like unaccenteded grace notes:

<img width="395" alt="screen shot 2017-02-22 at 08 32 23" src="https://cloud.githubusercontent.com/assets/3487289/23221287/8a150780-f8d9-11e6-84d8-d3fd0df4a345.png">

An advantage to labeling them as *Nachschlag* would be that re-barring the music would place the grace notes on the correct side of a barline (before it for Nachschlag, and after for other grace notes).  But that probably will not happen very often in MEI.  In SCORE this is a problem, and Nachschlag must have a local barline on the staff to prevent them from crossing over a system barline.

Here are the two possibilities for converting the above example to 2/4:

<img width="471" alt="screen shot 2017-02-22 at 08 37 13" src="https://cloud.githubusercontent.com/assets/3487289/23221525/2d2e8ff4-f8da-11e6-9011-3823c39ea15e.png">

<img width="440" alt="screen shot 2017-02-22 at 08 36 55" src="https://cloud.githubusercontent.com/assets/3487289/23221527/2f625dd2-f8da-11e6-9541-ee326e6106ed.png">

The first one assumes the grace notes are attached to the next note, and the second example assumes that they are attached to the previous note.

Labeling Nachschlag might also be of use for grace-note kerning.  Nachschlag should always be kerned, but unaccented grace notes can sometimes be un-kerned.

**Comment by pe-ro** [comment]
@rettinghaus, by definition in MEI the time for unaccented grace notes is always stolen from the preceding note.  In essence, they're all _Nachschlagen_.  :-)

**Comment by pe-ro** [comment]
@craigsapp, I remember you talking about kerning somewhere, but could you run through what you mean by that term again please, esp. with respect to grace notes?

**Comment by craigsapp** [comment]
Here it is:

https://github.com/rism-ch/verovio/issues/255

**Comment by rettinghaus** [comment]
@pe-ro well, yes and no. Seen from timing they are sort of identical. But semantically unaccented grace notes *belog* to the following note, whereas a Nachschlag belongs to the preceding note. 
The visual difference is shown above by @craigsapp. Performance is indeed (mostly) identical. 

LilyPond follows the semantic path (for kerning) and assigns notes defined as `\grace` to the following note. To get the correct Nachschlag-rendering you have to use `\afterGrace`. 
(`\acciaccatura` and `\appoggiatura` is also available in LilyPond.)

NB: in #368 we came to the conclusion that unaccented grace notes usually are those with a slash.

**Comment by pe-ro** [comment]
I get the "belongs to" relationship, but should each note in the 2-note figure be associated with the principal note?  Or do both notes form a single Nachschlag that has that relationship?

**Comment by rettinghaus** [comment]
Both notes form a single Nachschlag. 
What would be the difference in encoding?

**Comment by craigsapp** [comment]
The Nachschlag would usually be a group of grace notes.  But probably not worth the effort to have an independent grouping element since it would most always be a beamed pair of grace notes, or to explicitly have a grouping mechanism to link it to the preceding real note, since the sequencing of data in the layer should be sufficient.

It would not be possible to have a Nachschlag after an accented or unaccented grace note, so they would all have to be adjacent to each other in any case, immediately following a real note, and they must occur before any "acc" or "unacc" grace notes which would be attached to the next real note. 

It could be treated as another label for `@grace` which could be applied to either a `note`, `chord`, or `beam`.  The label should contain `unacc` and then either have a dash or a space after which the Nachschlag qualifier would be given, such as `unacc-after`, `unacc-ns`, `unacc-post`, etc.

**Comment by pe-ro** [comment]
Values for `@grace` of "unacc" and "unacc-after" will work, but since they will apply only to the note itself, there should be a Schematron rule that says if one grace under a beam is marked as "unacc-after", then all the notes under that beam must carry the same value.

The only way around this (admittedly) somewhat clunky solution is to create a grace note grouping mechanism more specific than `<beam>`.  `<grupetto>` perhaps?

**Comment by craigsapp** [comment]
All grace notes within a beam must be the same type; otherwise, they would/should not be beamed together.  So it may be best to put the `@grace` on the beam, and ignore or mark as an error any `@grace` on individual notes within the beam.

Here is an example of a Nachschlage group followed by and unaccented grace note:

<img width="810" alt="screen shot 2017-02-22 at 13 28 36" src="https://cloud.githubusercontent.com/assets/3487289/23233168/d9b1865a-f902-11e6-9d09-a39538415992.png">

The following two measures show how it might be split across a measure boundary.

One advantage of marking as a Nachschlage is that the second Nachshalge in m2 looks correct, while the one in the first measure does not since there is no space after the trill note. I.e., the Nachschlage marking on the grace notes could ensure at least a small gap to the previous note to indicate the duration of the real note.

**Comment by craigsapp** [comment]
Would these grace notes be categorized as Nachschlage?

<img width="462" alt="screen shot 2017-02-22 at 13 45 38" src="https://cloud.githubusercontent.com/assets/3487289/23233928/49ce222a-f905-11e6-886f-e89ed40a90e1.png">

(Chopin mazurka in C# minor, op. 30, no. 4)

And how should they be encoded, particularly in attaching the grace note beam to a regular note?

**Comment by pe-ro** [comment]
> So it may be best to put the @grace on the beam, and ignore or mark as an error any @grace on individual notes within the beam.

That's sort of what I'm suggesting with `<grupetto>`, which indicates that all its children are grace notes.

If `@grace` were added to `<beam>`, should it take the current values: "acc", "unacc", and "unknown"?

Chopin?  Chopin, really?  Damn, I'm learning to like Chopin less and less.  🤕 

According to your earlier statement --
> All grace notes within a beam must be the same type; otherwise, they would/should not be beamed together.

Mr. Chopin shouldn't beam the big notes and the little notes together.  But, nevertheless, he has.  I think he was just trying to mess us up.

Seriously, putting aside completely the fact that there are too many notes in the right hand, the best encoding strategy I can come up with off the top of my head is to assume there are 2 layers here (supported by the fact that the big notes have a down stem) and mark the small notes as simply being small, not grace notes.  Something like the following, although I've not been entirely accurate about which notes are in which layer --
```
<measure xmlns="http://www.music-encoding.org/ns/mei">
  <staff>
    <layer>
      <beam>
        <note dur="8" stem.dir="up"/>
        <chord dur="8" stem.dir="up" fontsize="small"/>
        <note dur="8" stem.dir="up" fontsize="small"/>
        <chord dur="8" stem.dir="up" fontsize="small"/>
      </beam>
      <note dur="8" stem.dir="down" fontsize="normal"/>
      <rest dur="8"/>
      <rest dur="8"/>
      <chord dur="8" stem.dir="down">
        <note/>
        <note/>
      </chord>
    </layer>
    <layer>
      <note dur="4"/>
    </layer>
  </staff>
  <staff>
    <layer>
      <note dur="4"/>
      <chord dur="8">
        <note/>
        <note/>
        <note/>
      </chord>
      <rest dur="8"/>
      <rest dur="4"/>
    </layer>
  </staff>
</measure>
```

**Comment by pe-ro** [comment]
Incidentally, at least one of the first notes in the right hand should be marked using `@sameas` to make sure the note head only gets rendered once.

**Comment by craigsapp** [comment]
> Chopin? Chopin, really? Damn, I'm learning to like Chopin less and less.

Just wait until I eventually get to nocturnes:

<img width="769" alt="screen shot 2017-02-22 at 14 27 49" src="https://cloud.githubusercontent.com/assets/3487289/23235654/315bbd0a-f90b-11e6-979f-b814990acd33.png">

<img width="780" alt="screen shot 2017-02-22 at 14 31 20" src="https://cloud.githubusercontent.com/assets/3487289/23235776/992b32a8-f90b-11e6-890d-0cc6434e57a7.png">

Here is a single-note Nachschlage:

<img width="436" alt="screen shot 2017-02-22 at 14 33 40" src="https://cloud.githubusercontent.com/assets/3487289/23235868/edd9a4f6-f90b-11e6-9b76-005bb69cc18c.png">

Arpeggiation grace notes (maybe to indicate a slow arpeggio):

<img width="766" alt="screen shot 2017-02-22 at 14 37 44" src="https://cloud.githubusercontent.com/assets/3487289/23236018/822d2c86-f90c-11e6-9d39-32eb480c49e1.png">

**Comment by rettinghaus** [comment]
A Nachschlag normally ends an ornament. So definitely no Nachschlag for
Chopin! I wouldn't call them grace notes at all, but more like  "flitting
notes". Or just simply "small notes".
As a Nachschlag is basically part of an ornament, one could encode those as
children of trill or mordent, but that would be somewhat ugly.


Am 22.02.2017 11:19 nachm. schrieb "pe-ro" <notifications@github.com>:

**Comment by craigsapp** [comment]
> Incidentally, at least one of the first notes in the right hand should be marked using @sameas to make sure the note head only gets rendered once.

That will be useful to keep in mind.  When verovio does layer collision avoidance, I can submit a bug report to have it respect `@sameas` markers (currently all shared notes in layers are done in `@sameas` style).

**Comment by craigsapp** [comment]
> Seriously, putting aside completely the fact that there are too many notes in the right hand, the best encoding strategy I can come up with off the top of my head is to assume there are 2 layers here (supported by the fact that the big notes have a down stem) and mark the small notes as simply being small, not grace notes. Something like the following, although I've not been entirely accurate about which notes are in which layer --

Encoding as "small notes" in a second layer should be acceptable, with the assumption that they all have the same (tuplet) duration without showing a tuplet number, and having only a single beam line.

A tricky aspect is that the shared note between the layers has an accidental.  In this sort of case (small notes sharing a notehead with a regular note), any accidental before the note should be displayed in regular size.

**Comment by pe-ro** [comment]
@rettinghaus, over in #406 I called these "quasi-improvisational" notes.  

In @craigsapp's last 2 examples (m. 1 of "Here is a single-note Nachschlage" and m. 2 of "Arpeggiation grace notes -maybe to indicate a slow arpeggio"), there is a trill preceding the grace notes. I know the term normally applies to earlier music, but I'd say that Chopin was "extending" the meaning of "Nachschlag".   We probably don't want to encourage encoders to label them that way, but I don't think we can keep anyone from doing it.

> A tricky aspect is that the shared note between the layers has an accidental. In this sort of case (small notes sharing a notehead with a regular note), any accidental before the note should be displayed in regular size.

Big notes are always throwing their weight around. 😀

**Comment by pe-ro** [comment]
> That will be useful to keep in mind. When verovio does layer collision avoidance, I can submit a bug report to have it respect @sameas markers (currently all shared notes in layers are done in @sameas style).

The opposite approach, however, is just as good.  That is, treat all notes shared by the layers as the same note head and require an offset of some kind to move one note (very rarely both notes) when necessary.  I'd say Verovio should accommodate both approaches.

**Comment by craigsapp** [comment]
Here is an example of typesetting the first Chopin sample from above in SCORE:

<img width="462" alt="screen shot 2017-02-22 at 13 45 38" src="https://cloud.githubusercontent.com/assets/3487289/23233928/49ce222a-f905-11e6-886f-e89ed40a90e1.png">

<img width="825" alt="screen shot 2017-02-22 at 18 28 55" src="https://cloud.githubusercontent.com/assets/3487289/23242305/ea3f4a14-f92c-11e6-9430-a41fc7edd85d.png">

[chopin-mazurka-30-4.txt](https://github.com/music-encoding/music-encoding/files/795404/chopin-mazurka-30-4.txt)


I was able to encode the small notes as grace notes, so not too unusual for SCORE :-).  The only complication is that SCORE wants to left-justify the overlapped regular/grace notes, so I had to give the grace notes a horizontal offset to simulate right-justification on the shared notehead.

**Comment by lpugin** [comment]
> I was able to encode the small notes as grace notes, so not too unusual for SCORE :-). The only complication is that SCORE wants to left-justify the overlapped regular/grace notes, so I had to give the grace notes a horizontal offset to simulate right-justification on the shared notehead.

Yes, this is the hack we could try to avoid. I agree with Perry that we could encode them as a second layer with small notes. However, the additional issue here is that the duration should be adjusted, either with `@dur` / `@dur.ges` or with a `tuplet`, which is certainly possible and fairly easy.

Alternatively, we could try to think of a way to say that the first grace note has to be on the time stamp of the previous note. Something like:

```xml
<staff>
    <layer>
        <note dur="4" stem.dir="down"/>
        <beam>
            <note dur="8" stem.dir="up" grace="acc" tstamp="1.0"/>
            <chord dur="8" stem.dir="up" grace="acc"/>
            <chord dur="8" stem.dir="up" grace="acc"/>
            <chord dur="8" stem.dir="up" grace="acc"/>
        </beam>
        <note dur="8" stem.dir="down"/>
        <rest dur="8"/>
        <rest dur="8"/>
        <chord dur="8" stem.dir="down">
            <note/>
            <note/>
        </chord>
    </layer>
</staff>
```

If I understand correctly, the use of `@sameas` would give something like:

```xml
<staff>
    <layer>
        <note dur="4" stem.dir="down" xml:id="n1"/>
        <beam>
            <note sameas="#n1" stem.dir="up" grace="acc"/>
            <chord dur="8" stem.dir="up" grace="acc"/>
            <chord dur="8" stem.dir="up" grace="acc"/>
            <chord dur="8" stem.dir="up" grace="acc"/>
        </beam>
        <note dur="8" stem.dir="down"/>
        <rest dur="8"/>
        <rest dur="8"/>
        <chord dur="8" stem.dir="down">
            <note/>
            <note/>
        </chord>
    </layer>
</staff>

**Comment by craigsapp** [comment]
> Alternatively, we could try to think of a way to say that the first grace note has to be on the time stamp of the previous note. Something like...

That is an interesting possibility, and is close to how I did it in SCORE.  SCORE uses horizontal position in a manner similar to `@tstamp` in MEI.  If two notes on a staff have the same horizontal position, they also have the same tstamp in score (with a separate parameter allowing for an additional horizontal offset if they are not visually supposed to be at the same horizontal position, such as chords containing seconds).

**Comment by craigsapp** [comment]
Here is the 2nd layer method of encoding the Chopin example in SCORE:

<img width="878" alt="screen shot 2017-02-22 at 23 08 06" src="https://cloud.githubusercontent.com/assets/3487289/23248363/dc4bacaa-f953-11e6-899e-2a3efd2664fb.png">

[chop2.txt](https://github.com/music-encoding/music-encoding/files/795747/chop2.txt)


It is OK, but I notice a minor problem: the grace notes are spaced as sixteenth notes in the first group, and as 32nds in the second group, so the spacing in the two groups are different.  There would be greater problems if there were other notes in bottom staff occurring in the same beat (they would be falsely aligned with grace notes, possibly making the spacing inside the grace note group uneven).

Compare to the gracenote encoding (notice that the first grace note group is more compact):

<img width="825" alt="screen shot 2017-02-22 at 18 28 55" src="https://cloud.githubusercontent.com/assets/3487289/23242305/ea3f4a14-f92c-11e6-9430-a41fc7edd85d.png">

**Comment by pe-ro** [comment]
> Alternatively, we could try to think of a way to say that the first grace note has to be on the time stamp of the previous note.

That looks suspiciously like `<backup/>` to me.  😀  But I'm not opposed to the approach as long as `@sameas` is treated consistently; that is, saying something is "the same as" something else gives it the same time stamp, and as long as encoding as multiple layers also still works.

**Comment by lpugin** [comment]
Why did you put `@tstamp` on note then ;-) ?

**Comment by craigsapp** [comment]
SCORE input is done in a similar manner to `<layer>`, with only one layer being added at a time (and no backup).  In SCORE I cannot add all notes in one pass for this example (as grace notes or as small notes).  For the grace-note encoding method, I added all notes to a single layer except for the shared A4 grace notes, and then I added the A4s graphically (equal to assigning a tstamp or sameas to them).  

Backup would be good to avoid, but this is a quasi backup, so not quite a backup.  More of a freezing of the timeline, functioning similar to a chord/chordSpan.  I think `@sameas` is a good method: using `@tstamp` implies that you can use any timestamp value (making it a true backup/forward). `@sameas` has a similar problem, but feels more restricted

**Comment by pe-ro** [comment]
More as a confirmation of its time location, i.e., so it wouldn't have to be calculated any time you wanted to know when the note occurs.  It only occurred to me later that an event could be "time shifted" by altering the value of `@tstamp`, so it still feels a little kludgey.  Encoding the events in a measure backwards, recording the last note first, then penultimate note, and so on, and then using `@tstamp` to put them in chronological order is permissible, but it just feels a little weird.

In any case, because `@tstamp` is available I don't think we can disallow such behavior.  We just need to make sure it's used responsibly.

**Comment by pe-ro** [comment]
No comments on my `<grupetto>` suggestion?  I think this would be an easy way to distinguish beamed grace notes from others.  Then any special needs for grupetto, such as kerning, discussed in https://github.com/rism-ch/verovio/issues/255, and marking the group as a Nachschlag, could be met by adding appropriate attributes.  I think it's time to split `<beam>` into `<beam>` for regular notes and `<grupetto>` for grace notes.

**Comment by craigsapp** [comment]
I don't have a problem with that.  So a current `beam` containing grace notes would become a `grupetto`?  An advantage as you mention is being able to mark the function of grace notes at the grupetto level rather than the note/chord level.

Gruppetto might be the preferred spelling: https://en.wiktionary.org/wiki/gruppetto

A potential problem is that you are somewhat redefining gruppetto from the musical sense.  A Gruppetto is a group of notes which form an ornament, rather than a sequence of grace notes that are beamed together.  These two functions mostly coincide, but not exactly.

**Comment by pe-ro** [comment]
> So a current beam containing grace notes would become a `grupetto`?

Exactly.

> you are somewhat redefining gruppetto from the musical sense.

I'm not married to the name.  Got other suggestions?

**Comment by craigsapp** [comment]
`gbeam` might be good if it has the exact meaning of a beamed set of grace notes. `beam` would still be used for "small notes" and "cue notes", of course, which posses non-zero score durations.

**Comment by pe-ro** [comment]
Or `beamgr`?

**Comment by craigsapp** [comment]
No problem with `beamgr`, but `gbeam` is easier to say.

**Comment by pe-ro** [comment]
BEAM-grr, kinda like Beemer with a guh. :-)

**Comment by craigsapp** [comment]
😈

**Comment by rettinghaus** [comment]
Why `beamgr`? For me it totally looks like `graceGrp`!

**Comment by pe-ro** [comment]
Good call.  In that case, there doesn't necessarily have to be a rendered beam.

**Comment by craigsapp** [comment]
> Good call. In that case, there doesn't necessarily have to be a rendered beam.

Yes, the main thing is if the grouping is tied to a beaming of the contained notes or not.   In most cases they would be beamed, so allowing them to not be beamed would add mostly unnecessary verbosity: (`<graceGrp><beam>...</beam></graceGrp>`).  In other words `graceGrp` interacts interacts with `beam` in the same way that `tuplet` does.

Here are two examples to think about (wether they are to be grouped without beaming).   The first is an unbeamed gruppetto, and the second are a sequence of grace notes which all do not share a single beam (but these are probably two separate groups anyway):

<img width="712" alt="screen shot 2017-02-23 at 11 38 32" src="https://cloud.githubusercontent.com/assets/3487289/23275783/b149c80c-f9bc-11e6-9ac4-36bababd1a29.png">

If the grace note grouping element is supposed to mean that all notes in the group are to be beamed together, then something with "beam" in the element name would be best; otherwise using "group" in the name would be better.

**Comment by pe-ro** [comment]
Here's a possible approach to `<graceGrp>` --
```
<classSpec ident="att.graceGrp.anl" module="MEI.cmn" type="atts" mode="add">
  <desc>Analytical domain attributes.</desc>
  <classes>
    <memberOf key="att.common.anl"/>
  </classes>
</classSpec>
<classSpec ident="att.graceGrp.ges" module="MEI.cmn" type="atts" mode="add">
  <desc>Gestural domain attributes.</desc>
  <classes>
    <memberOf key="att.graced"/>
  </classes>
</classSpec>
<classSpec ident="att.graceGrp.log" module="MEI.cmn" type="atts" mode="add">
  <desc>Logical domain attributes.</desc>
  <classes>
    <memberOf key="att.event"/>
    <memberOf key="att.beamedWith"/>
  </classes>
  <attList>
    <attDef ident="attach" usage="opt">
      <desc>Records whether the grace note group is attached to the preceding or following
        event. The usual name for the former is "Nachschlag".</desc>
      <valList type="closed">
        <valItem ident="pre">
          <desc>Attached to the preceding event.</desc>
        </valItem>
        <valItem ident="post">
          <desc>Attached to the following event.</desc>
        </valItem>
      </valList>
    </attDef>
  </attList>
</classSpec>
<classSpec ident="att.graceGrp.vis" module="MEI.cmn" type="atts" mode="add">
  <desc>Visual domain attributes.</desc>
  <classes>
    <memberOf key="att.color"/>
    <memberOf key="att.beamRend"/>
  </classes>
  <attList>
    <attDef ident="beam" usage="opt">
      <desc>Indicates if the group is beamed.</desc>
      <datatype>
        <rng:ref name="data.BOOLEAN"/>
      </datatype>
    </attDef>
    <attDef ident="beam.slash" usage="opt">
      <desc>Indicates if the beam carries a diagonal slash.</desc>
      <datatype>
        <rng:ref name="data.BOOLEAN"/>
      </datatype>
    </attDef>
  </attList>
</classSpec>
<elementSpec ident="graceGrp" module="MEI.cmn" mode="add">
  <desc>A container for a sequence of grace notes.</desc>
  <classes>
    <memberOf key="att.common"/>
    <memberOf key="att.facsimile"/>
    <memberOf key="att.graceGrp.log"/>
    <memberOf key="att.graceGrp.vis"/>
    <memberOf key="att.graceGrp.ges"/>
    <memberOf key="att.graceGrp.anl"/>
    <memberOf key="model.eventLike.cmn"/>
  </classes>
  <content>
    <rng:zeroOrMore>
      <rng:choice>
        <rng:ref name="model.eventLike"/>
        <rng:ref name="model.appLike"/>
        <rng:ref name="model.editLike"/>
        <rng:ref name="model.transcriptionLike"/>
      </rng:choice>
    </rng:zeroOrMore>
  </content>
  <constraintSpec ident="When_not_copyof_graceGrp_content" scheme="isoschematron">
    <constraint>
      <sch:rule context="mei:graceGrp[not(@copyof)]">
        <sch:assert
          test="count(descendant::*[local-name()='note' or local-name()='rest' or
          local-name()='chord' or local-name()='space']) &gt; 1"
          >A graceGrp without a copyof attribute must have at least 2 note, rest, chord, or
          space descendants.</sch:assert>
      </sch:rule>
    </constraint>
  </constraintSpec>
  <constraintSpec ident="When_graced" scheme="isoschematron">
    <constraint>
      <sch:rule context="mei:graceGrp[@grace]">
        <sch:assert test="not(descendant::mei:*[@grace])">The grace attribute is not allowed
          on descendants of a graceGrp with a grace attribute.</sch:assert>
      </sch:rule>
    </constraint>
  </constraintSpec>
</elementSpec>
```
This will validate
```
<graceGrp beam="true" grace="unacc" attach="pre" label="Nachschlag">
  <note/>
  <note/>
</graceGrp>
```
The `<note>` descendants of `<graceGrp>` are prevented from having `@grace` themselves by the Schematron provided.  Like `<beam>`, `<graceGrp>` must also have at least 2 event children.

This change doesn't prevent the following, currently-allowed markup --
```
<beam label="beamedGraceNotes">
  <note grace="unacc"/>
  <note grace="unacc"/>
</beam>
```
Schematron could be added, however, to disallow a beam with only grace note children.  Of course, that will break compatibility.  I don't see that as a huge problem, though, since the upgrade XSLT can turn all of these into `<graceGrp>` elements.

Since `<graceGrp>` is a member of model.eventLike.cmn, it can occur anywhere other notes, chords, rests, beams, etc. can occur.  In other words, anywhere where `<beam>` can currently happen.

Thoughts?

**Comment by craigsapp** [comment]
That looks good.  Are beams allowed inside of `graceGrp`?:

```
<graceGrp grace="unacc" attach="pre" label="Nachschlag">
  <note/>
  <beam>
      <note/>
      <note/>
  </beam>
</graceGrp>
```

In other words is `graceGrp` for an arbitrary sequence of grace notes with the same function or more of a replacement for a beamed sequence of grace notes?

**Comment by pe-ro** [comment]
>  Are beams allowed inside of `graceGrp`?

Yes, that's possible, but 
```
<graceGrp grace="unacc" attach="pre" label="Nachschlag" beam="false">
  <note/>
  <graceGrp beam="true">
    <note/>
    <note/>
  </graceGrp>
</graceGrp>
```
is an alternative as long as `@beam` is available.

One might also see other configurations, such as --
```
<graceGrp grace="unacc" attach="pre" label="Nachschlag" beam="true">
  <note/>
  <note/>
</graceGrp>
<note grace="unacc" label="non-Nachschlag"/>
```
depending on the "Nachschlag-iness" of the preceding/following note(s).

Also, at present a `<graceGrp>` containing nothing but a `<beam>` is allowed --
```
<graceGrp grace="unacc" attach="pre" label="Nachschlag">
  <beam>
    <note/>
    <beam>
      <note/>
      <note/>
    </beam>
  </beam>
</graceGrp>
```

The question of whether to treat the beam as a first-class object (i.e., using `<beam>` instead of `@beam`) raises many difficult questions, just as it does with `<tuplet>`.  In fact, it makes me doubt whether `<graceGrp>` is a good idea after all. 🙁

**Comment by craigsapp** [comment]
`graceGrp@beam` versus `graceGrp/beam` would behave similar to `note@accid` and `note/accid`.  When no special attributes are needed for the beaming of the grace notes, then `graceGrp@accid` can be used.  For unusual cases with beam attributes, `graceGrp/beam` can be used.

**Comment by rettinghaus** [comment]
I like it. 
What if you really can't tell if it's "attached" to the previous or following note? Just don't set the attribute? Or would it be wiser to have `@attach="unknown"` (analogous to `@grace`)?

**Comment by lpugin** [comment]
> The question of whether to treat the beam as a first-class object (i.e., using `<beam>` instead of `@beam`) raises many difficult questions, just as it does with `<tuplet>`. In fact, it makes me doubt whether `<graceGrp>` is a good idea after all.

I think `graceGrp` is a good idea, but I would not add a `@beam` to is. That is I would expect this:
```xml
<graceGrp grace="unacc" attach="pre" label="Nachschlag">
    <beam>
        <note/>
        <chord>
            <note/>
            <note/>
        </chord>
    </beam>
</graceGrp>
```

I know that we should not model the encoding for facilitating processing, but when the processing becomes cumbersome maybe this means that there is something not so great with the encoding... For example, if I have this:

```xml
  <beam>
    <tuplet>
        <note grace="unacc">
            <accid/>
            <artic/>
        </note>
        <chord grace="unacc">
            <artic/>
            <note>
                <accid/>
            </note>
            <note/>
        </chord
    </tuplet>
  </beam>
```

There is an awful lot to query around to know for example is the `<artic>` or the `<accid>` is part of a grace group. Plus this is quite error prone because we can easily have a missing `@grace`

**Comment by pe-ro** [comment]
OK, no `grace/@beam`. Beaming will have to be done with `graceGrp/beam`.  However, I've added `beam/@slash` for those cases (usually associated with grace notes, but not always) where there's a diagonal slash through the beam (not the note stems).  For example,
```
<graceGrp grace="unacc" attach="post" grace.time="10%">
  <beam slash="true">
    <note dur="16"/>
    <note dur="16"/>
    <note dur="16"/>
  </beam>
</graceGrp>
<note dur="2" dots="1"/>
```
![image](https://cloud.githubusercontent.com/assets/5712877/24118288/a1f95d9c-0d83-11e7-9fbc-a0b25a7fe932.png)

Also, as @rettinghaus has requested, `@attach` can have the value `unknown`.

Next questions:
- Should `<graceGrp>` be allowed to nest?
- Since they might contain redundant or contradictory info, should `@grace`, `@grace.time`, and perhaps even `@stem.mod` be disallowed (via Schematron) on note descendants of `<graceGrp>`?

**Comment by pe-ro** [comment]
I have a bit of uneasiness about adding `<graceGrp>`.  I just don't feel it's quite "ripe" enough yet.  Any objections to tabling it for now?

**Comment by craigsapp** [comment]
I don't have a problem with that.

**Comment by lpugin** [comment]
I like it and I think it fills an important gap. But we can wait if you think we need to.

**Comment by pe-ro** [comment]
@lpugin: Actually, you've provided the vote of confidence I was looking for, so I'll put it in. 😀 

But, should it be removed for MEI Basic?
