### ISSUE TITLE
data.KEYSIGTOKEN regex is incorrect

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#432]
The regular expression for `key.sig` currently requires a leading letter to validate. The regex is:

`[a-g][0-9](s|f|ss|x|ff|xs|sx|ts|tf|n|nf|ns|su|sd|fu|fd|nu|nd|1qf|3qf|1qs|3qs)`

which means that key signatures need to have the form 'a1s'.

**Comment by pe-ro** [comment]
This is intentional.  The goal is to separate the abstract concept of key and the key signature actually found in the document.  The info that was in `key.sig` in earlier versions of MEI is now expected to be in `key.fifths`.  `key.fifths` expresses the key in terms of the circle of fifths, while `key.sig` can be used to record the physical appearance of the "key".

For example, the key of the piece might be B flat, but the key signature displays only one flat --
```
<scoreDef 
  key.fifths="2f" key.sig="b4f" 
  meter.count="4" meter.unit="4" meter.sym="common" 
  ...
```

**Comment by ahankinson** [comment]
I'm not sure what `b4f` is supposed to represent, nor what a `key.sig` value of `g53qf` (which is a valid value) would represent.
