### ISSUE TITLE
Cue size

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#433]
In the current develop version, the `@size` (for indicating cue) attribute was merged into `@fontsize`. Since cue is not necessary bind to a font, wouldn't it make sense to instead replace `@size` with `@cue="true|false"`?

**Comment by pe-ro** [comment]
This is related to #406.

**Comment by lpugin** [comment]
Sorry, I forgot about it. I do not want to raise a full discussion again, but I am not convinced that `@fontsize` is the right attribute for indicating cues.

**Comment by rettinghaus** [comment]
I agree with @lpugin. With `@fontsize` alone there is no possibility for having `large` cue notes (Which is *not* the same as trying to have large small notes).

**Comment by pe-ro** [comment]
As @donbyrd said over in #406, "cue" always implies small notes, but I can see the need for possibly separating "small-ness" from "cue-ness".  I'll add a `cue` attribute and remove "cue" from the values allowed by `@fontsize`.  Good enough?

**Comment by lpugin** [comment]
Fine with me, thanks.

**Comment by pe-ro** [comment]
Fixed by 277b94ee077630d1c418a8dbec37ef9b666cecf4.

**Comment by donbyrd** [comment]
I realize this issue is closed, but @pe-ro's reference to my comment in #406 really seems to imply that I don't see the need for possibly separating "small-ness" from "cue-ness", and I'd like to clarify things. For the record, I see the need for _absolutely_ separating "small-ness" from "cue-ness". My comment in #406 did say that cue notes are always small, but it went on to say that the reverse is _not_ true, and the following discussion included several examples from me illustrating that point :-) . In other words, I'm glad @pe-ro made the change he described :-) . (Sorry, Perry, I don't mean to give you a hard time; I'm just extremely sensitive, perhaps overly so, to accuracy regarding the characteristics of music notation.)

**Comment by pe-ro** [comment]
Hi @donbyrd,

I didn't mean to imply that _you_ didn't recognize the separation, but that _I_ might not have clearly understood the consequences of not implementing it properly.  😀 

Aside:  it pays not to be overly sensitive when it comes to music notation.

**Comment by donbyrd** [comment]
Sorry, Perry. Actually, I was pretty sure you didn't mean to imply that; I was overly sensitive when it came to music notation.
