### ISSUE TITLE
Deprecate key.sig

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#434]
`@key.sig` has been moved to `@key`, and the idea of `@key.sig` in 4.0.0 was to represent the number of accidentals, the line they are on, and the type; so `b3f` would be a B flat on the 3 staff line.

After discussion with @pe-ro we decided that it would be more appropriate to deprecate `@key.sig` and use `<keySig>` for any advanced key signature definitions.

**Comment by lpugin** [comment]
I agree that using `<keySig>` or advanced key signature definitions is a good approach. However, I am not sure I understand why `@key.sig` needs to be changed or deprecated. Did we have an issue / discussion about it? I cannot find it.

**Comment by ahankinson** [comment]
As per the conversation with Perry, the semantics of current `@key.sig` mixes visuals (`1f` = 1 flat) with visuals (it is assumed that this means the key signature has a b-flat). However, it may not be the case that a key signature with one flat is a b-flat; it could be an e-flat (for non-standard scores). 

Thus `@key.sig` is changed to `@key` to represent the position on the circle-of-fifths (`1f`), with the idea that `@key.sig` would then try to represent the specific pitch accidentals on the specific lines. (It's still not clear to me how it does this, but if we're deprecating `@key.sig` it doesn't really matter.)

**Comment by ahankinson** [comment]
I also couldn't find a discussion about it. It would be handy to link it here if there was one, even if it was a side-effect of another change.

**Comment by pe-ro** [comment]
There wasn't any discussion, unless you count me talking to myself as I made the change. :-)

**Comment by lpugin** [comment]
It does count as a discussion, but maybe we should discuss it further ;-)

I don't this the current `@key.sig` mixes semantics and visuals at all. It only makes the assumption that flats and sharps follow the fifth circle. This is a fair assumption and a perfectly valid approach.

I am not sure I understand how the proposed approach works. @pe-ro : could you give some examples?

**Comment by pe-ro** [comment]
The "circle of fifths" approach doesn't take into account partial key signatures.  For example, we've all seen pieces where visually the key signature contains 1 flat, but E flats are indicated by accidentals (expressly written or implied) placing the real key of the piece in Bb, not F.  In other words, the _key signature_; that is, how many flats/sharps appear on the page, is different from the analyzed/perceived/_theoretical key_ of the piece, so two different methods of representation are necessary.

In MEI 4.0.0, `@key` makes use of the "circle of fifths" method, while `@key.sig` represents the visual key signature.  (Naming them this way makes `@key.sig` match `<keySig>`.)  Since `@key.sig` duplicates info that can also appear in `<keySig>`, it (`@key.sig`) can be deprecated.  Alternatively, and better in my opinion, it can be placed in the analytical module, where it can be switched off in MEI Basic, and switched on when a compact representation of the key signature is desired.  For example, one might want to use `@key.sig="b4f e5f"` instead of parsing out the children of `<keySig>`.  This is the same design pattern used by `@accid` and `<accid>`.

**Comment by lpugin** [comment]
> In MEI 4.0.0, `@key` makes use of the "circle of fifths" method, while `@key.sig` represents the visual key signature

I would say that in MEI 3.0, `@key.sig` also makes use of the "circle of fifths", but indeed for its visual appearance. For a partial signature we currently simply do
```xml
<staffDef key.pname="g" key.mode="minor" key.sig="1f"/>
```
That is, `@key.sig` represents the visual signature assuming a circle of fifths (well, with only one here, which makes it a bad example, sorry...).

> Since `@key.sig` duplicates info that can also appear in `<keySig>`, it (`@key.sig`) can be deprecated. 

I agree that technically it can. But why this one and not another (e.g., `@clef.line`/`@clef.shape`) ?

I did make the request of having `@sig` in `<keySig>` for aligning it with `@key.sig`  in https://github.com/music-encoding/music-encoding/issues/250
I think this is still useful. For example, you might one to use the key signature element just because you want to have a link to a facsimile. So the previous example would be:
```xml
<staffDef key.pname="g" key.mode="minor">
    <keySig sig="1f" facs="#facs-id"/>
</staffDef>
```
So having `@key.sig` and `@sig` as is seems to be quite useful and also significantly less error prone than to have the detailed content of a key signature to be given explicitly for any partial key signatures or when `<keySig>` is desired for an unrelated reason.

**Comment by ahankinson** [comment]
If I understand this correctly, @pe-ro, you're saying that if I'm encoding a piece of music with lots of Eb's, best practices would dictate `@key=2f` and `@key.sig=b4f`?

If so, at no point are we actually encoding the key _signature_ that is there on the page. We do need a way to express the fact that there is a key signature present, and it does in fact have 1 flat. That's a pretty standard convention in music notation, and this change seems to muddy the waters on how to effectively communicate a well-known convention. 

`@key` is not 1 flat; the "key" is F, the key _signature_ is 1 flat. The key may be perceptually Bb if there's lots of accidental Eb's, but that doesn't change the fact that the key signature is still just 1 flat. 

The form `@key.sig=1f` effectively communicates one flat in the key signature while still being vague enough about any perceived tonal centre in the music -- it could be F major, it could be d minor, it could be Bb major with all the Eb's written as accidentals, but (for whatever reason) the key signature is given as 1 flat. We can already express the fundamental pitch name and mode, so `@key.sig=1f @key.pname=B @key.accid="f" @key.mode=major` would be how I might suggest encoding your particular example. .pname, .accid, and .mode could certainly be moved to the analytical module since those are really only known with some sort of analysis, but .sig is a thing on a page.

**Comment by pe-ro** [comment]
> If I understand this correctly, @pe-ro, you're saying that if I'm encoding a piece of music with lots of Eb's, best practices would dictate `@key=2f` and `@key.sig=b4f`?

Yes.

> If so, at no point are we actually encoding the key signature that is there on the page.

Yes we are!  The key signature appearing on the page; that is, 1 flat on B4, is encoded by `key.sig="b4f"`.  The key is encoded using `key="2f"` -- two steps around the circle of 5ths to the left.  The tonal center is expressed using `pname="g" mode="minor"`.

**Comment by lpugin** [comment]
I am not convinced. First by the content of `@key`, namely `2f` that for me indicates a key signature and not a key. These are two different concepts. Also, all the parsing involved in reading `@key.sig` makes me think that this is not very XML-like. But the main problem for me is that by introducing the octave placement in the `@key.sig` values you enforce distinct `@key.sig` to be given depending on the clef and also on engraving practices. In other words, and if I understand correctly, you cannot do (staffGrp omitted deliberately) :
```xml
<scoreDef key.sig="1f">
    <staffDef clef.shape="G" clef.line="2"/>
    <staffDef clef.shape="F" clef.line="4"/>
</scoreDef>
```
But instead enforce to do
```xml
<scoreDef>
    <staffDef clef.shape="G" clef.line="2" key.sig="b4f"/>
    <staffDef clef.shape="F" clef.line="4" key.sig="b3f"/>
</scoreDef>
```
Or am I overlooking something? Sorry if I do.

**Comment by ahankinson** [comment]
Except that if you asked Joe Musician what the key was, they would probably answer "F" (or, with a further glance, "D minor"). The _key_ is not 1 flat.

**Comment by craigsapp** [comment]
> > If I understand this correctly, @pe-ro, you're saying that if I'm encoding a piece of music with lots of Eb's, best practices would dictate `@key=2f` and `@key.sig=b4f`?

> Yes.

Why is that @pe-ro?  A standard critical edition style would be to add an editorial accidental to the key signature.  Example case from the page:

http://wiki.ccarh.org/wiki/Performing_Corelli%27s_Op._5_violin_sonatas

<img width="668" alt="screen shot 2017-05-24 at 4 40 40 pm" src="https://cloud.githubusercontent.com/assets/3487289/26409253/5041facc-40a0-11e7-9599-200fff90dba7.png">

Saying that `@key=3s` and `@key.sig="f5s c5s"` is about the same thing, but involves a lot of calculation to figure out which accidentals should be editorial and have brackets placed around them.  What about using `<choice>` or a `<rdg>` for such situations? And how would this be parallel to mensuration signs versus modern time signatures (as well as old/new clefs)?  This this is basically an old key signature versus a new key signature.

Using `@key=2f` and `@key.sig=b4f` seems to imply `@key="2f"` is the "logical" key signature, and `@key.sig="b4f"` is the "visual key signature".  But in a modern edition, the "logical" key signature would be the visual key signature, with critical editions wanting to put a bracket around the added accidental in the key signature.

When switching between `@key` and `@key.sig` as a visual key signagure, the visual accidentals `note@accid` would be pretty complex to calculate properly.  I am presuming that `note@accid` would be in reference to `@key.sig` rather than `@key` when both are present?

**Comment by pe-ro** [comment]
Damn!  What a hornet's nest!  

I'll try to put it back like it was; that is, with `@key.sig` taking values from `mixed|0|([1-9]|1[0-2])[f|s]`.

**Comment by pe-ro** [comment]
Here's the ODD necessary to effect the change --
```
<classSpec ident="att.keySig.log" module="MEI.shared" type="atts" mode="replace">
  <desc>Logical domain attributes.</desc>
  <attList>
    <attDef ident="sig" usage="opt">
      <desc>Written key signature.</desc>
      <datatype maxOccurs="unbounded">
        <rng:ref name="data.KEYFIFTHS"/>
      </datatype>
    </attDef>
  </attList>
  <remarks>
    <p>Mixed key signatures, e.g. those consisting of a mixture of flats and sharps (Read,
      p. 143, ex. 9-39), and key signatures with unorthodox placement of the accidentals
      (Read, p. 141) can be encoded using the <gi scheme="MEI">keySig</gi> element.</p>
  </remarks>
</classSpec>
<classSpec ident="att.keySigDefault.log" module="MEI.shared" type="atts" mode="replace">
  <desc>Used by staffDef and scoreDef to provide default values for attributes in the
    logical domain that are related to key signatures.</desc>
  <attList>
    <attDef ident="key.sig" usage="opt">
      <desc>Written key signature.</desc>
      <datatype maxOccurs="unbounded">
        <rng:ref name="data.KEYFIFTHS"/>
      </datatype>
    </attDef>
  </attList>
  <remarks>
    <p>Mixed key signatures, e.g. those consisting of a mixture of flats and sharps (Read,
      p. 143, ex. 9-39), and key signatures with unorthodox placement of the accidentals
      (Read, p. 141) can be encoded using the <gi scheme="MEI">keySig</gi> element.</p>
  </remarks>
</classSpec>
```
I'm leaving in data.KEYFIFTHS as it makes clear what the values refer to.  `@key.sig.mixed` is still left out since it's function can be taken over by `<keySig>`.

Better?

**Comment by ahankinson** [comment]
That looks good to me. I think this will also remove the need for `data.KEYSIGTOKEN`, right?

**Comment by pe-ro** [comment]
Yep.  That's for catching that.
