### ISSUE TITLE
Use github wiki or github pages for the Guidelines?

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#448]
Discussion moved here from #440. 

A lot of things need to be added/revised in the Guidelines. Should we use the wiki here or github pages for the Guidelines. Is there a reason to prefer one over the other?

**Comment by pe-ro** [comment]
Benni said:

>I don't think a wiki is a good place for the guidelines, at least in the sense of controlled versioning and tying the guidelines to a specific schema version. Although it might be in the sense of "contribution ease".
>
>I don't know enough about the mechanisms of GitHub pages though…
>
>Although this might ease contribution, I think we have to maintain the guidelines with the schema and publish a PDF version.

This is primarily a way to facilitate contributions.  But, I hope it would help with on-going maintenance too.  Also, I'm holding onto the hope that the markdown version can be machine-transformed into TEI (Lite or Tite?) for validation and publication on the web and as a PDF.

This change would also provide an opportunity to reorganize and rewrite the Guidelines in a more-accessible style.

**Comment by ahankinson** [comment]
For what it's worth, GitHub wiki pages can be 'cloned' and committed to, like any other git repo. This would be very useful for a bulk upload of the existing guidelines.

It may be a big problem, though, that the guidelines would no longer be in TEI. Once we put it in markdown and get people editing it, we probably won't be able to easily put it back into TEI. Personally, I'm OK with that, but others may not be.

**Comment by ahankinson** [comment]
Also -- documentation versioning would be tricky. How do you show the guidelines for v3.0 once 4.0 has been released? And how do you maintain the links in the prose of the guidelines with the element definitions?

**Comment by pe-ro** [comment]
I'm not exactly certain of the process or the terminology, but since GitHub wiki pages can be treated like another repo, I assume that any given state of the guidelines could be marked/tagged as "released". The guidelines for v 3.0 would be available via its own, unique URL, as would 4.0.  In addition, once the markdown is converted to TEI, that file could also be part of a release, couldn't it?

What I'm imagining is the same process we have in place now -- the TEI text documentation and schemaSpec, filtered through a stylesheet (TEI now, but perhaps something else later), become an HTML document (for web browsing and generation of the PDF) -- but with the addition of a markdown "front-end".  That is, the markdown files (one for each section/chunk/page of the documentation) are transformed into the textual part of the Guidelines.  Additional hand or mechanical editing might be necessary at this stage, but I hope it would be minimal.  The biggest problem, as you point out, is the creation and maintenance of links between "pages".  But there's a mechanism for that in markdown, which could be transmogrified into TEI, couldn't it?

If we're not able to access older versions of the Guidelines from within GitHub itself, then we could at least maintain the generated HTML and PDF versions on music-encoding.

Maybe it's a pipe dream ...

**Comment by ahankinson** [comment]
Sure. But let's say someone comes along and does a cleanup of the guidelines on the wiki -- after all, that's what a wiki is for, so that we can allow more people to edit and contribute.

So it's not just a one-way street. We'll need to then be able to back-convert the markdown pages to TEI if we want to keep the TEI versions of the guidelines.

**Comment by pe-ro** [comment]
`Markdown -> TEI -> HTML -> PDF` is still a one-way street, isn't it, no matter when or how many times you traverse it?

Perhaps a silly question -- where are the markdown-encoded wiki pages actually stored?

Another question, can we trigger the `Markdown -> TEI` process on commit of the wiki page?  If so, then we can always keep the TEI pages/files in sync with the wiki.  

The major issue, of course, is assembling the collection of TEI files (via external parsed entities or XInclude) into one big TEI document.  But, if there's an index page in the wiki that contains only pointers to the pages with actual content, then that page can be used as a "driver" in which the pointers are replaced by the content of the referenced files, right?

**Comment by craigsapp** [comment]
The system I am using for VHV documentation is fairly easy for general user editing of content:
    http://doc.verovio.humdrum.org

Here is a page mostly edited by someone else after I set it up:
     http://doc.verovio.humdrum.org/filters/dissonant
which I think is being edited via the Github online editor.

Notice that on this page and most other pages in the VHV documentation, there is an edit button at the bottom of the page:

<img width="317" alt="screen shot 2017-07-19 at 7 39 46 am" src="https://user-images.githubusercontent.com/3487289/28352233-7bd26d30-6c55-11e7-8dce-dd6814415b75.png">

Clicking on the button takes you to the page where the markdown file is located on Github, and then you can press the edit button to edit online:
     https://github.com/humdrum-tools/vhv-documentation/edit/gh-pages/filters/dissonant/index.md

<img width="1116" alt="screen shot 2017-07-19 at 7 42 21 am" src="https://user-images.githubusercontent.com/3487289/28352293-d2c3bed2-6c55-11e7-89ca-5ab4cf3545f6.png">

To edit, a person has to have a Github account.  People outside of the repository can submit a change for review; otherwise, changes can be saved and the page is rebuilt on Github pages within 10 minutes (typically less than a minute).

The VHV documentation is based on this Jekyll template:
     http://idratherbewriting.com/documentation-theme-jekyll

This template has a search feature built into it:
     http://idratherbewriting.com/documentation-theme-jekyll/mydoc_search_configuration.html

And a method of converting the website into a PDF:
    http://idratherbewriting.com/documentation-theme-jekyll/mydoc_generating_pdfs.html
although I have not be interested in this, so no PDFs of VHV documentation.

Another useful feature to note is that the dissonant tool documentation:
          http://doc.verovio.humdrum.org/filters/dissonant
displays notation generated from verovio automatically in the browser when the page is loaded.  For example this music notation:

<img width="336" alt="screen shot 2017-07-19 at 7 51 07 am" src="https://user-images.githubusercontent.com/3487289/28352497-0cb603a6-6c57-11e7-9dc0-1b302170c761.png">

Is generated by the text:

```html
{% include verovio.html
	humdrum-visible="false"
	source="passing"
	scale="50"
	pageWidth="1000"
	tabsize="10"
%}
<script type="application/x-humdrum" id="passing">
**kern	**kern
*M2/4	*M2/4
4C	8cL
.	8dJ
4AA	4e
=2	=2
4FF	8fL
.	8eJ
4GG	4d
=	=
*-	*-
!!!filter: dissonant
</script>
```

"verovio.html" is a liquid template file:
    https://github.com/humdrum-tools/vhv-documentation/blob/gh-pages/_includes/verovio.html
which takes the above text and transforms it into an SVG image with verovio.

**Comment by ahankinson** [comment]
"Markdown -> TEI" will be a pretty fraught process, since it will involve "upconverting" (introducing semantic tags into what is, essentially, a markup language). It's better to skip TEI altogether: `Markdown -> PDF` [for example](https://github.com/alanshaw/markdown-pdf). Markdown -> HTML is the most standard use, so there is no problem there.

I see TEI as being the biggest barrier to entry for contributing to the guidelines. Moving it to Markdown will almost certainly help remove that barrier.

**Comment by bwbohl** [comment]
but how will a markdown data entry process be integrated into the schema generation? Aren't there dependencies of the schema to the documentation?

**Comment by pe-ro** [comment]
> Aren't there dependencies of the schema to the documentation?

The RNG schema and the Elements, Attributes, Model Classes, and Data Types pages are generated from the `<schemaSpec>` portion of the full TEI file.  There are no dependencies between the `<schemaSpec>` and the prose portions of the Guidelines.

So, we can separate the generation of the schema from that of the prose.  Schema generation could be handled using the TEI stylesheets and the prose could all be in markdown.

**Comment by ahankinson** [comment]
There are auto-generated links between the guidelines and the spec, though. It would need to be tested whether we could control those links or if they're done automagically in the documentation generation process.

**Comment by kepper** [comment]
At this point, we have links going from the guidelines to the spec only, but not the other direction – something we should take care of anyway.

Since I wrote the current transformations for both HTML and PDF outputs for the guidelines (including specs), I think I know them quite a bit. Since it's possible to convert markdown to angle brackets, it should be fairly straightforward to adjust the existing pipeline to support markdown input. After all, it's just another level of abstraction ;-)

**Comment by bwbohl** [comment]
> At this point, we have links going from the guidelines to the spec only, but not the other direction – something we should take care of anyway.

mentioned in in #394 and created separate issue #450

> Since it's possible to convert markdown to angle brackets, it should be fairly straightforward to adjust the existing pipeline to support markdown input.

Would that also allow editing the TEI or would we then have the markdown as single entry point?

**Comment by ahankinson** [comment]
We have created a new repo, music-encoding/guidelines, a Jekyll site that will host the new guidelines.  We will be deprecating the old ODD-based guidelines. It's currently in a state of conversion, and help is definitely appreciated. 

I will close this issue, but feel free to comment.
