### ISSUE TITLE
@type and @label

### ISSUE THREAD

**Issue by JanetteSeuffert** [music-encoding/music-encoding#479]
We would wish a more precise description of the attributes `@type` and `@label` in the guidelines, to differentiate exactly between these attributes `@type` and `@label` (also in regard for interchange) and their use.

`@type` used as attribute for precising an element, as an example:

	 `<title type=„main“>Der Freischütz</title>`

 `@label` used as (not only for lists) mark / a element and their content

 	`<identifier type="siglum" label="A">A</identifier>`

**Comment by bwbohl** [comment]
Comparing `mei:title/@type` to the more general availability of `@type` on arbitrary elements shows that there already is a (?semi-)closed list of values for the former. This does make sense as in a specific context a specific list of potential values is desirable. Nevertheless, foreseeing such values for any element is impossible. Actually one could argue that it lies within the responsibility of the encoder / project to define and assure the use of their closed list for other spots, e.g. via a schema customisation or additional schematron validation.
With the current developments of MEI in mind, and speaking on a more general interchange level I would even question the use of `mei:title/@type`for this purpose. Actually I think the new `@class` attribute could be considered more appropriate.

As I consider `@label` to be subject to even more individual factors I would not use it for any kind of describing the parent element more closely.

**Comment by pe-ro** [comment]
I somewhat agree with @bwbohl since `@label` is not intended to be a **_description_** of the element it's attached to, but a **_name_**.  It's most common use will be as a tool tip.

`@type`, on the other hand, contains an _ad hoc_ classification (that is, a narrower or broader term), while `@class` holds a pointer into a formal taxonomy.  The former can be any token that you like, the latter however requires a corresponding end point, either within a `<taxonomy>` in the current document or at the given URI.

The use of `title/@type` as a bibliographic classifier is a hold over from TEI.  I suggest that we not change that in order to make it easier to exchange data between TEI and MEI.  Providing these values in a semi-open/closed list doesn't mean that `@type` can't take any other value one might like since it is multi-valued.
```
<title type="main beloved too_hot_to_handle">
```
is just fine.

**Comment by pe-ro** [comment]
Having heard to further request, I'm closing this for now.
