### ISSUE TITLE
Contribution guidelines don't consider ideas or bug reports without proposed implementation

### ISSUE THREAD

**Issue by donbyrd** [music-encoding/music-encoding#487]
The New Issues page

  https://github.com/music-encoding/music-encoding/issues/new

says "If you have a bug or an idea, read the contributing guidelines before opening an issue". But those Guidelines

  https://github.com/music-encoding/music-encoding/blob/develop/CONTRIBUTING.md
  
assume you're going to be contributing code, while a large number of the current issues (including this one) are just statements of ideas or descriptions of bug with no related code. It seems like the Contribution Guidelines should discuss that type of contribution.

**Comment by ahankinson** [comment]
What would you like them to say?

GitHub automatically links any file named "CONTRIBUTING" to the new Issues page, so that message you see is automatically created. If you have an opinion of what this should say, you can modify the 'CONTRIBUTING' file. You can do this from GitHub without needing to pull or anything:

1. Click on CONTRIBUTING (make sure you're in the develop branch)
1. Click the edit button
1. Make the changes
1. Write a little message saying what you've changed in the bit below
1. Click 'Propose file change' (I think that's what the button is called)

GitHub will automatically open a new Pull Request for us. 

For now, I'm going to close this issue. If you have a concrete suggestion for wording in the contribution guidelines, please submit that via a pull request.

**Comment by donbyrd** [comment]
Thanks for the details, Andrew! I just submitted a pull request.  --Don


On Nov 30, 2017, at 4:29 AM, Andrew Hankinson <notifications@github.com> wrote:

> What would you like them to say?
> 
> GitHub automatically links any file named "CONTRIBUTING" to the new Issues page, so that message you see is automatically created. If you have an opinion of what this should say, you can modify the 'CONTRIBUTING' file. You can do this from GitHub without needing to pull or anything:
> 
> 	• Click on CONTRIBUTING (make sure you're in the develop branch)
> 	• Click the edit button
> 	• Make the changes
> 	• Write a little message saying what you've changed in the bit below
> 	• Click 'Propose file change' (I think that's what the button is called)
> GitHub will automatically open a new Pull Request for us.
> 
> For now, I'm going to close this issue. If you have a concrete suggestion for wording in the contribution guidelines, please submit that via a pull request.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---
Donald Byrd
Woodrow Wilson Indiana Teaching Fellow
Adjunct Associate Professor of Informatics
Visiting Scientist, Research Technologies
Indiana University Bloomington
