### ISSUE TITLE
text directions with duration

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#494]
How should `<dir>` type elements be encoded when they possess a duration?  For example:

<img width="821" alt="screen shot 2018-01-31 at 10 14 35 am" src="https://user-images.githubusercontent.com/3487289/35639715-f4d9d2e0-066f-11e8-9af1-0675d3e76760.png">

The `diminuendo` and  `ritardando` both have a duration of three measures.  

Presumably by using `@tstamp="0"` for the start of the first measure, and `@tstamp2="2m+12"`, or equivalently with `@startid` and `@endid`, or perhaps also with `@startid` and `@tstamp2`.

A more complex example would be how to encode the word breaks, such as "dimi-nu-en-do" and "ritar-dan-do".  In this particular case it looks like each syllable should be given a `@tstamp`, particularly when dealing with the coordinated display of the syllables in the two words (but one is split into groups, and the other is split into 3).  But in general, such stretched `<dir>`s should be evenly spaced.  An example of this would be "cresc. poco a poco" where the four words of the dir group would be "cresc." "poco" "a" "poco", and they should be spaced evenly (spatially, not temporally) in the score over the specified duration...

Somewhat related, how should the cresc and dashed line after it be encoded in this example:

<img width="1019" alt="screen shot 2018-01-31 at 10 15 18 am" src="https://user-images.githubusercontent.com/3487289/35640111-14043a74-0671-11e8-9a3f-1f6ce5de9105.png">

Should the "cresc." and line be a single `<dir>` entity, or should even the `<dir>` be the entire text `p cresc._ f`
with a `@tstamp` for each component of the dir group?

If the `cresc._` were replaced with a hairpin crescendo mark, how would the markup change?.  This is like the "pp < ff" in the first example above.

There was talk last year or so about horizontal grouping of dir elements, or dynamic markings in specific.  Has that been formalized into MEI yet?  If so, then I can start making feature requests in the verovio repository :-)

**Comment by pe-ro** [comment]
I'd encode the first example like so --
```
<dynam tstamp="1">p</dynam>
<dynam tstamp="1" tstamp2="2m+12">diminuendo</dynam>
<dynam tstamp="1" tstamp2="2m+12">ritardando</dynam>
<dynam tstamp="1">p</dynam>
```
where the 1st three `<dynam>` elements are in m. 3 and the last one is in m. 6.

Each of the "components" are encoded separately to provide the greatest amount of control over their start times.

There's no method yet for specifying exactly how the continuous dynamics (diminuendo and ritardando) should be stretched to fit the time allotted to them or how they should be divided by syllable.  One way to do this would be to use "-" as a mark of division --
```
<dynam tstamp="1" tstamp2="2m+12">dimi-nu-en-do</dynam>
```
the expectation being that the rendering software would space the "syllables" evenly and supply a reasonable number of dashes between them.

Another approach would be to use `<syl>` to mark the individual syllables --
```
<dynam tstamp="1" tstamp2="2m+12">
  <syl con="d">dimi</syl>
  <syl con="d">nu</syl>
  <syl con="d">en</syl>
  <syl con="d">do</syl>
</dynam>
```
which would provide greater control over the syllable connectors and an element to which additional attributes, such `@tstamp`, could be attached.  The problem with using `@tstamp`, however, is determining the proper value; that is, since the syllable "nu" occurs in m. 4, should its `@tstamp` value be relative to that measure (tstamp="1") or to the start of the dynamic marking (tstamp="1m+1")?  In my opinion, this complexity can be avoided if we provide the renderer with basic info and let it place the individual syllables where it wants.  Their locations in the original source can be indicated using `@facs`.

Another way to do the same thing is to use `<seg>`, which is already available within `<dynam>` --
```
<dynam tstamp="1" tstamp2="2m+12">
  <seg>dimi</seg>
  <seg>nu</seg>
  <seg>en</seg>
  <seg>do</seg>
</dynam>
```
However, we lose the capability of indicating the connectors between segments, unless we add `@con`.  I think this is the better way to go -- it doesn't "overload" the use of `<syl>` for lyric syllables and for syllables elsewhere.

The 2nd example can be encoded --
```
<dynam tstamp="1" vgrp="1">p</dynam>
<dir tstamp="1" tstamp2="4m+1" extender="true" lform="dashed" vgrp="1">cres.</dir>
<dynam tstamp="1" vgrp="1">f</dynam>
```
I've substituted `<dir>` for the crescendo marking since `<dynam>` doesn't currently allow `@extender` or `@lform`, but these should be added to `<dynam>`, I think.  

Again, the individual components are marked separately but vertically grouped via their shared value for `@vgrp`.  Elements that share a `@vgrp` value should be rendered at the same vertical height, what ever the renderer determines that to be.  The extender following "cres." is described by `@extender` and `@lform`.  The details of the rendering, avoiding the collision between "p" and "cres." on beat 1 of the first measure and how many dashes to use to fill the space between the end of the "cres." and the "f", are left open.

We could add another attribute, say `@dashes` or `@lsegs`, etc., that could be used to provide an exact number or a range of dashes to draw.  For example, if `@dashes` has a single value, exactly that number of dashes should be drawn.  If it has 2 values, the renderer is free to choose a number of dashes within the range between the provided values (including the end points of the range, of course).

**Comment by bwbohl** [comment]
see also #495

**Comment by ndubo** [comment]
We currently encode these cases of split `dynam` and `dir` with `dynam` for the single syllable and connect the `dynam` with `@next` and `@prev` (a `@plist` would do a similar job). 
for the dashes between the syllables , I would suggest allowing `@con="d"` directly in `dynam`. 
If dynamics are spilt, a sort of semantic representation of the full dynamic expression is required, in other words, a declaration telling that the `<dynam>do</dynam>` - meaningless in and by itself - is part of a  full 'crescendo' (some sort of gestural dynamic? `dynam.ges="crescendo"`?). 
Perhaps using the `syl` would do the job, but it looks uncomfortable. 
Of course, any solution working for `dynam `should also be available for `dir` as well and vice versa.

**Comment by pe-ro** [comment]
Waiting for comments ............

**Comment by pe-ro** [comment]
`<dynam>` is a member of the `att.extender` class in MEI v. 4 which, along with `@vgrp`, answers this question.  Closing now ...
