### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by axgeertinger** [music-encoding/music-encoding#503]
At http://music-encoding.org/support/guidelines and the other documentation pages such as http://music-encoding.org/documentation/3.0.0/chapters , the “Elements” link (http://music-encoding.org/documentation/3.0.0/elements) is dead.

**Comment by craigsapp** [comment]
What do you mean? When I look at this link: http://music-encoding.org/documentation/3.0.0/elements

I see this page:

<img width="1340" alt="screen shot 2018-03-06 at 6 48 54 am" src="https://user-images.githubusercontent.com/3487289/37038599-12db1c22-210a-11e8-8777-8d8ac4080978.png">

**Comment by axgeertinger** [comment]
That's peculiar. I get this:
![404](https://user-images.githubusercontent.com/3779074/37039403-afdf2890-2157-11e8-88d0-d58280cb15c0.png)

**Comment by craigsapp** [comment]
It must be the Danish censors...

**Comment by lpugin** [comment]
The link works for me too. Maybe you can try a "shift + reload" ?

**Comment by axgeertinger** [comment]
OK. I tested the link in various environments. Here are the results:

Desktop PC at home:
Firefox 43.0.4:      OK
MSIE 11:              OK
Chrome 64.0.xxx: OK

Desktop PC at office:
Firefox 52.0.1:       404
MSIE 11:               404
Chrome 64.0.xxx:  404

Laptop on WiFi at home or at work (location makes no difference):
Firefox 56.0.1:      404
MSIE 11:              OK
Chrome 64.0.xxx: OK

It doesn't seem to be a cache thing since I haven't used most of these combinations before.  Only the 'Elements' link seems to be affected. But if I am the only one experiencing this problem, it's probably not worth investigating further. But it seems to have started recently when the pages were slightly redesigned.

**Comment by lpugin** [comment]
It looks on the screenshot that the page requested is `http://music-encoding.org/documentation/3.0.0/elements/` (with a slash at the end) instead of `http://music-encoding.org/documentation/3.0.0/elements`. I wonder how this can be different.

**Comment by craigsapp** [comment]
Yes, I was just noticing that.   It seems to be a problem with the slash at the end of the address.

This works for me:
   http://music-encoding.org/documentation/3.0.0/elements

This does not work for me:
   http://music-encoding.org/documentation/3.0.0/elements/

The actual URL is:
   http://music-encoding.org/documentation/3.0.0/elements.html

Github is making an alias from `elements.html` to `elements` (or it is setup this way somehow in the configuration file for the website).

To fix the problem, the contents should be moved to:

   http://music-encoding.org/documentation/3.0.0/elements/index.html

This should allow these three URLs to work:

   http://music-encoding.org/documentation/3.0.0/elements
   http://music-encoding.org/documentation/3.0.0/elements/
   http://music-encoding.org/documentation/3.0.0/elements/index.html

To fix the problem, a permalink in the Jekyll header should be added placing the page in `/documentation/3.0.0/elements/index.html` in this Markdown file:

https://raw.githubusercontent.com/music-encoding/music-encoding.github.io/master/documentation/3.0.0/elements.md

See: https://jekyllrb.com/docs/permalinks

Or the contents of `elements.md` should be moved from `/documentation/3.0.0/elements.md` to `documentation/3.0.0/elements/index.md`, which would be the easiest thing to do  since there is no need to add the permalink to the Jekyll header in this case.

Alternatively all links to the elements page should be changed to:
   http://music-encoding.org/documentation/3.0.0/elements.html

**Comment by craigsapp** [comment]
(And this is probably true for other pages as well, where it might be best to force the contents to `/index.html` allowing for slashes to be optional rather than having `.html` be optional.)

**Comment by axgeertinger** [comment]
I notice that Firefox (at least sometimes, it appears) adds the slash if I omit it and therefore fails. I did use the URL without the trailing slash: I just followed the link.
Strangely, http://music-encoding.org/documentation/3.0.0/atts has the same faulty behaviour on my laptop (Firefox adds a slash and fails) but not on my office PC, while http://music-encoding.org/documentation/3.0.0/models works on both my laptop and office PC (no slash added).

**Comment by lpugin** [comment]
This should not be fixed because the links have `.html`. See http://music-encoding.org/guidelines/v3/elements.html

**Comment by craigsapp** [comment]
One possibility is to use redirections:

https://github.com/jekyll/jekyll/issues/3368
http://www.marran.com/tech/creating-redirects-with-jekyll
https://github.com/jekyll/jekyll-redirect-from

**Comment by craigsapp** [comment]
> This should not be fixed because the links have .html. See http://music-encoding.org/guidelines/v3/elements.html

Note that this URL also works:

http://music-encoding.org/guidelines/v3/elements

With some sort of automatic redirect to

http://music-encoding.org/guidelines/v3/elements.html

So additionally an alias could be made to:

http://music-encoding.org/guidelines/v3/elements/

Since that typically the mapping in most webservers for a URL like

http://music-encoding.org/guidelines/v3/elements

(hence the original confusion)
