### ISSUE TITLE
make neume part of att.placement

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#511]
When using `<neume>` within `<syllable>` it would be good to say wether the neume is "above" or "below" the letters (even it doesn't really fit `data.STAFFREL`).

**Comment by pe-ro** [comment]
`<syl>` already allows place, so it's possible to provide this info, although from the opposite perspective; that is, the position of `<syl>` relative to the neumes --
```
<syllable>
  <syl place="above">O</syl>
  <neume class="#hn_t">
    <nc class="#hn_p" oriscus="unknown" quilisma="unknown"/>
    <nc class="#hn_p" con="g" intm="u"/>
  </neume>
  <neume intm="d"/>
</syllable>
```
This and `<neume place="below">` allow capture of relative placement on every `<syl>` or `<neume>`.  Perhaps, however, the problem is that it *requires* recording the placement on every `<syl>` or `<neume>`.  It might be useful to allow the place info to be on `<syllable>` instead, e.g.,
```
<syllable place="below">
  <syl>O</syl>
  <neume class="#hn_t">
    <nc class="#hn_p" oriscus="unknown" quilisma="unknown"/>
    <nc class="#hn_p" con="g" intm="u"/>
  </neume>
  <neume intm="d"/>
</syllable>
```
`@place` doesn't feel right as the attribute name, though.  Perhaps "nplace" or "neumes" is better?  "neumeplace" is most expressive, but also somewhat lengthy.

**Comment by pe-ro** [comment]
Also, encoding order could be significant.  For example, 
```
<syllable place="below">
  <neume class="#hn_t">
    <nc class="#hn_p" oriscus="unknown" quilisma="unknown"/>
    <nc class="#hn_p" con="g" intm="u"/>
  </neume>
  <neume intm="d"/>
  <syl>O</syl>
</syllable>
```
could be used to convey the relative positioning of the neumes and the text syllable.

**Comment by rettinghaus** [comment]
As we encode *music with text* in MEI and not *text with music* this approach makes sense.
