### ISSUE TITLE
Revise <verse> to allow the encoding of a display label

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#514]
Neither `@n` nor `@label` can be used on `<verse>` to encode a label, such as "1." that precedes the syllabic content of `<verse>`.   `@label` isn't acceptable for this because it's not supposed to be used for document content.

Adding `<label>` to the content of `<verse>` appears to be a workable solution --
```
<content>
  <rng:zeroOrMore>
    <rng:ref name="label"/>
  </rng:zeroOrMore>
  <rng:zeroOrMore>
    <rng:choice>
      <rng:ref name="dir"/>
      <rng:ref name="dynam"/>
      <rng:ref name="tempo"/>
      <rng:ref name="space"/>
    </rng:choice>
  </rng:zeroOrMore>
  <rng:oneOrMore>
    <rng:choice>
      <rng:ref name="volta"/>
      <rng:ref name="model.sylLike"/>
      <rng:ref name="model.appLike"/>
    </rng:choice>
  </rng:oneOrMore>
  <rng:zeroOrMore>
    <rng:ref name="model.lbLike"/>
  </rng:zeroOrMore>
</content>
```
When necessary, the `@source` attribute can be used to indicate the particular source(s) for each label.

Doing this will allow `@n` to continue to be used to indicate verses with a different order than encoding order.

**Comment by rettinghaus** [comment]
With `<label>` available, there should be `<labelAbbr>`, too. When having multiple verses, some publishers print the verse number repeatedly on every new system.

**Comment by pe-ro** [comment]
I don't think `<labelAbbr>` is necessary since each instance of the label can be marked using `<label>`.  But could you provide an example please for testing?  Thanks.

**Comment by craigsapp** [comment]
If `<labelAbbr>` will always be the same as `<label>`, then it would not be necessary to have different from `<label>`.  But if `<labelAbbr>` is not allowed, then the number-at-every-break style would have to be input externally in the graphical music rendering process, such as an option to verovio.  Allowing `<labelAbbr>` would function as a sort of option to display such numbers, in a similar manner as instrument abbreviations as implemented in verovio (if there is an abbreviation, then display it).  So in this case, if there is a `<labelAbbr>` then display it; otherwise, the default style of just numbers at the start of the lyrics would be displayed.

Here is a case that @rettinghaus described:

http://kern.humdrum.org/cgi-bin/ksdata?file=erk001.krn&l=users/craig/songs/erk/liederschatz/band1&format=pdf

<img width="1004" alt="screen shot 2018-04-21 at 9 38 20 am" src="https://user-images.githubusercontent.com/3487289/39086536-c0f98710-4547-11e8-8856-c05dca7f30e4.png">


There are also cases where the verse numbers change in the middle of a piece, which I would expect `<label>` implementations would be able to handle.

**Comment by rettinghaus** [comment]
Thanks @craigsapp, this is exactly what I meant. So `<labelAbbr>` is, like for `<staffDef>`, an instruction for repetition, as I argued before in #361:
> `<labelAbbr>` is fine, but I was wondering if not `<labelRpt>` would fit better into naming scheme. In the end it is a container for *repeating the label*. Could be less confusing if anybody asks why `<label>` goes over `<labelAbbr>` on the first line …

**Comment by pe-ro** [comment]
Sorry, I still don't get your point.  If you want to provide another label, repeated or not, use the `<label>` element at the appropriate place.  The `<label>` element simply divides the content of `<verse>` into a label and the syllables that follow --
```
<section>
  <measure>
    <staff>
      <layer>
        <note pname="f" oct="4" dur="8">
          <verse>
            <label>1.</label>
            <syl>A</syl>
          </verse>
          <verse>
            <label>2.</label>
            <syl>E</syl>
          </verse>
          <verse>
            <label>3.</label>
            <syl>I</syl>
          </verse>
        </note>
      </layer>
    </staff>
  </measure>
  <!-- intervening measures -->
  <measure>
    <staff>
      <layer>
        <note pname="g" oct="4" dur="8">
          <verse>
            <label>1.</label>
            <syl>klopft</syl>
          </verse>
          <verse>
            <label>2.</label>
            <syl>Hol</syl>
          </verse>
          <verse>
            <label>3.</label>
            <syl>mir</syl>
          </verse>
        </note>
      </layer>
    </staff>
  </measure>
</section>
```

**Comment by lpugin** [comment]
@pe-ro : with dynamic rendering you do not necessary know where the new system will occur. If I understand correctly the idea is to supplied the abbreviation `<labelAbbr>` at the same place where `<label>` is given and the understanding of it should be to use this abbreviation of the label for its repetition at the beginning of a system.

**Comment by rettinghaus** [comment]
@lpugin Yes, exactly. This was the idea.

**Comment by pe-ro** [comment]
Ok, now I understand.  You're expecting this --
```
<measure>
  <staff>
    <layer>
      <note pname="f" oct="4" dur="8">
        <verse>
          <label>verse 1:</label>
          <labelAbbr>1.</labelAbbr>
          <syl>A</syl>
        </verse>
        <verse>
          <label>verse 2:</label>
           <labelAbbr>2.</labelAbbr>
          <syl>E</syl>
        </verse>
        <verse>
          <label>verse 3:</label>
          <labelAbbr>3.</labelAbbr>
          <syl>I</syl>
        </verse>
      </note>
    </layer>
  </staff>
</measure>
```
when the verse numbering system changes.  And in the case where it doesn't change, `<labelAbbr>` wouldn't be present, right?  The idea is that the `<labelAbbr>` element would affect the verse numbering at the next system break, wherever/whenever that might happen, correct?

It's not likely to be a problem, but, of course, this markup could occur in any measure, not just the first, leading to more data than necessary.  Just calling attention to the possibility.

**Comment by rettinghaus** [comment]
@pe-ro It could and should occur in any measure. 
Many editors combined refrains in print, so that not only the label itself would change, but indeed the "repeated" label would, too (that is, if it should be repeated on system starts).  
![591b](https://user-images.githubusercontent.com/7693447/41555791-0e57d786-7339-11e8-957a-5bbff18de071.jpg)
