### ISSUE TITLE
meiHeader: key, clef, timeSignature in source

### ISSUE THREAD

**Issue by riedde** [music-encoding/music-encoding#545]
In the header elements like `<incip>`, `<key>`, `<clef>` and so on are only available in `<workDesc>/<work>`. Thinking about sketches or other sources where the work is unknown, it might be helpful to save that the `<sourceDesc>/<source>`-level as data. This would be also helpful for encoding sources that contain material of the same work in different transpositions.

**Comment by ahankinson** [comment]
[edit: code formatting for tags]

**Comment by ahankinson** [comment]
The work isn’t actually unknown — you would have it in front of you. That it is unnamed or unattributed doesn’t make it less of a work, in the bibliographic sense.

The distinction is that the source elements describe the source material, while the work elements describe the intellectual material. You can see this in the child elements of source: physical description, history, etc.

**Comment by riedde** [comment]
Understanding the element `<work>` as a place were musical details of a source can be encoded I would agree. Differentiating source material and intellectual material might be my problem, because in my opinion, there is some kind of transition. Source descriptions contain very often information about the key.
On searching the documentation I noticed that `<work>` appears at different places. `<workDesc>/<work>` is not the right place for that I like to encode. But I didn't know that `<source>` also can contain a `<work>`at `<componentGrp>` or `<componentList>`. This might the place I was searching for.

**Comment by kepper** [comment]
You should really turn on Schematron validation. With that turned on, work can only be used as component of a work. This is only allowed to benefit from the ODD class system, instead of having individual models for work, expression, manifestation (=source) and item. All this belongs to the FRBR model in MEI. I'd recommend that you read the corresponding chapter in the Guidelines , which should give a sufficient introduction to the concepts that Andrew referred to. This is not meant as a RTFM, but in a way, it seems easier to send you there than to restate everything said over there. Of course we're happy to continue our discussion then ;-)
