### ISSUE TITLE
<hand>

### ISSUE THREAD

**Issue by ghost** [music-encoding/music-encoding#549]
As discussed at the ESS Metadata Workshop it would be good to have a `<classification>` at `<hand>` to remark if the information is sure or not. At RISM there are the 4 levels: "sicher" "ermittelt" "mutmaßlich" and "fälschlich".

**Comment by ahankinson** [comment]
[Edit: Code formatting. When putting XML tags in an issue, they won't appear unless you put "backticks" (`) around them.]

**Comment by pe-ro** [comment]
@Irmlind, I don't think "fälschlich" (false) is particularly useful. It's better if editorial assertions are stated positively, e.g. , `<composer cert="high">Beethoven</composer>` because it's impossible to prove a negative statement.  If what the editor/cataloger wishes to say is that "once upon a time this was attributed to Beethoven, but now I know differently", then instead of   `<composer cert="false">Beethoven</composer>` use `<composer cert="high">Haydn</composer>`. The `@evidence` attribute can be used to provide a brief reason for the assertion, e.g., `<composer cert="high" evidence="Haydn-Beethoven_correspondence">Haydn</composer>`.

As for the other values, I think "sicher" ('sure', 'certain') equates to a high level of certainty and "mutmaßlich" ('presumed') means a low level of certainty.  I'm not sure about the translation of "ermittelt" (Google says 'determined'), but that sounds like somewhere in the middle to me, so I think this maps to a  value of 'medium'. Voila! We're back to the original values.

While I don't think we need values other than the ones we've already got, it does seem that `<hand>` should be a member of att.evidence.  That I will happily fix. :grinning:

**Comment by ghost** [comment]
Hallo Perry,

the terms for qualifying the decision „sicher“, „mutmaßlich“ und „fälschlich“ und „ermittelt" were mentioned by Roland Schmidt-Hensel and come from RISM therefore I have written it. But your proposal is good. Thank you! 

I wish you a god week
Best regards Irmlind

**Comment by pe-ro** [comment]
Fixed by 128e577a09a19ebbc05f466eca30c166785ec5b2
