### ISSUE TITLE
Dynamics, slurs etc. without measures.

### ISSUE THREAD

**Issue by jamesopstad** [music-encoding/music-encoding#573]
What is the correct way to add slurs, dynamics etc. when there is no measure element? It seems these need to be contained by a measure element but I am encoding music without measures, as stated here - https://music-encoding.org/guidelines/v3/content/mensural.html#mensuralData.

**Comment by craigsapp** [comment]
This is related to issue https://github.com/music-encoding/music-encoding/issues/559, where the problem is kicked down the road into the future :-)

The problem is that `@tstamp` is useless (or virtually useless and very fragile) in measureless encodings.  In those sorts of situations, you must instead use `@startid` and `@endid` to place floating elements into the music.  To do this, assign an `xml:id` to any notes that need something attached to them, and then use the startid for items that need one attachment point, or startid and endid for two attachment points (endid is analogous to tstamp2).

Example:

first some notes:

```xml
    <note xml:id="note-L5F1" dur="1" oct="4" pname="c" accid.ges="n" />
    <note xml:id="note-L6F1" dur="breve" oct="4" pname="d" accid.ges="n" />
    <note xml:id="note-L7F1" dur="1" oct="4" pname="f" accid.ges="n" />
    <note xml:id="note-L8F1" dur="breve" oct="4" pname="d" accid.ges="n" />                         
```

Then here is a slur attached to the 2nd and 3rd notes:

```xml
 <slur xml:id="slur-L6F1-L7F1" staff="1" startid="#note-L6F1" endid="#note-L7F1" />
```

This system is known to verovio, which renders the notes and slur like this:

<img width="317" alt="screen shot 2019-01-24 at 2 16 37 pm" src="https://user-images.githubusercontent.com/3487289/51702778-a7374d00-1fe2-11e9-91fa-417bfce6dff9.png">

`@tstamp` is also completely useless in mensural encodings since the durations of notes are not defined locally on the note (it is context dependent on the mensuration sign and the other notes surrounding it). 
`note@dur` on notes in mensural notation encodings is very different than for CMN `note@dur`.  `@dur` functions in the mensural case purely as a visual display of the note in mensural music, and the duration is interpreted based on the shape plus the values stored in `@num` and `@numbase`: https://music-encoding.org/guidelines/v4/content/mensural.html , so calculating `@tstamp` values by computer and/or manually would be a nightmare in mensural music.

**Comment by ahankinson** [comment]
The suggestion of doing `@startid`/`@endid` is a good one. The `<slur>` element can appear in `<layer>`, so it does not need to be in `<measure>`. 

See: https://music-encoding.org/guidelines/v3/elements/slur.html

A note, however, that `<slur>` does appear within the CMN module, so it is not really part of the Mensural symbol repertoire.

**Comment by jamesopstad** [comment]
@craigsapp I tried to recreate your example but when I render it with Verovio it logs:

`[Warning] Element 'slur' is unknown and will be ignored`

What am I doing wrong? Here is the full file.

```xml
<mei>
  <meiHead />
  <music>
    <body>
      <mdiv n="1">
        <score>
          <scoreDef>
            <staffGrp>
              <staffDef n="1" lines="5" />
            </staffGrp>
          </scoreDef>
          <section n="1">
            <staff n="1">
              <layer n="1">
                <note xml:id="note-L5F1" dur="1" oct="4" pname="c" accid.ges="n" />
                <note xml:id="note-L6F1" dur="breve" oct="4" pname="d" accid.ges="n" />
                <note xml:id="note-L7F1" dur="1" oct="4" pname="f" accid.ges="n" />
                <note xml:id="note-L8F1" dur="breve" oct="4" pname="d" accid.ges="n" />
                <slur xml:id="slur-L6F1-L7F1" staff="1" startid="#note-L6F1" endid="#note-L7F1" />
              </layer>
            </staff>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

**Comment by bwbohl** [comment]
as this is almost valid MEI except for the fileDesc missing in meiHead), have you tried filing an issue in the verovio GitHub repository (https://github.com/rism-ch/verovio)?

**Comment by lpugin** [comment]
Verovio does not support slurs in un-measured.

**Comment by bwbohl** [comment]
have to correct myself, it's almost valid MEI 3.0.0 ;-)

@lpugin th for clarifying
