### ISSUE TITLE
revise description of staff element

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#621]
We should rethink the description of what a *staff* may be, e.g. a staff could be a single line instead of a group, the lines don't have to be equidistant, the lines don't have to be horizontal etc. 
The current situation is not satisfactory.

> A group of equidistant horizontal lines on which notes are placed in order to represent pitch or a grouping element for individual 'strands' of notes, rests, etc. that may or may not actually be rendered on staff lines; that is, both diastematic and non-diastematic signs.

**Comment by craigsapp** [comment]
What sort of repertories would you plan on expanding to?   "equidistant horizontal" lines could be simplified to "parallel lines" or looser wording such as "parallel-like lines" for some of the examples below.  The main intention is horizontal staff lines as found in both chant, mensural, and cmn.  Would you want to encompass corruptions of the standard notation of these, or expand to non-western music?  Then you also start having to deal with different concepts of pitch, rhythm, etc.

In terms of not horizontal, are you thinking in terms of this:

<img width="543" alt="Screen Shot 2019-10-02 at 1 40 22 PM" src="https://user-images.githubusercontent.com/3487289/66080211-78328d00-e51a-11e9-9b4d-f8884ec393f1.png">
https://en.wikipedia.org/wiki/Ars_subtilior

There is a lot of modern notation that pushes notation to various limits.  Somewhat conservative would be George Crumb's music (Spiral Galaxy):

<img width="787" alt="Screen Shot 2019-10-02 at 1 47 40 PM" src="https://user-images.githubusercontent.com/3487289/66080519-14f52a80-e51b-11e9-89c4-6af9138443f1.png">

Both of these are traditional notation of staff music, but warped.  There are also graphical staff-like representations of music, and non-semantic artistic scores which do not a have a fixed meaning.


How does this relate to tablatures?   For a regular staff the pitch is defined by positions of marks (noteheads) relative to these lines.  For tablatures, the pitch is often the symbol itself rather than its relation to the typical staff lines. And I think tablatures encoded in MEI are using currently as a generic container, not necessarily expecting a direct mapping onto a staff for display of the notation.

There are also things like alternate representations of classical notation, such as klavarskribo, which is a hybrid between tablature and regular notation:

https://en.wikipedia.org/wiki/Klavarskribo

<img width="409" alt="Screen Shot 2019-10-02 at 1 52 20 PM" src="https://user-images.githubusercontent.com/3487289/66080832-b7ada900-e51b-11e9-828b-d7091ec98eec.png">

There are also staff lines for percussion instruments.  These lines do not indicate pitch but rather instruments.  And these "staff" lines often contain gaps in the equidistant spacing in order to group the instruments.

**Comment by rettinghaus** [comment]
> What sort of repertories would you plan on expanding to?

Whatever we decide. I was thinking about those "warped" examples, too. But my main point is that the current version somewhat tries to describe a standard 5-lines staff without saying so explicitly. Percussion staffs are not covered at all. So "one ore more parallel-like lines" would be a start.

**Comment by craigsapp** [comment]
> Percussion staffs are not covered at all.

Here is an example of a percussion staff where there are two lines, but the two lines are spaced as if there were a missing middle line between the two:

<img width="1480" alt="Screen Shot 2019-10-02 at 11 11 06 PM" src="https://user-images.githubusercontent.com/3487289/66103273-13068800-e56a-11e9-9062-d0af1b6431ad.png">

This sort of staff would be useful to be able to encode in MEI.  There is also a question about how to encode the positions on the lines: should the top staffline be `@loc="2"` or `@loc="4"`?  Probably `@loc="4"` is better since intermediate positions 1 through 3 might need to remain addressable in some repertories, ie:

<img width="497" alt="Screen Shot 2019-10-02 at 11 28 59 PM" src="https://user-images.githubusercontent.com/3487289/66104054-4d712480-e56c-11e9-9941-33f5b363fd61.png">

**Comment by ahankinson** [comment]
> that may or may not actually be rendered on staff lines

I think the description obscures this bit too much, but the point is still that the "lines" may or may not actually be visible. Staff lines are a method of relating pitch, higher or lower, from another and in this sense they are equidistant parallel lines. The 'horizontal' is also strange, given the real-world examples shown, but it is also tightly bound to the metaphor of using space to show progress through time on the horizontal plane. Even the complex notations above are read 'left to right' (horizontal) although visually they may be altered to not appear as such.

**Comment by kepper** [comment]
We think that this is sufficiently clear for now. That doesn't mean it can't or shouldn't be changed, but we don't see value in this ticket for now. Closing for now.
