### ISSUE TITLE
data.MODE is incomplete

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#627]
`data.MODE` is incomplete, e.g. all the plagal modes are missing. 
I would like to add them. 
Question is if all the Gregorian modes should go into `data.MODE.gregorian` as part of the mensural module. @music-encoding/mensural-ig

**Comment by craigsapp** [comment]
They should definitely be added, and I think that particularly for early mensural music, the Gregorian modes would be useful to include, since the mode of a polyphonic piece was often described by the mode of the tenor part. 

However, adding Gregorian modes to the current set might need some though to avoid confusion related to the historical definitions of modality.  The current MEI list of modes are the modern set that describe pitch-class content and the tonic (final) note.  Gregorian modes also consider the range: authentic mode having the final note at the bottom of the range, and plagal having the final in the middle of the range, as well as a reciting tone (which is usually the fifth above the final in the authentic modes, but not in the plagal modes).  Technically "dorian" in the current MEI description encompasses both "authentic" and "plagal" modes.  So it is not really that "plagal" is missing, but rather than both "authentic" and "plagal" are missing.  Over time, the difference between plagal and authentic are lost in polyphonic music, since it is difficult to hear the ranges of the separate voices.  And the plagal reciting tones gradually died out towards the shift to major/minor tonality (with the authentic reciting tone becoming the dominant scale degree in tonal music).

Therefore it might be useful to have three categories for each mode: the generic or modern form, such as "dorian", and the Gregorian modes "dorian.authentic" and "dorian.plagal".   Perhaps an abbreviation such as "dorian.auth" might be more convenient, with "dorian.plag" potentially matching it.

The current `data.MODE` values are the modern definition of mode:

<img width="353" alt="Screen Shot 2019-10-15 at 8 22 13 AM" src="https://user-images.githubusercontent.com/3487289/66845322-af466c80-ef24-11e9-8262-3d5365615ccc.png">

For example, `locrian` is a theoretical mode from the 18th century:
     https://en.wikipedia.org/wiki/Locrian_mode

The`ionian` mode is missing and also a proleptic mode (roughly equivalent to `major` mode):
    https://en.wikipedia.org/wiki/Ionian_mode

But there is both `minor` and `aeolian`, which have a similar relation as `major` does to `ionian`:
     https://en.wikipedia.org/wiki/Aeolian_mode

Gregorian modes are also called Church modes:
     https://en.wikipedia.org/wiki/Gregorian_mode
and plagal modes are also called "hypo-" modes (i.e., "dorian" is an authentic mode, and "hypodorian" is a plagal mode, both indicating the the range used (from the same link as above):

<img width="468" alt="Screen Shot 2019-10-15 at 8 32 06 AM" src="https://user-images.githubusercontent.com/3487289/66846123-27f9f880-ef26-11e9-987c-fa13adce7857.png">

And note that the gregorian modes can also be referred to by roman numerals: `I` means dorian, `II` means hypodorian (plagal dorain), etc.  Originally there were 10 modes in 5 pairs, and the last four in the chart are added later.

--------------

Related to this is the broader concept of mode to indicate other pitch-class groupings for scales (which the modern "mode" system has merged with).   A basic example would be the octatonic scale:
     https://en.wikipedia.org/wiki/Octatonic_scale

There are also the similar concepts of mode in non-CWMN music theories for Turkish, Indonesian, and Chinese and other musics.  It might be useful to think how to add infrastructure for adding the mode equivalents in these systems as well (in the future).

**Comment by ahankinson** [comment]
I know mode, like 'key,' gets more problematic the further back you go. 

We might consider removing the `data.MODE` datatype altogether and simply allow the `@mode` attributes to be a semi-closed list, so that there are a number of non-controversial choices but anyone wishing to add more can do so without causing a validation error.

**Comment by craigsapp** [comment]
> We might consider removing the data.MODE datatype altogether and simply allow the @mode attributes to be a semi-closed list, so that there are a number of non-controversial choices but anyone wishing to add more can do so without causing a validation error.

That sounds OK to me, although for analysis and automation purposes it would be good to have enforced forms.  Giving a preferred list should be sufficient, and if someone really wants to not use the list they could.  For example "major" could be called "maj.", "Major", "Maggiore", "Dur", "C major" etc., with the alternate names not adding anything useful and making automatic processing of the mode descriptor difficult across datasets.

The historical European modes can reasonably well be split into two groups: the Gregorian chant (Church) modes up to around 1600, and the modern modal viewpoint after 1700, treating mode as a pitch-class set for musical scales and a discarded vestige of tonal music (which starts being re-examined and extended by composers such as Debussy).

**Comment by DILewis** [comment]
I’m far from being knowledgable about this subject (which also kind of means that I know enough to be scared of it). I agree that, since it’s much more an analytical concept than, say, key is in the early C19, it makes sense to have a semi-closed list as Andrew suggests.

Another advantage of this approach is that it allows it to be used by Jazzers (and possibly for the analysis of some post-tonal classical compositions, too).

D

**Comment by rettinghaus** [comment]
Thank you all for the input. As @craigsapp mentioned a semi-closed list is always bad for parsing. Basically we always have (in every context) a strict list of values for "mode", and if you're not happy with the available ones, you should customize MEI to your needs (I think @kepper would agree). 
Thus said, I'm not against a semi-closed list per se.

In the above description the ["Tonus peregrinus"](https://en.wikipedia.org/wiki/Tonus_peregrinus) is missing. 
I propose `data.MODE.gregorian` to consist of the following values: 
```
dorian 
hypodorian 
phrygian 
hypophrygian 
lydian 
hypolydian 
mixolydian 
hypomixolydian 
peregrinus
```
These represent the eight "original" gregorian modes with the "unclassifiable" one. 
The later additions to the concept could go into `data.MODE.gregorian.extended`:
```
ionian
hypoionian 
aeolian 
hypoaeolian 
locrian 
hyopolocrian 
```
This would make customization easy and allows us to expand the values for different contexts/models, like the proposed `MEI.makam` model (see https://en.wikipedia.org/wiki/Turkish_makam).

**Comment by rettinghaus** [comment]
Additionally I wanted to point out, that some music code systems use modes for rendering key signatures, e.g. Lilypond uses `\key f \mixolydian` and ABC music `K:H phrygian`.

**Comment by ahankinson** [comment]
The change to a semi-closed list is actually as simple as changing:

`<valList type="closed">`

to

`<valList type="semi">`

Here: https://github.com/music-encoding/music-encoding/blob/develop/source/modules/MEI.xml#L2613

This can happen independently of the additional values, and, as @DILewis points out, could support additional modes like "[octatonic](https://en.wikipedia.org/wiki/Octatonic_scale)" or expanded ideas about the notion of scales.

I would feel better if we could get an early music person (particularly neumes) to have a look over the proposed list and give their thoughts. They would hopefully be apprised of the latest thinking behind the concept of mode and their names.

**Comment by DILewis** [comment]
> Additionally I wanted to point out, that some music code systems use modes for rendering key signatures, e.g. Lilypond uses \key f \mixolydian and ABC music K:H phrygian.
This is the sort of thing I worry about, though – from my position of partial knowledge, this looks like a hack. Lots of early music has a signature that is a step or two away from what this would suggest, and many pieces have different sigs in different parts without being in different modes. Arguably, this is true for key as well, and that’s why the signature is usually explicitly specified in an encoding.

**Comment by craigsapp** [comment]
> > e.g. Lilypond uses \key f \mixolydian and ABC music K:H phrygian.
> Lots of early music has a signature that is a step or two away from what this would suggest,

These are using the modern modal theory, so there is not any particular ambiguity (other than I didn't know ABC allowed German pitch names, which would make `K:B phrygian` difficult to interpret...).  In any case, MEI separates the key signature (visual domain) from the mode (analytic domain) in a manner similar to Humdrum.   This is important for the early key signatures as you mention, where an accidental is dropped from the key signature from a modern point of view.  For example B-flat major would usually be written with a single flat in the 17th century.  Example:

http://scores.ccarh.org/corelli/op5/corelli-op5n02.pdf

<img width="895" alt="Screen Shot 2019-10-16 at 8 30 19 AM" src="https://user-images.githubusercontent.com/3487289/66934205-00229780-efef-11e9-9063-1bc2e4203ed4.png">

Notice that the flats for the E's are written in the music rather than into the key signature.

**Comment by rettinghaus** [comment]
`MEI.dastgah` could be added for Persian music modes: https://en.wikipedia.org/wiki/Dastgah
Relates to #680
