### ISSUE TITLE
custos and sb 

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#629]
The guidelines say `sb` is 

> An empty formatting element that forces musical notation to begin on a new line.

Hence it may contain a `custos`. As costodes only appear at the end of lines, it does not make sense to put it in an empty (!) element, that starts (!) a new line.

**Comment by ahankinson** [comment]
To clarify: Are you saying that `sb` can currently contain custos, or that it should be able to contain it?

**Comment by rettinghaus** [comment]
`sb` currently can contain `custos`.

**Comment by davidrizo** [comment]
Hi all,

The title of the <sb> documentation page in "https://music-encoding.org/guidelines/v4/elements/sb.html” is (**system beginning**) – An empty formatting element that forces musical notation to begin on a new line. I agree with the fact of having an element that denotes the start of a system. Among other things It helps in the encoding of facsimiles.

If sb stands for "system beginning", maybe the custos should not be in this element but in a standalone one because it is located at the end of the previous staff.

However, it <sb> stands for system break it is ok, but it is difficult to denote the start of the system when linking to a facsimile.

Best regards

**Comment by rettinghaus** [comment]
`custos` is a normal layer element, and that should be sufficient. 
`barLine` also can end a system but it is not allowed within `sb`.

**Comment by rettinghaus** [comment]
Just noticed that `custos` may also appear in `tuplet`. Does that make any sense? As custodes have no duration itself.

**Comment by craigsapp** [comment]
A custos could theoretically be inserted within a tuplet group, provided that there is a system break within that group.  But this would typically be encoded as a `tupletSpan`, at least in measured music in the CMN module.   

In mensural music, the scribe will generally break the music at a breve boundary, but if they are probably not very musical or they run out of space they may break at an arbitrary location

**Comment by ahankinson** [comment]
I believe that 'round about MEI 2012 the definition of sb changed from "system break" to "system beginning". This was to bring it in line with TEI's "Line Beginning" element: https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-lb.html

So it's possible that `custos` as child is a hangover from that era. I agree that `custos` shouldn't be a child of `sb`, though.
