### ISSUE TITLE
Values for MIDI volume

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#638]
`@midi.volume` should conform to `data.MIDIVALUE_PERCENT`, but there is no such datatype.

**Comment by craigsapp** [comment]
Probably `data.MIDIVALUE_PERCENT` is a typo, and it should be `data.PERCENT`?

https://music-encoding.org/guidelines/v4/data-types/data.percent.html

Percent is a generic unit, so it is not specific to MIDI.

Also I do not see an attribute `@midi.volume` in the guidelines.  What elements can it be used on?  I theory it can exist since there is a master volume continuous controller in MIDI.  There is also `@midi.velocity` which is similar.

**Comment by rettinghaus** [comment]
I would have guessed it meant data.MIDIVALUE *or* data.PERCENT …

It’s used here 
https://music-encoding.org/guidelines/v4/elements/instrdef.html

**Comment by craigsapp** [comment]
> I would have guessed it meant `data.MIDIVALUE` *or* `data.PERCENT` …

Yes, that makes sense.
