### ISSUE TITLE
Plain chant encoding in mensural module

### ISSUE THREAD

**Issue by davidrizo** [music-encoding/music-encoding#645]
Is there any specific element to encode a a plain chant melody in mensural module or the space element must be used? 

In this example, I've composed how these voices should be approximately aligned, i.e., the altus (second voice) must start before the other voices until the bar line is found. In this case it happens at the beginning of the work, but it may be located in the middle of the piece:

![image](https://user-images.githubusercontent.com/10772049/73867269-ae747600-4846-11ea-9472-2849d067b011.png)

**Comment by bwbohl** [comment]
@martha-thomae could you please revise this issue?

**Comment by giulianodibacco** [comment]
@davidrizo It is not entirely clear to me if you are asking how to encode the correct alignment (how to record the time when the other parts are silent and the altus sings solo, without using rests if there are no rests) or how to encode the alternance between mensural and chant notation. Could you clarify?
 
BTW with my shortsightedness, I am almost seeing a ligature c-d and two diamonds, as if this would be not chant but mensural black. (In which case you could editorially add rests.) I am totally sure that I am not answering the question, but this case makes me feel that it would be useful 1) to extend the usage of `@notationtype` to units smaller than `staffDef` (am I being heretical?) and 2) to introduce a notationtype value for chant.

**Comment by pe-ro** [comment]
1. It would not be heretical to make `<section>` and `<ending>` and perhaps `<mdiv>` members of att.notationType.  This would permit capturing the notation type of time spans.
2. If it does turn out that the opening of @davidrizo's example is neume, not mensural notation, as @giulianodibacco suggests, why not use 'neumatic' as the value of `@notationtype` instead of adding 'chant'? "chant" is not a kind of notation, it's a musical/liturgical function.  That is, neume notation could've (and probably was at some point) used to write down secular songs, dances, etc., but the `@notationtype` doesn't allow "song", "dance", etc. because it's only concerned with the notation, not it's style/function/use.
3. As for alignment, wrap each kind of notation in its own `<section>`. In the 1st section, only staff 2 will have content.  Without content, the other staves are implicitly silent/tacet. In the 2nd section, all staves will have content.  If you do decide to mix neume and mensural notation, you'll need to validate against the **mei-all schema** or create a new customization that mixes these.

**Comment by giulianodibacco** [comment]
@pe-ro 1) I am glad to hear that. 2) Totally agreed about using "neumatic" as a value. (I was not suggesting "chant" as a value but to introduce 'a value for chant' (the repertoire using neumatic notation).)

**Comment by martha-thomae** [comment]
> 3. As for alignment, wrap each kind of notation in its own <section>. In the 1st section, only staff 2 will have content. Without content, the other staves are implicitly silent/tacet. In the 2nd section, all staves will have content. If you do decide to mix neume and mensural notation, you'll need to validate against the mei-all schema or create a new customization that mixes these.

This sounds like the right solution!
Thanks, @pe-ro!

Regarding **point 2**, there is already a `@notationtype` value for neumatic notation (the value is `neume`), so we can use that. We would only need to make the changes indicated in **point 1** (make `<section>` a member of att.notationType to be able to use `@notationtype` within this element—because right now it only works on `<staffDef>`)

**Comment by pe-ro** [comment]
@martha-thomae, you're correct -- the value is 'neume', not 'neumatic'.  Old, tired eyes.

**Comment by giulianodibacco** [comment]
@martha-thomae worth mentioning in ch.5 when you discuss notationtype?

**Comment by davidrizo** [comment]
@giulianodibacco I was asking all what you've discussed: the change of notation type and the alignment, and the key points have been discussed in your answers :)

Regarding the notation type let's better use an image that belongs to @martha-thomae (Martha, it's the document "1 ASPERGES ME", image 1v.jpg) -- see the segment until the bar line.

![image](https://user-images.githubusercontent.com/10772049/80131685-e1ebb480-859a-11ea-9837-ae4e0cee3627.png)

The notation is not black mensural, or neumatic (I've asked to our musicologist). It's just plain chant (canto llano in Spanish), that appears in white mensural notation since the 16th century. It can be used as incipit in the beginning of a work (usually sung by the priest - the "musical/liturgical function" that @pe-ro has mentioned), or alternating with polyphonic parts.

These notes have not a specific duration, or at least all of them have the same, they depend on the singer. Notice that it has not any meter / mensuration sign first despite being the first page. Notes in this kind of plain chant are usually notated as blackened _brevis_ to contrast it with white mensural _brevis_ that denote a measured duration. What seem to be _ligature_ are not actually _ligature_ in the mensural notation sense with different duration of their components depending on the shape,  just notes with the same duration that conform a melisma.

This example should be transcribed to modern notation as:
- all notes as whole notes - sometimes they are filled black


![image](https://user-images.githubusercontent.com/10772049/80196464-be1d8280-861d-11ea-9fac-07832bdb4e0e.png)

----
The example I added first in this issue is a little different. It seems to be (I've asked to be sure and I've not have the answer yet) measured because it has a cut time in the beginning and there are two types of black figures, _brevis_ and _semibrevis_.  Anyway it's the same case, a part that is sung as Gregorian that is answered by a polyphonic section.
![image](https://user-images.githubusercontent.com/10772049/80128991-c2eb2380-8596-11ea-84b3-068005c6b482.png)

---
Then:
* Point 2) The first example notation is not any of mensural or neumatic, it's a new one we don't have yet in notationType. Maybe it would be better just having it as `notationtype="mensural"` and `notationsubtype="plainchant"`. I suggest to encode them as they are written using `<note dur="brevis" colored="true" pname....>` and embedding in a `ligature` in case of being drawn as ligature. The system that finds the `notationsubtype="plainchant"` should known the rules to process correctly the durations.
* Point 1) As @martha-thomae suggests, it seems to be better to add the notationtype attribute to section. If we need to add a scoreDef / staffDef to each section, we would still have to link the different staffDef elements in each section. 
* Point 3) The @pe-ro approach seems to be enough: 
> " In the 1st section, only staff 2 will have content. Without content, the other staves are implicitly silent/tacet. In the 2nd section, all staves will have content. "

**Comment by lpugin** [comment]
@davidrizo `@notationsubtype` is an open attribute with no predefined values. It is of course absolutely fine to use it the way you want, and to have your system using it. However, this is not going to be a generic approach. 
Regarding the distinction between the visual aspect of the notation and its duration, I suggested a while ago to have a `@notationtype.ges` attribute for cases where there is a need to make a distinction between the two: https://github.com/music-encoding/music-encoding/issues/597
Maybe this is something that could be useful here too?

**Comment by davidrizo** [comment]
Regarding the example below, all notes, despite their notated figure, should be played with the same duration.
![](https://user-images.githubusercontent.com/10772049/80128991-c2eb2380-8596-11ea-84b3-068005c6b482.png)

It is explained in "El melopeo y maestro :tractado de musica theorica y pratica", by Pietro Cerone, 1613.
(It is [digitised](https://books.google.es/books?id=yfwobs9YNwMC&pg=PA415&lpg=PA415&dq=%22El+compás+verdadero+del+cantollano+es%22&source=bl&ots=1kv6p9zrxR&sig=ACfU3U1r3jxFf5nRvQULPSeSBX9CEDn5gg&hl=es&sa=X&ved=2ahUKEwjumpfC44DpAhWXAWMBHcyOBPEQ6AEwAHoECAQQAQ#v=onepage&q=%22El%20compás%20verdadero%20del%20cantollano%20es%22&f=false)) in several places.

![image](https://user-images.githubusercontent.com/10772049/80198362-43099b80-8620-11ea-8e32-323a7721625d.png)

The meaning is something like:
The right measure of _Cantollano_ (plainchant) is a whole, unbreakable and just one, and it has just one part, ...., all "points" are the same, it takes the same time to sing a squared point with two stems than other with just one,  to sing a ligature (punto alphado) than a semibreve (triangulado).

It seems that in some specific repertoires, such as hymns or credos, there may be some differentiation in the duration of notes.

@lpugin I agree with your proposal in #597. If I understand correctly, it would be notationtype.ges="plainchant". 
As @pe-ro mentioned above, the notationtype should not denote the use. Then, I would use notationtype="mensural", notationtype.ges="plainchant", however I don't known how this differentiation in the case of being  a hymns or credos should be done.

**Comment by martha-thomae** [comment]
Hi @davidrizo 

> The notation is not black mensural, or neumatic (I've asked to our musicologist). It's just plain chant (canto llano in Spanish), that appears in white mensural notation since the 16th century. It can be used as incipit in the beginning of a work (usually sung by the priest - the "musical/liturgical function" that @pe-ro has mentioned), or alternating with polyphonic parts.

Yes, this is plainchant. And all that you say is correct regarding that it appears as the incipit or alternating with polyphonic sections. But, as far as I know, **plainchant is notated in neumatic notation**. And all what you say later is in agreement with neumes: 
1. notes not having specific durations
2. ligatures originated in neumes, but they didn't have a specific meaning in terms of duration (they indicated melismas)
3. And they are transcribed in CMN just as you did, with black note-heads (normally ligatures are indicated by using brackets above those note-heads). 

> These notes have not a specific duration, or at least all of them have the same, they depend on the singer. Notice that it has not any meter / mensuration sign first despite being the first page. Notes in this kind of plain chant are usually notated as blackened brevis to contrast it with white mensural brevis that denote a measured duration. What seem to be ligature are not actually ligature in the mensural notation sense with different duration of their components depending on the shape, just notes with the same duration that conform a melisma. This example should be transcribed to modern notation as...

This is why with respect to:
> Point 2) The first example notation is not any of mensural or neumatic, it's a new one we don't have yet in notationType. Maybe it would be better just having it as notationtype="mensural" and notationsubtype="plainchant". I suggest to encode them as they are written using <note dur="brevis" colored="true" pname....> and embedding in a ligature in case of being drawn as ligature. The system that finds the notationsubtype="plainchant" should known the rules to process correctly the durations.

If this is still neumatic notation, it should be encoded as `@notationtype = neume` and the notes should be encoded according to the **neume module** (using **mei-all** for validation). But I am not 100% sure. I will verify for sure that these are neumes with a Guatemalan musicologist (since the MSS comes from Guatemala). But I would also like to consult @elsinhadl, because Elsa is a Musicologist familiar with Iberian musical notation (she is Coordinator of the Portuguese Early Music Database). And she is way more familiar with neumes than I am (the documentation for the Neume module v.4 has been worked by her). The question, @elsinhadl, is about [this comment](https://github.com/music-encoding/music-encoding/issues/645#issuecomment-618575993). Is the 'Asperges me' incipit of this piece written in neumes or is it some other type of notation? The rest of the piece is set in polyphony and uses mensural notation.

![80131685-e1ebb480-859a-11ea-9837-ae4e0cee3627](https://user-images.githubusercontent.com/13948831/80413623-b8ce6b00-889d-11ea-8adf-ead6d292c568.png)

Aside from this, I agree with the other two points, @davidrizo.

If I am wrong, and plainchant is not normally notated in neumes, I agree that another value needs to be introduced for plainchant.

**Comment by martha-thomae** [comment]
Regarding the other example—the one that looks like black mensural notation, but it is not—I agree with @lpugin solution. The use of a `@notationtype` and `@notationtype.ges` attributes to encode the visual and gestural domain seems perfect. 

> Regarding the example below, all notes, despite their notated figure, should be played with the same duration.
> ![](https://user-images.githubusercontent.com/10772049/80128991-c2eb2380-8596-11ea-84b3-068005c6b482.png)


> Then, I would use notationtype="mensural", notationtype.ges="plainchant"

Yes, I agree, it would be something like `@notationtype = "black.mensural"` and `@notationtype.ges` equal to either `"neume"` or `"plainchant"` (whichever is more appropriate).

@lpugin, I hadn't seen the issue https://github.com/music-encoding/music-encoding/issues/597 before, but this seems perfect for pieces that fall in any transition period.

**Comment by pe-ro** [comment]
I think 
```
@notationtype = "black.mensural"
@notationtype.ges = "neume" (or "plainchant")
```
is gilding the lily.

Why not simply 
```
@notationtype="black.mensural"
@notationsubtype="neume" (or "plainchant")
```
?
This adequately captures the "form" of the notation in `@notationtype` and its function in `@notationsubtype` without adding yet another attribute.

Since the value space of `@notationsubtype` is unconstrained, it may even contradict `@notationtype`, for  example, in those cases where one form of notation is effectively functioning as another, 
```
@notationtype="black.mensural"
@notationsubtype="white.mensural"
```
Complex relationships between notationtype and notationsubtype can be addressed by using `<taxonomy>`.
 
It would be a good idea to rename `@notationtype` to `@notationType` and `@notationsubtype` to `@notationFunction`.

**Comment by elsinhadl** [comment]
Hi,

Thank you for involving me in this interesting discussion. 

_- Is the 'Asperges me' incipit of this piece written in neumes or is it some other type of notation?__
It is square notation, thus it is encoded using the MEI neume module. This incipit is sung as plainchant (no concern for expressing the rhythm in the notation).

_- @davidrizo 's incipit Dixit Dominus Domine meo:_ 
this looks notated in _[cantus fractus](https://www.oxfordreference.com/view/10.1093/oi/authority.20110803095547883)_, that is, plainchant with some mensural elements, e.g. the semibrevis shape). The Spanish treatise you mention is clear in saying that despite the shape of the notes, they are sung with the same duration (= as cantus planus/plainchant/canto llano).  Thus, in this case it may be useful to have a @notationFunction="plainchant" (or "cantusplanus")

However, we should take into account that sooner or later someone will come across a piece of music in cantus fractus, that is, an hybrid notation between plainchant and mensural notation. You can see some examples of cantus fractus [here](http://www.cantusfractus.org/raph_1/manoscritti/FC_057.htm#p.%2091)
A piece in cantus fractus looks like written in mensural notation but actually it mixes elements of square and mensural notation. Usually it has no exact mensural value but is still sung with some concern for the rhythm.  Hence, it may be useful to have also @notationFunction="cantusfractus"

Please do let me know if I missed anything or my explanation was unclear. 

Elsa

**Comment by lpugin** [comment]
@pe-ro 

> This adequately captures the "form" of the notation in `@notationtype` and its function in `@notationsubtype` without adding yet another attribute.

I agree that `@notationtype.ges` is meant to serve a different purpose - I guess this is what you are referring to. Its purpose is to cover cases when the visual aspect of a notation differs than the gestural one. Maybe this is not useful in this particular case, but certainly in other ones in my opinion. I can elaborate in #597 if you think this is desirable. (This being said, I am not convinced by the distinction made between form and function for `@notationtype` and `@notationsubtype`)

**Comment by pe-ro** [comment]
We can take the discussion over to #597 if you like, but first I'd like to say that instead of `@notationtype.ges`, I'd prefer additional values in `@notationtype`.  One approach would be to use the value 'transitional' in `@notationtype`, then give the principal types in `@notationsubtype`.  For example,
```
notationtype="transitional" notationsubtype="neume mensural.black"
```
would indicate a transitional notation between neume and black mensural notation that has features of both.  This is the most flexible solution because it allows transitions between any notational types, even if they're nonsensical --
```
notationtype="transitional" notationsubtype="neume aleatoricCMN"
```

Another possibility is to allow multiple values from the current vocabulary in `@notationtype`, 
```
notationtype="neume mensural.black"
```
which would allow multiple type values, but with the added benefit of reserving `@notationsubtype` for additional extension/restriction.

The last possibility is to provide new values for `@notationtype` that name the transitional styles, like _cantus fractus_, e.g.,
```
notationtype="cantusFractus"
```
the individual words of "cantus fractus" being conjoined in order to preserve the later possibility of multiple space-separated values.  I prefer this last one as it is the most explicit.

I think it's important to note that no matter how we choose to resolve this question, it won't be possible to capture every nuance.  For instance, neither `notationtype="transitional" notationsubtype="neume mensural.black"` nor `notationtype="neume mensural.black"` says anything about the direction of the transition. I'm guessing that `cantus fractus` does capture this, but there may not be precise names for other transitional periods, and even if there are, it may be difficult (or perhaps impossible) to name every transitional nuance in every domain -- the notation may be transitioning in rhythmic terms but not in pitch designation, etc.  These attributes will only ever provide the broadest of categorization, the remedy for which is to use `<taxonomy>`.

**Comment by hajicj** [comment]
Hi all,

just to provide more examples for this discussion, we have situations like this:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/4629511/86152342-8fc19500-baef-11ea-945b-5bfa2c1c9820.png">

where mensural and rhombic plainchant notation mix rather freely. In this case, it seems to me that the brevis-like shapes in the beginning are showing the singers just to make the first two notes longer, like repeated notes in square chant notation, and act therefore as a kind of ligature. But also everything can be considered black mensural semibreves -- with chant-like ligatures of semibreves. Another example from the same manuscript:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/4629511/86153470-43775480-baf1-11ea-9f2c-70e139734d5c.png">

I am not even sure how to sing this, so I don't have any ideas on how to properly represent it, but I'm hoping these examples will be helpful in the discussion on encoding this transitional notation.

**Comment by pe-ro** [comment]
@hajicj, Have you tried validating an encoding containing mensural and neume features against mei-all.rng or mei-all_anyStart.rng?  The following example demonstrates how notes, neumes, and ligatures can be combined within a `<layer>`:
```
<staff xmlns="http://www.music-encoding.org/ns/mei">
  <layer>
    <neume/>
    <note/>
    <ligature>
      <note/>
    </ligature>
  </layer>
</staff>
```

**Comment by martha-thomae** [comment]
Hello! 
It seems like everyone agreed with @pe-ro proposed solution (I am attaching it here at the end). So, if this is alright with everyone, I would like to make a PR for adding the notationtype-related attributes into the `<section>` and `<ending>` elements.

> 1. It would not be heretical to make `<section>` and `<ending>` and perhaps `<mdiv>` members of att.notationType.  This would permit capturing the notation type of time spans.
>
> 3. As for alignment, wrap each kind of notation in its own `<section>`. In the 1st section, only staff 2 will have content.  Without content, the other staves are implicitly silent/tacet. In the 2nd section, all staves will have content.  If you do decide to mix neume and mensural notation, you'll need to validate against the **mei-all schema** or create a new customization that mixes these.

**Comment by lpugin** [comment]
This sounds good to me and I can see it being useful in many cases. I am only a little be unsure with the need to have in on `<ending>` since the element seems pretty much bound to CWMN. Am I overlooking something?

**Comment by martha-thomae** [comment]
Hi @lpugin! No, I think you are right based on the description of the element. I will make the changes just for `<section>` then.

What about adding `@notationtype` to `<mdiv>` (which was also suggested by Perry)?

**Comment by kepper** [comment]
Sorry for coming late to the discussion, and apologies if I've missed the obvious somewhere. I have one question, though: Does this, by any means, provide support for mixing repertoires "vertically", i.e. have one staff in mensural notation, and another staff in say CMN, providing a transcription of the first? I'm aware that this causes a whole lot of other problems (do I hear `<measure>` or `multi-metrical music` anywhere?), and so resolving it depends on quite some other beasts to be tackled, but eventually (probably in a later revision), this should be considered as well, right?

**Comment by martha-thomae** [comment]
Hi @kepper!
Sorry to get back to you a few days later...

I am afraid this doesn't deal with the issue of "vertically" mixing repertoires. Let's say that it allows for mixing repertoires "horizontally." For example, allowing for one section to encode chant, followed by a section encoding mensural. Something like this:

![](https://user-images.githubusercontent.com/13948831/80413623-b8ce6b00-889d-11ea-8adf-ead6d292c568.png)

This would be especially useful when all voices are in polyphony, but only one of them has a chant incipit, like this:

![GuatC1_f 1_annotated](https://user-images.githubusercontent.com/13948831/88610989-179ab080-d056-11ea-8d53-1a8e957702ab.png)

So, in the **first section**, **only one** of the four **`<staff>`** elements would have a `<layer>` **with actual music content**—the chant incipit—while the other three would be empty. And **in the second section, all four `<staff>` elements would have music content**—the polyphonic section in mensural notation. Since the mensural notation would be in its own section, the polyphony would start simultaneously in all four voices. If we didn't have a dedicated section for the chant incipit, the voices 1, 3, and 4 would start when voice 2 is still in the chant incipit.
______

It would be nice to also come up with a solution that mixes voices vertically allowing for both a mensural staff and a CMN notation staff (but, yes, the `<measures>` would be an issue). But I am afraid what we are proposing here is not related to that. Will be thinking about it, though.

**Comment by kepper** [comment]
Hi @martha-thomae, no worries. This wasn't so much about giving you extra homework, it was more to remind some others, including @pe-ro, @lpugin and myself that this is still an open issue (even though I don't have an issue number at hand, and there may not even be one yet – it's just something we've discussed a couple of times, years ago). It's more about polyrhythm, as seen for instance in Mozart's _Don Giovanni_ (2/4 vs 3/4), which makes it necessary to separate between vertical "sections" of a score. Such a mechanism, however, should also enable us to mix notational systems vertically. While the directions for that are clear (if I remember correctly), it's still to be implemented. 
I think what you've proposed for the example above makes perfect sense – just have a section that is tacet in all but one voice, and then have a subsequent section for all voices in a separate notational system…

**Comment by martha-thomae** [comment]
> What about adding @notationtype to <mdiv>?

Regarding this question, I won't add `@notationtype` to the `<mdiv>` element. I think it is not necessary now, since`<mdiv>` has its own `<scoreDef>` containing `<staffDef>` elements that **do indicate** the `@notationtype`.

On the other hand, `<section>` does need the `@notationtype` attribute to be able to encode two sections in different notations.

----

With that stablished, I worked on the PR for including `@notationtype` in `<section>` (the change is simple and it is ready on my fork). But when I worked on an example to show how this new feature would look like, I started to question if this was the best way to encode a chant incipit of a polyphonic piece, so I want your feedback. 

@kepper, @lpugin, @pe-ro: from the following two proposals for encoding a chant incipit of a polyphonic piece, which would be the most appropriate (based on your experience with MEI and how things usually get encoded in other repertoires)? Or is there even a third option more appropriate?

Here are the two proposals, followed by the issues I found with each of them (I am not even completely convinced if they are real issues, that is why I want to consult with you):

* **Option 1:** Using one `<mdiv>` with one `<scoreDef>` and two `<section>` elements, one for the chant incipit and another for the polyphonic section. The first `<section>` would have a `@notationtype = "neume"`, and the second `<section>` would have a `@notationtype = "white.mensural"`.

* **Option 2:** Using one `<mdiv>` element with two `<mdiv>` as children. The first `<mdiv>` would encode the chant incipit (with the `@notationtype="neume"` being used within its `<staffDef>` elements), and the second `<mdiv>` would encode the polyphonic section (with the `@notationtype="mensural.white"` being used within its `<staffDef>` elements). Each `<mdiv>` would already contain its own `<scoreDef>` and `<section>` elements.

**"Cons"** of each approach:

* **Option 1**. Using two `<section>` elements, we would have to encode the mensuration within the `<layer>` itself, right? (See commented lines in the _sections_testing_ file.)

  If we were to encode the mensuration in the `<staffDef>` elements, the mensuration sign would be rendered before the chant incipit (see image). And, regardless of how Verovio renders it, I think encoding the mensuration in `<staffDef>` is not appropriate since the mensuration does not apply to the whole voice, but only to the second section. So, again, I guess the most appropriate thing is to encode the mensuration of each voice in a `<mensur>` element within the corresponding `<layer>`. I don't know if this would actually be a "con," but **it was my impression that encoding the mensuration using `<mensur>` within `<layer>` was more appropriate for changes in mensuration; and that when we are defining the mensuration of a voice (or the initial mensuration of a voice), it would be preferable to encode this within`<staffDef>`.**

  ![option1_twoSections](https://user-images.githubusercontent.com/13948831/88940167-737f5800-d255-11ea-9e81-e9841b14d6dc.png)

  **Short note:** In the _sections_testing_ file, please ignore the `@notationtype` attributes in the `<staffDef>` elements. These were included just so that Verovio could render the example. Again, the `@notationtype` attributes would be in the corresponding `<section>` elements.

* **Option 2**  was to use two `<mdiv>` elements (each with its own `<scoreDef>` and `<section>` elements) to encode the chant incipit and the polyphonic segment of the piece, respectively. In this solution, the mensuration can be safely encoded within the `<staffDef>` elements of the second `<mdiv>` element, so the issue outlined in the previous bullet point is not present here. (Clefs are also encoded in the `<staffDef>` elements of each `<mdiv>`, in case they are different between the chant incipit and the polyphonic section.)

  The file showing this is the _mdiv_testing_. The two following images show the rendering in Verovio of each of the two `<mdiv>` children (I commented the other to be able to render them in Verovio).

  ![option2_twoMdivs_mdiv1](https://user-images.githubusercontent.com/13948831/88943932-19cd5c80-d25a-11ea-9a67-4b1f7ec6c4c1.png)

  ![option2_twoMdivs_mdiv2](https://user-images.githubusercontent.com/13948831/88943962-20f46a80-d25a-11ea-84b2-1a0d0dcaa77b.png)

  But I don't know if this is a good solution because all the examples I find in the guidelines using `<mdiv>` tend to encode larger sections of music (e.g., movements, acts, or scenes). I don't find any explicit statement about the constraint of `<mdiv>` to only large sections, though. **But I would like to know if this is still a good solution; if `<mdiv>` could be used to encode chant incipits of a polyphonic piece, or if this element is not appropriate to encode such a short music passage.**

I guess my question is, which solution is more consistent with MEI's use? Is there another solution not even considered?
Do these "cons" even represent actual issues?

[testing_2sections_vs_2mdivs.zip](https://github.com/music-encoding/music-encoding/files/5002304/testing_2sections_vs_2mdivs.zip)

**Comment by martha-thomae** [comment]
Johannes proposed a solution for the particular problem @davidrizo was introducing here (and that I also need to solve for encoding the Guatemalan manuscript I am working with). Again, the problem poster here is the most MEI-like or standard way to encode a polyphonic piece with a chant incipit (see image).

<img src="https://user-images.githubusercontent.com/13948831/88610989-179ab080-d056-11ea-8d53-1a8e957702ab.png" width="550"/>

Johannes proposed the solution of using two sets of `<scoreDef>` and `<section>` elements within the `<mdiv>` element. The first pair of `<scoreDef>` and `<section>` would encode the chant incipit, and the second one would encode the polyphonic part of the piece (what is in mensural notation).

The file encoding both would look like this:

[oneMdiv_TwoSetsOfScoreDefAndSection.xml.zip](https://github.com/music-encoding/music-encoding/files/5039069/oneMdiv_TwoSetsOfScoreDefAndSection.xml.zip)

When I render this in Verovio, it only shows gives me an error. If I erased one of the two pairs of `<scoreDef>` and `<section>`, it renders the other perfectly (regardless of which pair I erase, the one encoding neumes or the one encoding mensural).

@lpugin: How difficult / how much effort would it be involved for Verovio to be able to render both?

**Comment by martha-thomae** [comment]
This issue is solved with Johannes's proposal, shown in https://github.com/music-encoding/music-encoding/issues/645#issuecomment-670294397. It just needs to be added to the guidelines for documentation.
