### ISSUE TITLE
Reconsidering the need of `<phrase>` element

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#667]
I would suggest to reconsider the need of the `<phrase>` element and the possibility to replace it with an attribute on `<slur>` - or have more generic element name for both. Since a phrase and a slur look the same and that they are even often interchangeable, having an attribute to distinct them is probably enough. It seems to me that we have a semantic granularity discrepancy in comparison with other elements, such as `<dir>`, and dropping `<phrase>` would be more inline them. I would argue that `<tie>` has a different purpose / meaning and should remain a distinct element.

**Comment by rettinghaus** [comment]
After thinking twice about that, I think it is ok to have `@func` on `<slur>` to further specify its kind, and then drop `<phrase>`. Biggest question is: should `@func` be semi-open or closed? I can think of `legato`, `phrase`, `syllable` and `unknown`.

**Comment by lpugin** [comment]
Other opinions on this? Or objections? If not I will make a PR

**Comment by kepper** [comment]
I've commented on this topic over here: https://github.com/rism-ch/verovio/pull/1466#issuecomment-632615872. I don't think that we should use the "Bindebogen" `<slur>` for the generic "Bogensetzung". Much rather, we should treat `<slur>` as syntactic sugar for a new, yet-to-be-named element for arbitrary curved lines / arcs (just like `<phrase>`). I'd like to hear better / more convincing arguments…

**Comment by pe-ro** [comment]
There's already a `<curve>` element for marking curved lines/arcs that are neither slurs nor phrases.  And it conveniently carries a `@func` attribute.

**Comment by ahankinson** [comment]
I could imagine that semantic marking of music notation would want to treat slurs and phrases differently, even though visually they look very similar. Perhaps `phrase` could or should be retained as an analytical element (or attribute)?

**Comment by kepper** [comment]
so we should investigate if and how the models of `<slur>`, `<phrase>` and `<curve>` need to be unified, and then think about some more values for that semi-open list. No need to drop `<phrase>` here…

**Comment by pe-ro** [comment]
`<slur>` and `<phrase>` are intended to be syntactic sugar for `<curve func="slur">` and `<curve func="phrase">`.  The values of `@func` on `<curve>` can never be a closed set (`<curve>` can be used to "draw" all kinds of arbitrary things), hence the need for semantically-meaningful elements like `<slur>` and `<phrase>`.  I wouldn't recommend removing these elements.

It wouldn't hurt to expand the currently allowed set of values for `curve/@func` beyond "unknown".

It would be ok to unify `<slur>` and `<phrase>` into a single element with `@func` allowed to take the values "slur" or "phrase".  But that element shouldn't be `<curve>` for the reasons already given.  Still, I don't understand why this is necessary.  Is it just to avoid duplicating the code invoked by the different elements?  What's the problem with having 2 different elements result in the same code being called?

**Comment by craigsapp** [comment]
The problem with differentiating between `<slur>` and `<phrase>` is that there is a continuum between the function of the two.  In other words, they are both slurs (curves), and one describes an articulation (perform the notes legato, or with a single bow stroke, without tonging) and the other describes the phrasing (not intended to describe the performance articulation but how to conceptualize grouping of the notes).  There can be cases where the articulation slur is also a phrasing slur.  "phrase" is an analytic concept which gets complicated if you are to mix with visual domain, where an "analytic phrase" would be some music that ends in a cadence or otherwise has a structural grouping function.  There are also hierarchies of phrasing.  For example there are antecedent and consequent phrases, and these also form a larger period phrase, and there are also phrasing slurs that group partial phrases, and sometimes the meaning of a slur is difficult to distinguish between an articulation or phrasing slur.  How people encode these functions will not be consistent.

Using `@func` on slur is best.  If there is no `@func` attribute, then that should be assumed to have an "unknown" function, of course.  The main two functions would be an articulation slur and a phrasing/grouping slur.  Hauptstimme and Nebenstimme are related to phrasing.

Here is a random example:

https://ks.imslp.net/files/imglnks/usimg/3/33/IMSLP369144-PMLP02282-Chopin_-_Opus_24_Cortot_french.pdf

<img width="716" alt="Screen Shot 2020-06-04 at 3 42 18 PM" src="https://user-images.githubusercontent.com/3487289/83817594-06e34500-a67a-11ea-9bea-e2bc7d54c1bd.png">

The slurs in the top staff are phrasing slurs, and the slurs in the bottom staff are articulation slurs.  The music is marked as "legato", so articulation slurs are not needed per se.

Humdrum has a slur `()` and a phrase `{}` system.  I interpret the phrase markers to be used to mark analytic phrases (demark music with cadential endings or structural boundaries), and these phrase markers are not intended to be (necessarily) visible in the graphical music notation, but rather used to encode the structure of the music for analysis.

**Comment by pe-ro** [comment]
MEI `<slur>` and `<phrase>` elements should be interpreted the same way.  They have the same visual appearance, but `<slur>` is for articulation curves and `<phrase>` represents curves (provided on the page) that have a structural/analytical purpose. 

The marking of arbitrary, unrendered phrase boundaries (especially when they contradict the visual phrase markings) can be encoded using the `<annot>` element.  The remarks at [https://music-encoding.org/guidelines/v4/elements/annot.html](url) describe how to use the element to comment on an arbitrary collection of nodes.

**Comment by lpugin** [comment]
I fully acknowledge the need to be able to encode a phrase, and we need to keep it. I am only suggesting to 'downgrade' it from element to attribute. Now of course, it would be ideal to have a name similar to the German one, because saying `<slur func="phrase"`> is not perfect. However, I would not go for `<curve>` because this is too generic. The main point is that downgrading it has the advantage to better deal with the grey area between phrases and slurs and to offer more flexibility. In the end, we have the best of the two words - encodings that make the distinction can very easily be processed by tools that do not while not loosing much for the former. If you look elsewhere (Behind Bars, Dorico), phrases are slurs. Some define them as slurs above slurs, but there is never a clear distinction as far as I know.

**Comment by lpugin** [comment]
@pe-ro 

> Still, I don't understand why this is necessary. Is it just to avoid duplicating the code invoked by the different elements? What's the problem with having 2 different elements result in the same code being called?

There are way not to duplicate code, no problem. This was only an MEI question. I had the feeling that `<phrase>` is not widely used. I thought that one reason for this is that having a distinct element than `<slur>` for encoding phrases is an attempt to draw a line between things that are actually difficult to define and differentiate. Hence the proposal to use instead an attribute, but I am fine with `<phrase>`.
