### ISSUE TITLE
Iranian quarter tones (Koron and Sori)

### ISSUE THREAD

**Issue by Ashkanph** [music-encoding/music-encoding#680]
Hi

I wanted to use [Verovio](https://www.verovio.org/index.xhtml), But It uses mei and mei doesn't support the two Iranian quarter tones ( [Koron](https://en.wikipedia.org/wiki/Koron_(music)) and [Sori](https://en.wikipedia.org/wiki/Sori_(music)) ).

Please consider adding them to your project. I will add some examples at the end of this issue.

Thanks in advance

------------------

![1](https://user-images.githubusercontent.com/22937754/85721039-3bd93980-b706-11ea-9ca6-ef68e625c8d6.png)

![2](https://user-images.githubusercontent.com/22937754/85721068-44317480-b706-11ea-878d-26255793e3e6.png)

![daramad dashti saba](https://user-images.githubusercontent.com/22937754/85721096-4b588280-b706-11ea-99fd-57e275a7423b.png)

![3](https://user-images.githubusercontent.com/22937754/85721120-50b5cd00-b706-11ea-9c17-aad13b5fd5a1.jpg)

![4](https://user-images.githubusercontent.com/22937754/85721160-5c08f880-b706-11ea-80a9-b0e1eac2c3f0.jpg)

**Comment by lpugin** [comment]
For the record https://w3c.github.io/smufl/gitbook/tables/persian-accidentals.html

**Comment by ahankinson** [comment]
Is it possible to encode the notation with a quarter-flat / quarter-sharp, but then use the SMuFL glyph to display it in Verovio?

**Comment by Ashkanph** [comment]
> Is it possible to encode the notation with a quarter-flat / quarter-sharp, but then use the SMuFL glyph to display it in Verovio?

Actually they are not precisely quarter tones; But the difference is not much. So I think using quarter-flat and quarter-sharp can be enough. (I am not sure if the question was for me. I am just a simple front-end developer who wants to use the Verovio's javascript version)

But what about the `midi player` and `Verovio musicxml converter`? Musicxml supports the Koron/Sori, and writing the Musicxml in Ubuntu is much easier for me than Mei.

**Comment by pe-ro** [comment]
Encoding as quarter-tone accidentals and displaying them using the SMuFL glyph would be an efficient temporary work-around.

But, if the Iranian accidentals aren't exactly quarter-tone adjustments, then what do they express?  It would be good to add them if they express something the current set of accidental concepts don't get at.  Adding them would make translation from MusicXML easier, but updating the musicxml2mei transform and/or the transform employed by Verovio would be required.

**Comment by craigsapp** [comment]
> And what about the midi player in Verovio? Can I have their sounds too?

To do non-equal-temperament in Standard MIDI Files, the tuning has to be adjusted using pitch-bend messages. So in theory this is possible, but there will be limitations (the three examples you give will all work): 

* only one voice on a staff at a time (no layers)
* no chords
* maximum of 15 staves.

> But, if the Iranian accidentals aren't exactly quarter-tone adjustments, then what do they express?

They are symbolic quarter-tones, in the similar manner that sharp/flat are semi-tones.  The temperament would indicate the exact ratio if it is not exactly a quarter tone.  

https://www.youtube.com/watch?v=YCVFkircZUg

What does the circle between notes mean?  And the diving fish after notes? and the wiggly line between notes in the last measure of the last example, and probably the same function twice in the second example?

**Comment by pe-ro** [comment]
Whether the Iranian accidentals are added to data.ACCIDENTAL.WRITTEN and/or data.ACCIDENTAL.GESTURAL or not, I think it would be a good idea to clarify the semantic effect of the "normal" accidentals (sharp, flat, natural, etc.) in terms of 1/2 steps (aka tones) the way the quarter tone accidentals are.  For example,
```
s Sharp. Pitch raised by a half step.
f Flat. Pitch lowered by a half step.
ss Double sharp. Pitch raised by 2 half steps. (written as 2 sharps). 
x Double sharp. Pitch raised by 2 half steps. (written using croix). 
ff Double flat. Pitched lowered by 2 half steps.
xs Triple sharp. Pitch raised by 3 half steps. (written as a croix followed by a sharp). 
sx Triple sharp. Pitch raised by 3 half steps. (written as a sharp followed by a croix). 
ts Triple sharp. Pitch raised by 3 half steps. (written as 3 sharps). 
tf Triple flat. Pitch lowered by 3 half steps.
n Natural. No alteration of pitch.
```
There is already precedent for visual differentiation (e.g., 'xs' vs 'sx') so adding 'koron' and 'sori' as variations of '1qf' and '1qs', respectively (if they're deemed to be equivalent/close enough) makes sense.  It makes even more sense to add them if they're a different class of accidental than the usual 1/2 or 1/4 tone types.

**Comment by pe-ro** [comment]
I don't know if Verovio supports MEI's MIDI elements, but the pitch bend messages Craig referred to can be encoded using `<cc>` elements.  See [https://music-encoding.org/guidelines/v4/elements/cc.html](url).

**Comment by craigsapp** [comment]
`<cc>` is for continuous controllers, but pitch bend MIDI messages are needed.  What element are those?  Not `<pb>` since that means page break.

**Comment by rettinghaus** [comment]
@Ashkanph could you add an example MusicXML file?

**Comment by pe-ro** [comment]
@craigsapp, sorry, I misspoke, there's a separate element called `<bend>`. See [https://music-encoding.org/guidelines/v4/elements/bend.html](url).  It's not in the model.midiLike class since it can be used for graphical (as in guitar notation) as well as gestural bend information.

**Comment by craigsapp** [comment]
I saw `<bend>` but also noticed that it was graphical.  Also, pitchbend is typically a dynamic change over time, so there should be multiple MIDI pitchbend messages for each `<bend>`.  For non-equal-temperament simulation in General MIDI files, a single MIDI pitch bend message is needed immediately before the note (rather than a series of messages after the note), and another to cancel the bend after the note (or think of it as another bend before the next note).

In this case, explicit MIDI pitch-bends would not necessarily be needed in the MEI encoding, since they could be interpreted from the quarter-tone accidentals and handled behind the scenes (maybe with an option to verovio when converting into MIDI).  When a quarter-tone needs to be played, a pitch-bend is given before the note to adjust to that quartertone pitch, then the note is attacked.  When returning to a non-quarter-tone pitch another pitchbend message is given that adjusts the pitch.    MIDI pitchbend affects all active notes on a MIDI channel, so all notes in a chord would be affected by the same amount (so they could all be tuned out of equal-temperament, but the will be in equal-temperament with respect to each other).  Another minor consideration is that the pitch-bend depth is programmable (typically the bend range is +/- 2 semitones by default).

I implemented a just-intonation tool for a compositional project in my class this past quarter:  https://github.com/craigsapp/ratioscore/tree/master/scores
This is a proof-of-concept for realizing koron and sori, or any other tuning system for monophonic instruments.

For example, here is a score that arpeggiates just fifths and just major thirds:

https://github.com/craigsapp/ratioscore/blob/master/scores/test6.txt

```
!!!OTL: Exponentiation test
**time	**ratio
*MM120	*ref:C1
!! Up by just perfect fifths:
0	(3/2)^0
1	(3/2)^1
2	(3/2)^2
3	(3/2)^3
4	(3/2)^4
5	(3/2)^5
6	(3/2)^6
7	(3/2)^7
8	(3/2)^8
9	(3/2)^9
10	(3/2)^10
11	0
!! Up by just major thirds:
12	(5/4)^0
13	(5/4)^1
14	(5/4)^2
15	(5/4)^3
16	(5/4)^4
17	(5/4)^5
18	(5/4)^6
19	(5/4)^7
20	(5/4)^8
21	(5/4)^9
22	(5/4)^10
23	(5/4)^11
24	(5/4)^12
25	(5/4)^13
*-	*-
```

Here is a zipped MP3 file of the score (after rendering to MIDI and converting to MP3):  [test6.zip](https://github.com/music-encoding/music-encoding/files/4834102/test6.zip).  Just perfect fifths are close to equal temperament so there is not must difference, but if you listen to the just major thirds, you should be able to hear the notes sound quite out of tune as the arpeggiation progresses (since each a just major third is about 16 cents flat of equal temperament).


Here is the compiled MIDI file in a text-based representation, with each MIDI event on a separate line.  A MIDI event starts with a time (prefixed with a `v`) and then the MIDI bytes for the event.

```
"MThd"			; MIDI header chunk marker
4'6			; bytes to follow in header chunk
2'1			; file format: Type-1 (multitrack)
2'2			; number of tracks
2'1000			; ticks per quarter note

;;; TRACK 0 ----------------------------------
"MTrk"			; MIDI track chunk marker
4'18			; bytes to follow in track chunk
v0	ff 51 v3 t60	; tempo
v0	ff 51 v3 t120	; tempo
v0	ff 2f v0	; end-of-track

;;; TRACK 1 ----------------------------------
"MTrk"			; MIDI track chunk marker
4'330			; bytes to follow in track chunk
v0	e0 '0 '64	; pitch-bend 8192(0.000000)
v0	90 '24 '64	; note-on C1
v999	80 '24 '64	; note-off C1
v1	e0 '80 '64	; pitch-bend 8272(0.009766)
v0	90 '31 '64	; note-on G1
v999	80 '31 '64	; note-off G1
v1	e0 '32 '65	; pitch-bend 8352(0.019531)
v0	90 '38 '64	; note-on D2
v999	80 '38 '64	; note-off D2
v1	e0 '112 '65	; pitch-bend 8432(0.029297)
v0	90 '45 '64	; note-on A2
v999	80 '45 '64	; note-off A2
v1	e0 '64 '66	; pitch-bend 8512(0.039062)
v0	90 '52 '64	; note-on E3
v999	80 '52 '64	; note-off E3
v1	e0 '16 '67	; pitch-bend 8592(0.048828)
v0	90 '59 '64	; note-on B3
v999	80 '59 '64	; note-off B3
v1	e0 '96 '67	; pitch-bend 8672(0.058594)
v0	90 '66 '64	; note-on F#4
v999	80 '66 '64	; note-off F#4
v1	e0 '49 '68	; pitch-bend 8753(0.068481)
v0	90 '73 '64	; note-on C#5
v999	80 '73 '64	; note-off C#5
v1	e0 '1 '69	; pitch-bend 8833(0.078247)
v0	90 '80 '64	; note-on G#5
v999	80 '80 '64	; note-off G#5
v1	e0 '81 '69	; pitch-bend 8913(0.088013)
v0	90 '87 '64	; note-on D#6
v999	80 '87 '64	; note-off D#6
v1	e0 '33 '70	; pitch-bend 8993(0.097778)
v0	90 '94 '64	; note-on A#6
v999	80 '94 '64	; note-off A#6
v1001	e0 '0 '64	; pitch-bend 8192(0.000000)
v0	90 '24 '64	; note-on C1
v999	80 '24 '64	; note-off C1
v1	e0 '79 '91	; pitch-bend 11727(0.431519)
v0	90 '27 '64	; note-on D#1
v999	80 '27 '64	; note-off D#1
v1	e0 '31 '87	; pitch-bend 11167(0.363159)
v0	90 '31 '64	; note-on G1
v999	80 '31 '64	; note-off G1
v1	e0 '110 '82	; pitch-bend 10606(0.294678)
v0	90 '35 '64	; note-on B1
v999	80 '35 '64	; note-off B1
v1	e0 '62 '78	; pitch-bend 10046(0.226318)
v0	90 '39 '64	; note-on D#2
v999	80 '39 '64	; note-off D#2
v1	e0 '13 '74	; pitch-bend 9485(0.157837)
v0	90 '43 '64	; note-on G2
v999	80 '43 '64	; note-off G2
v1	e0 '92 '69	; pitch-bend 8924(0.089355)
v0	90 '47 '64	; note-on B2
v999	80 '47 '64	; note-off B2
v1	e0 '44 '65	; pitch-bend 8364(0.020996)
v0	90 '51 '64	; note-on D#3
v999	80 '51 '64	; note-off D#3
v1	e0 '123 '92	; pitch-bend 11899(0.452515)
v0	90 '54 '64	; note-on F#3
v999	80 '54 '64	; note-off F#3
v1	e0 '75 '88	; pitch-bend 11339(0.384155)
v0	90 '58 '64	; note-on A#3
v999	80 '58 '64	; note-off A#3
v1	e0 '26 '84	; pitch-bend 10778(0.315674)
v0	90 '62 '64	; note-on D4
v999	80 '62 '64	; note-off D4
v1	e0 '106 '79	; pitch-bend 10218(0.247314)
v0	90 '66 '64	; note-on F#4
v999	80 '66 '64	; note-off F#4
v1	e0 '57 '75	; pitch-bend 9657(0.178833)
v0	90 '70 '64	; note-on A#4
v999	80 '70 '64	; note-off A#4
v1	e0 '8 '71	; pitch-bend 9096(0.110352)
v0	90 '74 '64	; note-on D5
v999	80 '74 '64	; note-off D5
v0	ff 2f v0	; end-of-track
```

Here are the first two notes:

```
v0	e0 '0 '64	; pitch-bend 8192(0.000000)
v0	90 '24 '64	; note-on C1
v999	80 '24 '64	; note-off C1
v1	e0 '80 '64	; pitch-bend 8272(0.009766)
v0	90 '31 '64	; note-on G1
v999	80 '31 '64	; note-off G1
```

* The first line sets the pitch-bend to zero pitch adjustment
* The second line turns on the C1 pitch
* The third line turns off the C1 pitch
* The fourth line gives a new pitch bend, which is +1.95 cents higher if the pitchbend depth is set to 2.
* The fifth line turns on the G1 pitch
* The sixth line turns off the G1 pitch

So in other words, there is a single pitchbend message immediately before each note that adjusts the pitch that follows it.

Also, I had to add a 1-millisecond anticipation to the pitch bend so that it did not affect the note attack, but this will be dependent on the synthesizer perhaps.

----------------

Here is an example related more closely to `<bend>`:

```
**time	**ratio
*	*ref:C4
0	16/15H
1	_1h
*-	*-
```

In this score there is a single note that starts a just minor second above Middle C, and then pitch bend lowers the note to middle C.  Here is a zip file with the rendered MIDI and MP3 versions of the score:  [test.zip](https://github.com/music-encoding/music-encoding/files/4834129/test.zip)

Here is a text-based representation of the rendered MIDI file:

```
"MThd"			; MIDI header chunk marker
4'6			; bytes to follow in header chunk
2'1			; file format: Type-1 (multitrack)
2'2			; number of tracks
2'1000			; ticks per quarter note

;;; TRACK 0 ----------------------------------
"MTrk"			; MIDI track chunk marker
4'18			; bytes to follow in track chunk
v0	ff 51 v3 t60	; tempo
v0	ff 51 v3 t60	; tempo
v0	ff 2f v0	; end-of-track

;;; TRACK 1 ----------------------------------
"MTrk"			; MIDI track chunk marker
4'97			; bytes to follow in track chunk
v0	e0 '97 '67	; pitch-bend 8673(0.058716)
v0	90 '61 '64	; note-on C#4
v50	e0 '124 '65	; pitch-bend 8444(0.030762)
v50	e0 '23 '64	; pitch-bend 8215(0.002808)
v50	e0 '50 '62	; pitch-bend 7986(-0.025146)
v50	e0 '77 '60	; pitch-bend 7757(-0.053101)
v50	e0 '104 '58	; pitch-bend 7528(-0.081055)
v50	e0 '4 '57	; pitch-bend 7300(-0.108887)
v50	e0 '31 '55	; pitch-bend 7071(-0.136841)
v50	e0 '58 '53	; pitch-bend 6842(-0.164795)
v50	e0 '85 '51	; pitch-bend 6613(-0.192749)
v50	e0 '112 '49	; pitch-bend 6384(-0.220703)
v50	e0 '11 '48	; pitch-bend 6155(-0.248657)
v50	e0 '39 '46	; pitch-bend 5927(-0.276489)
v50	e0 '66 '44	; pitch-bend 5698(-0.304443)
v50	e0 '93 '42	; pitch-bend 5469(-0.332397)
v50	e0 '120 '40	; pitch-bend 5240(-0.360352)
v50	e0 '19 '39	; pitch-bend 5011(-0.388306)
v50	e0 '46 '37	; pitch-bend 4782(-0.416260)
v50	e0 '74 '35	; pitch-bend 4554(-0.444092)
v50	e0 '101 '33	; pitch-bend 4325(-0.472046)
v50	e0 '0 '32	; pitch-bend 4096(-0.500000)
v999	80 '61 '64	; note-off C#4
v0	ff 2f v0	; end-of-track
```

There is one pitchbend before the first note to set the frequency of C#4 to be a just minor second above C4, then notice that there are numerous MIDI pitchbend messages to realize the bend.

**Comment by Ashkanph** [comment]
> They are symbolic quarter-tones, in the similar manner that sharp/flat are semi-tones. The temperament would indicate the exact ratio if it is not exactly a quarter tone.

yes, this is true.

> What does the circle between notes mean? And the diving fish after notes? and the wiggly line between notes in the last measure of the last example, and probably the same function twice in the second example?

I think the circles in the first example and the wiggly lines in the last and second examples are related to the Iranian style of playing violin (I don't play violin so I don't know about the specific symbols they use. For example [this is a video of the playing of the first example (I hope the link is not a temporary link.)](https://aspb3.cdn.asset.aparat.com/aparat-video/7b183008a39defad9f3444b2f33ce5334450132-360p.mp4) It is `Daramade Dashti` from the second [Radif](https://en.wikipedia.org/wiki/Radif_(music)) book of [Abolhasan Saba](https://en.wikipedia.org/wiki/Abolhasan_Saba)).

I don't know what are those diving fish. The image is from a scanned book; Maybe some marks by the owner of the book.

@rettinghaus honestly i haven't tested them much. I only made some test with portable MuseScore and there was koron/sori in them. this is the result: [musicxml file](https://gist.github.com/Ashkanph/e5e0f3384924342d84a39bca14ca0c27)

**Comment by pe-ro** [comment]
@craigsapp, you're right, a `<bend>` directive requires multiple MIDI pitch bend events to render (i.e., sound) the desired effect.  As you say, these don't have to be explicitly encoded -- they can be generated.  But, looking at it now, it would make sense to also add an element, perhaps called `<pitchBend>`, `<pBend>` or `<mBend>`, to make it possible to capture MIDI pitch bend info, whether as a result of/linked to a `<bend>` directive or for microtonal deviations separate from bend directions.

**Comment by pe-ro** [comment]
Adding `<pitchBend>` should probably be split off into a separate issue.

**Comment by craigsapp** [comment]
Yes, adding `<pitchBend>` would be good.

Looking at the circles in the notation as the violinist plays, I would say that they function as grace notes after a regular note, and the vertical position of the circle probably indicates the pitch (only step up or step down in the examples, but may also be a larger interval).  If not literal grace notes then they otherwise take 1/2 of the previous notes duration for the pitch marked a step above or below the main note in order to make it easier to read the music (instead of 32-notes, only 16th notes need to be shown).

If the fish are hand-written, then they could be stylized circles.

**Comment by rettinghaus** [comment]
I don't think that using pitch bend messages is the way to go here. The MIDI tuning standard seems to be more appropriate. 
We already have `@tune.temper` on `<scoreDef>`, but can't say anything processable about single pitches. 
I would like to see a `@midi.tuning` attribute on `<instrDef>` which could point to a table-like precise definition of each and every pitch in the `<meiHead>`. That would allow for sending a bulk tuning dump message at the beginning of a piece, and it could even be changed during playback with a redefined `<instrDef>`.
See https://en.wikipedia.org/wiki/MIDI_tuning_standard

**Comment by rettinghaus** [comment]
related to #612

**Comment by craigsapp** [comment]
> See https://en.wikipedia.org/wiki/MIDI_tuning_standard

This is not supported by all MIDI synthesizers (such as Wild Web MIDI), so it could be used, but not be implemented for all synthesizers.  In addition, you are limited to 12 notes per octave regardless of the temperament.  If you need 13+ notes octave, there is a problem.  The pitch-bend method will be universally playable, but there are also limitations.

In any case, it is better to hide the realization with explicit pitch bend messages in the MEI data, and infer the pitch-bend values from temperament or tuning information as needed, which would be handled by the conversion of MEI to MIDI.

**Comment by Ashkanph** [comment]
> I would say that they function as grace notes after a regular note

Yes, You are right. Thank you

[This is the mp3 of the third example](https://drive.google.com/file/d/1TYcItiNXig291HkMFH_wAP6I0avls7zp/view?usp=sharing)

and [This is the video of the second example from Instagram](https://www.instagram.com/p/BsljieOAueO/)

It would be really nice to be able to put Iranian sheet musics in online websites with their midi. But most of the current javascript libraries don't support it.

**Comment by kepper** [comment]
should be read more carefully, maybe adding an attribute class for iranian accidentals
