### ISSUE TITLE
Make Schematron rule for mixed beams a warning

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#690]
The scheamtron rule `check_beam_place` requires all notes/chords within `<beam place="mixed">` to have a `@stem.dir`. 
This doesn't make sense, as you may want to advise the engraver to put a beam between the note heads without giving explicit stem directions. 
Also, it is not available with `beamSpan`, which isn't very consistent.

**Comment by craigsapp** [comment]
If there are two notes in the beam, then the stem directions should be easy to infer for a mixed beam.

If there are more than two notes in the beam, then it becomes more difficult to figure out the stem directions (and placement of the beam).  But in almost all cases it should still be clear: look for the largest interval of all of the notes are on a staff in which to place the beam, or separate notes by staff if the beam is cross-staff.

A problem will occur when the stem directions are not correct for the mixed beam: if the beam is mixed and all notes are stem-up, what would/should happen?  Does the mixedness or explicit beam directions have priority? And should the Schematron check for such impossible cases?

**Comment by lpugin** [comment]
> If there are two notes in the beam, then the stem directions should be easy to infer for a mixed beam.

See your example here ;-) https://github.com/music-encoding/music-encoding/issues/391#issuecomment-274619339 Looking at the interval does not tell you anything. When notes are on the same staff, then you probably need stem direction indications. Detecting if they make sense will be difficult to achieve via Schematron, I think, but I have very little knowledge of Schematron.

**Comment by craigsapp** [comment]
> Looking at the interval does not tell you anything.

😜 

https://github.com/music-encoding/music-encoding/issues/391#issuecomment-276353995

<img width="117" alt="Screen Shot 2020-07-15 at 10 35 08 AM" src="https://user-images.githubusercontent.com/3487289/87576954-fb2a6b80-c686-11ea-807b-a213b40db954.png">

Yes, although there are two equivalent possibilities: this one or with the beam having an opposite slope.  So a default could be chosen in such cases based on the automatically assigned stem direction of the first note.  This would usually be down except in this three-voice situation.  In this case the best position is for the first note to have a stem up to avoid the other notes at the same time without giving any note a large offset (just a little one for the start of the mix beam in this case).  But of course to have to figure that out computationally would be complicated.

---------------

This is an ambiguous case:

https://github.com/music-encoding/music-encoding/issues/391#issuecomment-276353995

<img width="718" alt="Screen Shot 2020-07-15 at 10 33 48 AM" src="https://user-images.githubusercontent.com/3487289/87576741-ae469500-c686-11ea-82f9-018227e60e9c.png">

Although the middle rendering is the most expected.  But adjusting the intervals there would be even more ambiguous cases.  It would be clear that the beam should go through the largest interval, but should the beam be inserted between other intervals, or jump above or below the rest of the notes?

One possibility is that for multi-note beams, only the first and last notes need to have stem directions.  For this case it would work to disambiguate the three possible mixed beam renderings: case 1: down-up, case 2: down-down and case: 3: up-down.  It would still be a bother to automatically calculate the stem directions of the intermediate notes (and there may be ambiguities).

**Comment by pe-ro** [comment]
The schematron rule on `<beam place="mixed">` exists to make certain that there are no ambiguities -- when `@place = "mixed"`, then stem directions must be provided on all the notes/chords under the beam.

A similar rule wasn't added to `<beamSpan>` because it's somewhat difficult to determine which notes/chords participant in / are affected by the beam.  Ideas on how to do this are appreciated.

**Comment by rettinghaus** [comment]
When all stem directions are provided, there are no ambiguities, and therefore no `beam@place` is needed. But it is needed, when you do not encode stem directions. I want to say: "try to place the beam above/below/between all notes". 
What else would be `beam@place` good for? Just to double-encode information?

**Comment by craigsapp** [comment]
The Musedata printing system has mixed beams, and they are controlled by the stem directions only, so this would be sufficient.

However, a dual encoding would have a purpose: It would be useful to explicitly state on the beam that it should be mixed, since this is a rare state for beam placement.  Someone could accidentally give the wrong stem directions on notes inside of the beam, causing an impossible mixed beam configuration to occur.  Also if you are beaming unbeamed notes together, you would have to be careful to either remove the individual contrary note stem directions or calculate new stem directions for the notes based on or to decide the beam placement.  And when removing that same beam, the individual notes may need to have stem directions added again (and these would have been lost when they were first beamed together).

**Comment by pe-ro** [comment]
I second what @craigsapp says about dual encoding -- sort of.  The encoding isn't redundant, but rather requires 2 parts.  `@place="mixed"` signals a beam containing notes/chords with opposing stem directions. Because ambiguity can arise in this case, stem direction is required on all the notes/chords participating in the beam.

The schematron rule can be enhanced to check for what @craigsapp refers to as "impossible configurations" of stem direction.

It is also possible that a mixed-direction beam could be drawn if all the notes/chords have `@stem.dir` with some "up" and others "down" even if `@place` is missing.  But, since `@stem.dir` is optional, it's harder to check for potential errors.  It would be up to the rendering software to check for and deal with any errors.

**Comment by bwbohl** [comment]
2023 Developer Workshop: We decided to make the schematron rule a warning for now. Moreover the rule should only apply when the notes are all on the same staff.
