### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#751]
In chapter 2.4.2. of the guidelines for MEI4 there are several images missing.

**Comment by bwbohl** [comment]
could you please double check on https://music-encoding.org/guidelines/dev/content/shared.html the dev version, I think it's fine there, isn't it?

**Comment by rettinghaus** [comment]
Yeah, obviously there are no _images_ missing, but the encoding snippets, as they have turned into `img` elements.

**Comment by bwbohl** [comment]
Ok, now I get what you mean… problem in reinstating this section was those images got lost on the way somewhere on v3 and I didn't manage to get the dev version ready for the 4.0.1 release, that's why these changes went into the dev version and consequently the code examples are only available there.

We could provide a patch for v4 that would issue a bug fix release, or wait for the next release, thoughts?

**Comment by ahankinson** [comment]
I believe this is fixed now?

**Comment by martha-thomae** [comment]
Not yet. It is fixed for the current version of the guidelines, but not for the development version.

**Comment by bwbohl** [comment]
It's fixed in development but not in v4 guidelines

**Comment by bwbohl** [comment]
should we fix it for v4 or just leave as is?

**Comment by rettinghaus** [comment]
@bwbohl This should definitely be fixed. But it's not done by simply copying over parts from dev version. And unfortunately it's broken in v3 too ([22.2.](https://music-encoding.org/guidelines/v3/content/usersymbols.html#usersymbolsModuleUses)).

**Comment by rettinghaus** [comment]
fixed with [fac90ff17303713fcaa35e468744197464203a25](https://github.com/rettinghaus/guidelines/commit/fac90ff17303713fcaa35e468744197464203a25)
