### ISSUE TITLE
Soft accents (and combinations)

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#768]
Is there a "native" way to encode the glyphs from https://w3c.github.io/smufl/latest/tables/articulation-supplement.html in MEI, or does one have to mix articulations with hairpins? 
Switching to `att.extSym` could solve it only in part, as you still not have an explicit semantic information.

**Comment by pe-ro** [comment]
Unfortunately, explicit semantics can never be recorded for everything one might encounter in an unbounded graphical information system like music notation.  An extension mechanism will always be required.

**Comment by craigsapp** [comment]
> explicit semantics can never be recorded for everything one might encounter in an unbounded graphical information system like music notation.

That is the design philosophy of SCORE :-)

This one is very common (with the rest of the examples seeming to be a generalization from this accent):

<img width="908" alt="Screen Shot 2021-02-08 at 8 48 33 AM" src="https://user-images.githubusercontent.com/3487289/107252761-8506a100-69ea-11eb-938f-21cdd2a1b6b8.png">

The others are a 20th-century invention, or are they present in older repertories?

It is a pain to encode `<>` accents as hairpins.  But it gets difficult because sometimes the accent behaves as an articulation, and other times like hairpins (i.e., if the music spacing does should not change the width of the "soft" accent, then it behaves like an articulation, and if it should stretch/compress when the music spacing changes, then it should be attached with `@tstamp` as hairpins.  But styles of the width of the "soft" accent in different editions are more variable than with regular accents.

One possible way to encode this class of articulation would be to allow children of a `<>` articulation, in which case the children articulations would be placed inside angle brackets.  Or there could be an `artic@soft="yes"` parameter, although how to encode the null soft articulation?  Perhaps as `<artic artic="soft" soft="true">` without `@artic`?.  Or as `<note artic="soft">` in the compressed case.

---------------------

A separate but related issue that would be extremely useful to implement is to allow a double hairpin form for `<hairpin>`.  Such as `<hairpin form="cres dim">` or `<hairpin form="cres-dim">`.  Such a hairpin would be exactly 1/2 a crescendo and 1/2 diminuendo during its tstamp length (but the midpoint would be independent of tstamps), and the two sub-hairpins would be required to be vertically aligned.   This would be extremely useful for dealing with the hybrid situation of something that behaves both as an accent and as a linked pair of hairpins.  To get equal lengths for the two hairpins and enforce them to be vertically aligned is nearly impossible otherwise.

**Comment by craigsapp** [comment]
Related to the sforzato issue (https://github.com/music-encoding/music-encoding/issues/608), it could be done with a `@glyph.num`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-02-08T10:55:20" version="3.2.0-dev-79dc742-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000453376412">
    <score xml:id="score-0000002025390885">
     <scoreDef xml:id="scoredef-0000000099252458" midi.bpm="400">
      <staffGrp xml:id="staffgrp-0000001150057781">
       <staffDef xml:id="staffdef-0000001841514441" n="1" lines="5">
        <clef xml:id="clef-0000000511878907" shape="G" line="2" />
        <meterSig xml:id="metersig-L2F1" count="4" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000001350590936" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L4F1" dur="1" oct="4" pname="c" accid.ges="n">
          <artic xml:id="artic-L4F1" artic="acc" glyph.num="#xED46" />
         </note>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

But such accents are not yet in VerovioText to allow rendering them:

<img width="250" alt="Screen Shot 2021-02-08 at 10 57 45 AM" src="https://user-images.githubusercontent.com/3487289/107268043-7fb25200-69fc-11eb-960b-034de3718d18.png">

**Comment by kepper** [comment]
The ODD Thursday group sees value in adding those values, but there seems to be some possible confusion about those additional values for potential users. It seems that the issues overlap with editorial questions (what is an accent, a long accent, a hairpin?), so this probably needs very thorough documentation – knowing that MEI cannot take decisions for editors, but only assist them in taking their own well-reasoned decisions.

**Comment by ahankinson** [comment]
@kepper, @rettinghaus can I move this to 'discussions'? Any specific changes can be opened as an issue or a PR referencing the discussion.
