### ISSUE TITLE
processable attacca

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#78]
_From [kep...@edirom.de](https://code.google.com/u/113787537940489926112/) on June 26, 2012 10:20:54_

Right now, attacca and the like can only be encoded using <dir>. Do we need a way to encode this information in a processable way?

_Original issue: http://code.google.com/p/music-encoding/issues/detail?id=78_

**Comment by ahankinson** [comment]
_From [andrew.hankinson](https://code.google.com/u/andrew.hankinson/) on October 17, 2012 07:52:52_

**Labels:** -Milestone-Release2013 Milestone-ReleaseNext

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on May 30, 2014 08:46:33_

**Labels:** -Milestone-ReleaseNext Milestone-ReleaseFuture

**Comment by pe-ro** [comment]
Would `@attacca` on `<mdiv>` be sufficient?  For example --
```
<mdiv n="1"/>
<mdiv n="2" attacca="true"/>
<mdiv n="3"/>
```
would indicate that movement 2 should begin immediately after the end of movement 1.

**Comment by craigsapp** [comment]
> would indicate that movement 2 should begin immediately after the end of movement 1.

A complication is that the *attaca* text is printed at the end of a section rather than the beginning.  I.e., "the next movement should begin immediately after this movement"  instead of "this movement should begin immediately after the end of the previous movement".

**Comment by pe-ro** [comment]
I'm thinking that the text at the end of mvt. 1 would be treated as a directive; i.e., `<dir>attacca</dir>`.  The `@attacca` attribute is for machine-performance purposes.

**Comment by pe-ro** [comment]
By separating the text and performance aspects, the text can say anything, e.g. `<dir>Next movement immediately following.  Go now!</dir>`.  Or there might be no text at all.

**Comment by craigsapp** [comment]
> I'm thinking that the text at the end of mvt. 1 would be treated as a directive; i.e., 
> `<dir>`attacca`</dir>`. The `@attacca` attribute is for machine-performance purposes.

OK, then it will not matter which mdiv has the `@attaca`.  

But another thought: would you ever want to link the `<dir>` on the previous mdiv to the @attaca?  That can't be done within an attribute.  The `<dir>` could be given `@type="attaca" @startid="#nextmdiv"`.

**Comment by pe-ro** [comment]
`@startid` is already used for another purpose, so the example could be --
```
<dir type="attaca" next="#nextmdiv">Attaca</dir>
```
or, preserving `@type` for other purposes --
```
<dir attaca="#nextmdiv">Attaca</dir>
```
or, realizing `<dir type="attaca">` as a separate element --
```
<attaca next="#nextmdiv">Attaca</attaca>
```
This last one allows for the requiring of `@next` and is probably the best option.

Just as it doesn't matter which `<mdiv>` has the `@attaca`, it doesn't really matter which `<mdiv>` has the `<dir>` or `<attaca>`.  😀 But putting it in the first one means it can be rendered where it appears.

**Comment by kepper** [comment]
I like this solution the best. The dir stays were it stands, it can be transcribed as written in the source, and the meaning can be derived from the attribute.

> 
> <dir attaca="#nextmdiv">Attaca</dir>

**Comment by pe-ro** [comment]
Ok, this is an easy fix.  But I'd like to hear other opinons -- @craigsapp? @lpugin?

**Comment by pe-ro** [comment]
Here's the ODD that implements `<attacca>` --
```
<classSpec ident="att.attacca.anl" module="MEI.analytical" type="atts" mode="add">
 <desc>Analytical domain attributes.</desc>
</classSpec>
<classSpec ident="att.attacca.ges" module="MEI.gestural" type="atts" mode="add">
 <desc>Gestural domain attributes.</desc>
</classSpec>
<classSpec ident="att.attacca.log" module="MEI.shared" type="atts" mode="add">
 <desc>Logical domain attributes.</desc>
 <classes>
  <memberOf key="att.controlEvent"/>
  <memberOf key="att.startEndId"/>
  <memberOf key="att.timestamp2.logical"/>
 </classes>
 <attList>
  <attDef ident="target" usage="opt">
   <desc>Indicates the next section or movement to be performed.</desc>
   <datatype>
    <rng:ref name="data.URI"/>
   </datatype>
   <constraintSpec ident="check_attaccaTarget" scheme="isoschematron">
    <constraint>
     <sch:rule context="mei:attacca/@target">
      <sch:assert role="warning" test="not(normalize-space(.) eq '')">@target attribute
       should have content.</sch:assert>
      <sch:assert role="warning"
       test="every $i in tokenize(., '\s+') satisfies substring($i,2)=//mei:*[local-name() 
       eq 'section' or local-name() eq 'mdiv']/@xml:id"
       >The value in @target should correspond to the @xml:id attribute of a section or
       mdiv element.</sch:assert>
     </sch:rule>
    </constraint>
   </constraintSpec>
  </attDef>
 </attList>
</classSpec>
<classSpec ident="att.attacca.vis" module="MEI.visual" type="atts" mode="add">
 <desc>Visual domain attributes.</desc>
 <classes>
  <memberOf key="att.extender"/>
  <memberOf key="att.placement"/>
  <memberOf key="att.verticalAlignment"/>
  <memberOf key="att.visualOffset"/>
  <memberOf key="att.visualOffset2.ho"/>
  <memberOf key="att.visualOffset2.to"/>
  <memberOf key="att.xy"/>
 </classes>
</classSpec>
<elementSpec ident="attacca" module="MEI.cmn" mode="add">
 <desc>An instruction to begin the next section or movement of a composition without
  pause.</desc>
 <classes>
  <memberOf key="att.common"/>
  <memberOf key="att.facsimile"/>
  <memberOf key="att.lang"/>
  <memberOf key="att.attacca.log"/>
  <memberOf key="att.attacca.vis"/>
  <memberOf key="att.attacca.ges"/>
  <memberOf key="att.attacca.anl"/>
  <memberOf key="model.controlEventLike.cmn"/>
 </classes>
 <content>
  <rng:zeroOrMore>
   <rng:choice>
    <rng:text/>
    <rng:ref name="model.textPhraseLike.limited"/>
    <rng:ref name="model.graphicPrimitiveLike"/>
    <rng:ref name="model.editLike"/>
    <rng:ref name="model.transcriptionLike"/>
   </rng:choice>
  </rng:zeroOrMore>
 </content>
 <constraintSpec ident="attacca_start-type_attributes_required" scheme="isoschematron">
  <constraint>
   <sch:rule context="mei:attacca[not(ancestor::mei:syllable)]">
    <sch:assert test="@startid or @tstamp or @tstamp.ges or @tstamp.real">Must have one of the
     attributes: startid, tstamp, tstamp.ges or tstamp.real.</sch:assert>
   </sch:rule>
  </constraint>
 </constraintSpec>
 <remarks>
  <p>As a specialized directive, <gi scheme="MEI">attacca</gi> is a control element. That is, it
   can be linked via its attributes to other events. The starting point of the attacca
   directive may be indicated by either a <att>startid</att>, <att>tstamp</att>,
    <att>tstamp.ges</att>, or <att>tstamp.real</att> attribute, while the ending point may be
   recorded by either a <att>dur</att>, <att>dur.ges</att>, <att>endid</att>, or
    <att>tstamp2</att> attribute. It is a semantic error not to specify a starting point
   attribute.</p>
 </remarks>
</elementSpec>
```
Making `<attacca>` a member of `model.controlEventLike` instead of `model.controlEventLike.cmn` would allow it to appear within `<staff>`.  In other words, within mensural notation.  For now, though, it's safe to assume that attacca only occurs in CMN.  Allowing it in mensural notation later will be a backward-compatible extension.  Allowing it in both repertoires now and restricting it to CMN later would be a backward-incompatible restriction.

Instead of `@next`, I added `@target`.  `@next` can still be used for generic purposes.  Also, `@target` is optional -- the assumption being that one should proceed to the next section or mdiv.  One only needs `@target` if that assumption is incorrect.

**Comment by lpugin** [comment]
If find it over the top to have a specific element for "attacca". So I would second the suggestions
```xml
<mdiv n="1"/>
<mdiv n="2" attacca="true"/>
<mdiv n="3"/>
```
or
```xml
<dir attaca="#nextmdiv">Attaca</dir>
```
with a preference for the first one

**Comment by kepper** [comment]
I agree. Having the attacca attribute on the mdiv simplifies processing, and the rendition in the score can be left to a simple dir. The only question I have is about the value of attacca: Does "true" mean that this movement is attacked, or the following one?

Ok, after having thought some more about this, I think I return to my earlier preference for dir. Otherwise, it'll cause a lot of complications when we have two sources, one stating an attacca, the other one not doing so. With dir, we can simply use app / rdg, but that wouldn't be possible on an attribute on mdiv. So while I still agree that a dedicated element seems to much, I vote for a dedicated (= more processable) attribute on dir – @attacca.

**Comment by rettinghaus** [comment]
@kepper What if an *attaca* is "implicit", i.e. not written as direction? Would you encode it as empty `<dir attaca="#nextmdiv" />`?

**Comment by pe-ro** [comment]
Since attacca is defined as an instruction to begin **"the next section or movement"** immediately, I think it's clear that `<mdiv attacca="true"/>` goes on the section/movement preceding the one to be "attacked".

But that's neither here nor there, as I think an element -- either `<dir>` or `<attacca>` is the better approach.

I don't understand why `<attacca>` is over the top.  There's precedent for it already; that is, `<fermata>`, which started life as `<dir type="fermata">`.  But the addition of `@form` and `@shape` to `<dir>` to describe a fermata's features (as opposed to other directives) dictated the creation of a new element.  I think the situation is analogous here -- it's better to create a new element than deal with the markup abuse that `dir/@attacca` would allow, even invite  Obviously, in the following --
```
<dir attacca="true">cuivre</dir>
```
the text direction and the presence of `@attacca` don't match.  Avoiding stuff like this is why it's necessary to create `<attacca>`.

That being said, I'm not opposed to also allowing `@attacca` on `<mdiv>` and `<section>`, especially if it is placed in the gestural domain.  I hope that would help make it clear that `@attacca` is intended for automated performance generation, not description of input documents or printed output.  There is a issue with this, as @craigsapp has pointed out, in that it's not possible to relate the `<attacca>` element and the `@attacca` attribute with each other, but I don't think it's a major problem.
