### ISSUE TITLE
Validation error in MEI.mensural.xml

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#789]
There are 4 validation errors within `att.duration.quality` connected to wrong encoding of `constraintSpec`. 
@martha-thomae please fix.

**Comment by musicEnfanthen** [comment]
@rettinghaus Please let's try to keep a friendly tone even if validation errors are indeed frustrating ;) 
Could you also please provide the actual error messages and a link to the constraintSpec of the section in question? Makes it much easier to chase down the issue.

@martha-thomae Could you please have a look if there is something that could be fixed from your side?

**Comment by rettinghaus** [comment]
I sincerely apologise if anyone has been offended, it wasn't supposed to sound rude. 

Here is the complete error report for `MEI.mensural.xml`:

> 174: element "constraintSpec" not allowed here; expected the element end-tag or element "exemplum", "listRef" or "remarks"
> 182: element "constraint" not allowed here; expected the element end-tag
> 190: element "constraintSpec" not allowed here; expected the element end-tag or element "exemplum", "listRef" or "remarks"
> 198: element "constraint" not allowed here; expected the element end-tag

**Comment by martha-thomae** [comment]
Hello.
No problem, thank you for acknowledging that, both @musicEnfanthen and @rettinghaus :)

Regarding the issue, thanks for submitting the error message, it will facilitate to track down this issue. I will be able to take a look at this in about two weeks (I have a very packed schedule right now). 

In general, I am not completely comfortable working with contraintSpecs. I have a very hard time writing them and testing them, and I have seen that they work a bit different when I define them in a customization file or in a source file—in one of them they are expected to be defined within the element they are affecting and in the other not, I cannot recall all the details right now. 

So, if anyone else wants to take a look at this, that would be good. If you feel comfortable, @rettinghaus, with making these changes yourself and a PR, that is fine too, I could evaluate them later as well. Otherwise, there is no problem and I will look into this in about two weeks and ask others for guidance and evaluation.

**Comment by rettinghaus** [comment]
@martha-thomae Any updates on this? My attempts to find a fix failed so far.
