### ISSUE TITLE
Remove <scoreFormat> from <physDesc>

### ISSUE THREAD

**Issue by KristinaRichts** [music-encoding/music-encoding#803]
The value of scoreFormat is not describing a physical entity. Because of this scoreFormat shouldn’t be available at physDesc anymore. The occurrence in the mei.frbr expression is still fine. The metadata-ig discussed this issue and decided to make this suggestion.

**Comment by kepper** [comment]
At ODD Friday, there was consensus that it makes no sense to have `<scoreFormat>` within `<physDesc>`. However, it should be possible to have that kind of information even without the FRBR module, so not only within `<expression>`.  It would be good to think about this use-case, and luckily, @riedde volunteered 👍  :-)

**Comment by pe-ro** [comment]
This discussion has already taken place several times.  When the FRBR module isn't used, the next best place for `<scoreFormat>`, however it may annoy the FRBR zealots, is `<physDesc>`.

**Comment by riedde** [comment]
I agree that `<scoreFormat>` has to be available also when not using the FRBR module, but I don't agree that `<physDesc>` is the best place for that. In MEI 4.1.0 `<physDesc` is only contained by `<item>` or `<manifestation>` and both elements are provided by the MEI.frbr module. Maybe I'm missing something but from my view it would be interesting to use  `<physDesc>` without MEI.frbr. I noticed that in MEI 3.0.0 `<physDesc>` was allowed in `<source>` which is still available in the header (independent from MEI.frbr), but in MEI 4.1.0. `<source>` may not contain `<physDesc>`.
However, I would be fine if `<scoreFormat>` is availabe in `<source>` or `<manifestation>` or `<item>` as some way of classification, but for me it is till no physical description. My suggestion is to set the element one level high, out of `<physDesc>`and also make it available in `<source>` that there is no constraint to use MEI.frbr

**Comment by pe-ro** [comment]
I suggest having a look at https://www.loc.gov/marc/bibliographic/bd3xx.html where score format is very clearly grouped with other kinds of physical description.  https://www.loc.gov/marc/bibliographic/bd348.html describes "Format of Notated Music" as "[t]he musical or **physical layout** (emphasis mine) of the content of a resource that is presented in the form of musical notation."

Putting `<scoreFormat>` in `<manifestation>` and/or `<item>` doesn't resolve the issue of how to record this info when the FRBR module isn't available, since both of these are only available when FRBR is turned on.  Allowing it in `<source>` subverts the intention of this element in v. 4.1.0; that is, to record only the high-level bibliographic details necessary to locate the source, not complete description.  Stated another way, if `<scoreFormat>` is allowed in `<source>`, then all the other details that were intentionally removed from `<source>` in v. 4 would have to be put back in as well and setting off a highly undesirable chain of discussions about the use of `<source>`.

So, while it may not be the optimal solution, allowing `<physDesc>` to contain `<scoreFormat>` follows tradition and minimizes other problems.

**Comment by riedde** [comment]
Okay, minimizing other problems is one thing i always prefer, but leaving it as it is does also not solve the problem that `<scoreFormat>` can not be used without MEI.frbr ...
Thank you fore the links, I also had a look there. It seems to me that this is some kind of clash of discipline/view/perspective if score format is physical or not.

**Comment by pe-ro** [comment]
I apologize -- I just realized that my argument with respect to allowing physical description without FRBR is based on v. 3.  

Still, I don't recommend removing `<scoreFormat>` from `<physDesc>` since the latter functions as a container for various kinds of data, not all of which are strictly descriptive of physical form.  For example, `<physDesc>` also allows accMat, captureMode, exhibHist, plateNum, titlePage, treatHist, and treatSched, which technically aren't descriptive of the physical qualities of the item.

**Comment by pe-ro** [comment]
Sometimes it's best to let sleeping dogs lie. :-)

**Comment by ahankinson** [comment]
Where did we land with this issue? Can it be closed with a "won't fix"?

**Comment by riedde** [comment]
I would like to keep this issue open until the next metadata-ig meeting (in june). After that I can tag an maybe close this issue.

**Comment by ahankinson** [comment]
OK

**Comment by riedde** [comment]
The metadata-ig is informed about this discussion and is fine if we close this issue with the tag "won't fix". We decided to take back this proposal and to keep `<scoreFormat>` as it occurs because of compatibility reasons. Further we are going to extend the description in the guidelines in section _3. Metadata in MEI_ to articulate the different ways of use/meaning.
@ahankinson would you close this issue, please? I don't have the user rights to do that.
