### ISSUE TITLE
Automatic search for no child elements?

### ISSUE THREAD

**Issue by KristinaRichts** [music-encoding/music-encoding#805]
In the metadata part of the guidelines, there are some elements where it says that they may not have child elements (for example: condition). In fact, child elements are allowed. Is there a way to automatically detect these elements?

**Comment by kepper** [comment]
This is because [<condition>](https://music-encoding.org/guidelines/dev/elements/condition.html) has a `macro group` (here: `macro.struc-unstrucContent`) as sole content, which isn't processed properly. I believe I've seen this error in a separate ticket already, but haven't investigated yet. I'll try to fix asap.

**Comment by kepper** [comment]
This issue was a duplicate of https://github.com/music-encoding/guidelines/issues/172. Both should be fixed now. Thanks to @pe-ro  and @KristinaRichts for reporting the issue 👍
