### ISSUE TITLE
MIDINAMES error in MEI 4/5 RelaxNGs

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#812]
Most values from the [data.MIDINAMES](https://music-encoding.org/guidelines/v4/data-types/data.midinames.html) range have lost their underscores in the resulting [rng](https://music-encoding.org/schema/4.0.0/mei-all.rng). Looks like the `altIdent` values slipped into there.
Same applies for [development version](https://music-encoding.org/schema/dev/mei-all.rng).

**Comment by kepper** [comment]
Would be helpful to have an example for the problem, and I'll try to look into this…

**Comment by ahankinson** [comment]
For example:

In the MIDINAMES list we have:

`Choir_Aahs  Program #52.`

But in the RNG we have:

```xml
<value>Choir Aahs</value>
<a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0">Program #52.</a:documentation>
```

**Comment by kepper** [comment]
After some more investigation: This is coming from the TEI Stylesheets we use. As already suspected by @rettinghaus, it is triggered on the presence of an `<altIdent>` element. If such an element is available, it's content is preferred over the `@ident` attribute on `<valItem>`. 

Here is our current definition (dev, but similar to v4):
```xml
<valItem ident="Choir_Aahs">
  <altIdent>Choir Aahs</altIdent>
  <desc>Program #52.</desc>
</valItem>
```

In version 3.0.0, the RNG was correct, but our ODD was a little simpler:
```xml
<valItem ident="Choir_Aahs">
  <desc>Program #52.</desc>
</valItem>
```

Due to some code reorganisations back then, I can trace the change back to 2017 only, without a proper commit for this very change. Eventually, this doesn't matter anyway, as we need a solution for this. I believe the original intention was to give the value in `<altIdent>` as human-readable version for use in Oxygen and other apps (like editor.verovio.org). However, in RNG there are no separate fields for this – whatever we want to have as value in the files will have to be the same as what tools will display as guidance. As spaces may lead to problems (not necessarily here, but perhaps in other data types that allow multiple values), I think reverting to underscores in our best bet. Luckily, this would also be the simplest fix – just remove all `<altIdent>` elements from `<valItem>`s… Opinions?

**Comment by musicEnfanthen** [comment]
Thanks for investigating, @kepper. Following your hints, I found this long-standing discussion about `<altIdent>` in the TEI, revealing some problematic status (of the use and allowed locations) of `<altIdent>` there. Maybe it is helpful for context: https://github.com/TEIC/TEI/issues/2049. 

Is there any mechanism to change preference order of `@ident` vs. `<altIdent>`.

Just for reference:  The `<altIdent>` values for MIDINAMES were probably introduced in this commit: https://github.com/music-encoding/music-encoding/commit/e16582545c484c7d8b8efada4cf67ff1bc8e3f1d .

**Comment by kepper** [comment]
Thanks @musicEnfanthen. If I get those TEI discussions right, there's no proposed change for `valItem/altIdent`. However, even a change on that end wouldn't give more options in the generated RNG. There, we only have two fields to fill: 

```xml
<value>Choir Aahs</value>
<a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0">Program #52.</a:documentation>
```

The content of `<value>`, and the content of `<a:documentation>`. Whatever we have in our `<desc>` will go into the `<a:documentation>`, and then it's either `@ident` or (preferred when available) `<altIdent>` that gets mapped to `<value>`. In [our own documentation](https://music-encoding.org/guidelines/dev/data-types/data.MIDINAMES.html), which is _not_ generated through the TEI stylesheets, the problem doesn't surface (or at least it's a different problem…). 

<img width="294" alt="grafik" src="https://user-images.githubusercontent.com/2078563/151655017-d1271bd2-cf7c-44b8-9a1a-ebca0278fb14.png">

Here, we only show `@ident` and `<desc>`, but never `<altIdent>` (so we're not taking up why we did this in the first place…). While we can show `<desc>` (or anything) in our own documentation, we can only surface one single field to the user documentation available in tools like Oxygen. At this point, I would suggest to just move the contents of `<altIdent>` into the sibling `<desc>`. The human-readable version won't be available in Oxygen anymore, but we can have that only if it's also used as value in the attribute, which causes technical issues. Additional documentation will only be available through our documentation then, where we're currently not showing this at all. To me, this sounds like hitting two flies with one flap…

**Comment by rettinghaus** [comment]
I'm in favour of dropping `<altIdent>`. It has no additional benefit as to present the "true" name from the General MIDI instrument names list. I think that those underscores obscure the original name.
In #902 I tried to make it clear that MEI is not simply copying the names.

**Comment by craigsapp** [comment]
General MIDI (Level 1) instrument list is fixed at 128 instruments plus percussion instruments (which are handled separately in General MIDI).

One thought is that there are synthesizers that can play more than 128 instruments.  General-MIDI compliant synthesizers may have more than 128 instruments, but these instruments are not in any industry-standard order (or even in a manufacturer specific order across different synthesizers), and often have fanciful or perhaps proprietary names. 

Also there are non-General-MIDI Synthesizers, such as a synthesizer that specializes in one instrument, such as organ, with multiple organ stops for instruments.   In such cases the MIDI names would be useless (so perhaps an Authority needs to be given for MIDI instrument names in the general case since they may not match that of the synthesizer playing back the MEI score).   Also the MIDI names are more of a byproduct of the standard rather than part of the General MIDI standard itself.  For example the first instrument is "Acoustic Piano"

`<altIdent>` could perhaps be used for such non-standard timbre names.   A simple example could be for a part that should be played on the [serpent](https://en.wikipedia.org/wiki/Serpent_(instrument)).  There is no standard General MIDI instrument for the Serpent, so instead the trombone (or other brass instrument) would be used as a substitute in General MIDI.  If someone had a synthesizer that had a serpent timbre, then the `altIdent` could be used to override the substitution timbre.

So a possible use of altIdent:

```xml
<valItem ident="Trombone">
  <altIdent>Serpent</altIdent>
  <desc>Program #72.</desc>
</valItem>
```

If "Serpent" were used as the name, it would be re-routed to the General MIDI  timbre for Trombone.  Alternatively, if there were a serpent timber on the synthesizer, it could be used instead of remapping to General MIDI.  To select instruments beyond the General MIDI list, you use the "Bank select" continuous controller:

<img width="765" alt="Screen Shot 2022-01-29 at 9 35 54 AM" src="https://user-images.githubusercontent.com/3487289/151671243-e3e52cb0-da3e-4447-b40b-ea9dcfe56f80.png">

In theory there can be 16384 banks of 128 instruments, for a total possible number of instruments at 2097152.  Most synthesizers have 10 or fewer banks, and only use the "coarse bank select" which is continuous controller #0.    To select the General MIDI bank, here are the MIDI bytes (hex):

```
B0 00 00
```

To select the second bank:

```
B0 00 01
```

The first number is the MIDI command (B = continuous controllers, 0 = channel 1.  The second number is which controllers (Bank select, coarse), and the third number is which controller (0 = first bank, 1 = second bank).   In theory there could be more than 128 banks on a synthesizer, and then the "bank select, fine" parameter would be used:

Select the first bank and first subbank (General MIDI):

```
B0 00 00
B0 20 00
```

Then it is ambiguous what the "second" bank would be, either:

```
B0 00 00
B0 20 01
```

or

```
B0 00 01
B0 20 00
```

-------------------------

In theory the instrument numbers could be allowed above 127, and if higher than 127, then that would indicate a higher bank.  For example, in such a representation system, instrument 128 (where the first instrument is 0), would be the first instrument in the second bank.  When converting to MIDI, there would be a controller message to select the bank and then a patch change to select the instrument in that bank:

```
B0 00 01
C0 00
```

This is complicated since General MIDI does not specify how to enumerate the banks, so in theory one of these two configurations may be necessary if the synthesizer uses two numbers to select a bank:

```
B0 00 01
B0 20 00
C0 00
```

```
B0 00 00
B0 20 01
C0 00
```

**Comment by ahankinson** [comment]
Given that description is for human-readable documentation, what about:

```xml
<value>Choir_Aahs</value>
<a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0">Choir Aahs, Program #52.</a:documentation>
```

**Comment by pe-ro** [comment]
Andrew's suggestion is simple, just like me. 😄 I like it.
