### ISSUE TITLE
Request to make divLine a child of layer

### ISSUE THREAD

**Issue by yinanazhou** [music-encoding/music-encoding#861]
We noticed that right now `divLine` does not have any possible parents (the "contained by" part is empty in this link: https://music-encoding.org/guidelines/dev/elements/divLine.html). To encode our chant pieces, we need to encode `divLine` somewhere in the MEI encoding.

The reasons to make `divLine` a child of `layer` are as follows:
1. In this way, `divLine` will be in the stream of notes, which are also encoded in `layer`.
2. `divine` acts like barLine, which is also a child of `layer`. The difference is that `divLine` separates chants, instead of separating sections of a piece like `barLine`.

In pull request #860 , we added the module `model.layerPart.neumes` to `divline` in `MEI.neumes.xml`. This is because `divLine` appears in the neume notation.

If there is a better way to do this, please let us know. Thank you!

**Comment by ahankinson** [comment]
Thanks @yinanazhou ! Nice catch -- indeed this element doesn't seem to be able to be included anywhere!

However, I'm wondering if a better solution is to make it part of `model.eventLike.neumes` instead. My reasoning is based on [page 13 of the Liber Usualis](http://liber.simssa.ca/#p=13&z=2).

In this the divisions are identified more as 'pauses' rather than bar lines, which means they are probably more akin to rests or accents than barlines. In other words, like rests or accents, they have an effect on the musical performance of the work, while barlines are unperformed structural indicators.

You will also notice in the example on the Liber Usualis page that divisions may occur within a syllable -- the notes on "Kyrie" are broken by two small divisions. This means that you may want a `divLine` to occur within a syllable, which the `model.eventLike.neumes` model would allow.

What are your thoughts?

**Comment by yinanazhou** [comment]
Thank you for your quick reply. I agree with you. I will change to the `model.eventLike.neumes` model and validate the new schema next week.

**Comment by bwbohl** [comment]
fixed in #860
