### ISSUE TITLE
Clarify <exhibHist> vs <eventList>

### ISSUE THREAD

**Issue by doerners** [music-encoding/music-encoding#879]
The element description of [`<exhibHist>`](https://music-encoding.org/guidelines/dev/elements/exhibHist.html) states that it encodes:

> A record of public exhibitions, including dates, venues, etc.

The element is only allowed within `<physDesc>`, although I would not consider an exhibition of an item an inherent physical property of a resource. Additionally, the element does not allow to record several exhibition events via structured descriptions, however, it is allowed to repeat the element itself.

My questions are: 

- What is the actual purpose of the element?  – Maybe I misunderstand why it is modelled in this specific way. This might be, because it is not clear on which element from the EAD standard it has been modelled (see [issue 878](#878)).
- Could the information be encoded better with the `<event>` element and do we need `<exhibHist>` at all, i.e. should we drop it?

**Comment by ahankinson** [comment]
The `<exhibHist>` is meant to indicate the times when the physical item was put on exhibit, so I think it is part of the physical description.

I'm not sure, but I think `event`/`eventList` are meant for marking-up text data (like a list of performances in a printed book), and not as structural metadata. It would be good to check and clarify this.

**Comment by rettinghaus** [comment]
I would argue that an *exhibition history* is nothing that belongs to a physical description directly but more to the history of locations. 
In `physLoc` we have a `history` element, which holds an `eventList`:

```xml
<physLoc>
    <history>
       <eventList label="list of exhibitions" class="exhibition">
          <event isodate="2021-12-20">
             <desc>Publicly shown in a library near you</desc>
             <date>2021-12-20</date>
          </event>
       </eventList>
    </history>
 </physLoc>
```

`history` can also be a direct child of manifestation.
So `event`/`eventList` seems to be able to hold structured information, way better than `exhibHist`:
```xml
<exhibHist>
    <p>This item will be on display at 20 Dec. 2021</p>
 </exhibHist>
```

**Comment by ahankinson** [comment]
Often with exhibits there is a tag or a description for the public that accompanies the object, so it's not just about the location; it's also what was said about it.

Not saying either of your comments are not appropriate! Just that it might _also_ need to contain something like:

`ff. 200v/201r: Here you can see the use of fine miniscule hand on the left page, transitioning to a later script style on the facing folio.`

**Comment by pe-ro** [comment]
`<exhibHist>` is based on the MARC 585 field (https://www.loc.gov/marc/bibliographic/bd585.html), not EAD.  Sorry for the error.  As Andrew alluded to, `<physDesc>` is a container for several kinds of information related to, but not absolutely limited to, a description of a physical object.  I think `<exhibHist>` fits the definition of the "handling" of an object allowed by the short definition of `<physDesc>`.

Whether to encode this information in physDesc/exhibHist or in physLoc/history/eventList is a matter of personal/project preference and structure of the document, record, etc. which the MEI encoding may be a transcription of.  It should be remembered that MEI is a _**document**_ encoding system.  For example, the header info may be the result of transcoding existing catalog record(s),  which may treat exhibition history as physical description _**or**_ as an event related to physical location.  A single record may also use _**both**_ of these approaches.  It's best not to over-simplify the existing world as we model it.

**Comment by pe-ro** [comment]
Andrew is also correct to point out that it may be necessary to record not just the fact that something was exhibited, but also information about why the object was shown, what was significant about the display, etc.

**Comment by doerners** [comment]
Thank you @ahankinson, @rettinghaus and @pe-ro for your comments!

What is said for the MARC 585 field makes much more sense to me in this context than somewhat related elements I could find within EAD, thank you @pe-ro for this insight! I propose that the remark for `<exhibHist>` should be updated accordingly. 

MARC calls this field 'Exhibitions Note'. From what I understood from your comments regarding the purpose of `<exhibHist>`, I think that this is a better or less confusing terminology than 'exhibition history'. We might should discuss a renaming of the element. I agree that, as @pe-ro pointed out, the element 

>fits the definition of the "handling" of an object

However, I would imagine that it might be best practice to encode exhibition events within `<physLoc>` and then link the event with any additional note that might be encoded within `<exhibHist>`.

**Comment by ahankinson** [comment]
I suspect `<physLoc>` is intended for use when an item shifts institutions, and not the physical location where the item lives _within_ the institution. You might use it to record shifts in shelfmark, though.

> Groups information about the current physical location of a bibliographic item, such as the repository in which it is located and its shelf mark(s), and its previous locations.

Objects can be exhibited without actually leaving the physical space where they are located. They change their shelfmark when they move institutions (usually) or even move collections within the same institution (e.g., when a book moves from a music library to a special collections library) but not if they're just going to a different room to be shown to the public. This is my presumption when reading between the lines on what is allowed within `<physLoc>` -- provenance, identifier, repository.

**Comment by doerners** [comment]
Since `<physLoc>` is modelled after EAD I checked out what is said about the element there, EAD states:

> <physloc> is used to identify where the described materials are stored, and it may contain such information as the name or number of the building, room, stack, shelf, etc., where the materials may be stored and retrieved. <physloc> can be used to designate onsite and offsite storage locations.

So I understand that it can be used to designate the exact location of an item for e.g. the purpose of retrieval. However, it probably depend on the granularity one wants for the description. If I just want to designate that a library holds an item without giving the exact location I probably need a less detailed description.

On another note, since `<history>` is allowed as a direct child of `<item>` one might encode any exhibition events there. However, if I think about it I don't really see why any information about such exhibitions shouldn't be bundled within an encoding. From the perspective that an additional (exhibition) note only existed, because of the specific context of that exhibition and not as an inherent property of the item itself, I would argue that the encoding could reflect that by allocating such a note within the event.

**Comment by bwbohl** [comment]
@doerners good spotting, again!

I was completely with you and the notions of streamlining the encoding model (moving or removing exhibHist) until thankfully @pe-ro brought the "document encoding" and with that a potential retro-digitization back to my mind!
(This brings some issues back to my mind that I had with some strict order of elements in the header, but that's another issue).

I think you could file a PR with improvements of the element descriptions (e.g. do descriptions of `physLoc` and `exhibHist` contain the reference to EAD and MARC respectively? Maybe even contain a link to the appropriate passage?)

But – although I like simplification of MEI – for consistency's and backwards-compatibility's sake, I deem it somewhat problematic to rename `exhibHist` because using names of external standards can become a problem when those standards evolve or are surpassed by another standard and e.g. a filed/element, although having the same definition, might have a different name. Such cases would consequently require us to update our "standard" just to keep it consistent or have different elements for the same purpose just to ease the harmonisation with different external standards.

**Comment by doerners** [comment]
Thank you @bwbohl!

Could you elaborate why renaming the element would be a bad idea? 
To me this is not clear, maybe because I just dealt too little with that matter so that I can't see the whole picture here. From what I read the element has already been renamed from `exhibithist` to `exhibHist` during the evolvement from MEI 2010 to MEI 2012, see e.g. [here](https://github.com/peterstadler/MEI-2010to2012/blob/master/MEI-2010to2012.xsl) and [here](https://music-encoding.org/downloads/MEI_TagLibrary_2010-05.pdf). Thus I don't quite understand the backwards-compatibility argument. My imagination would be that in order to converse from an older version of MEI to a newer one the mapping could be realised by a XSLT. I'm not quite sure if a backwards conversion has ever been done or is needed at all. To my knowledge the MEI Garage also doesn't offer tools for converting from a newer MEI version to an older one.

I also took some time to think a little bit more about the comments that have been presented within this issue. My impression (somewhat still) is that `exhibHist` is misplaced within `physDesc`. My arguments for that are:

- If we take MARC as the authority here, we see that the [MARC 5XX fields](https://www.loc.gov/marc/bibliographic/bd5xx.html) are _note fields_ where as the [MARC 3XX fields](https://www.loc.gov/marc/bibliographic/bd3xx.html) are _physical description fields_. So I would say that in the MARC universe the _Exhibition's Note_ ([MARC 585 field](https://www.loc.gov/marc/bibliographic/bd585.html)) is not considered a physical description.
- If we consider `exhibHist` to contain _information about why the object was shown, what was significant about the display, etc._ this information only exists because of the special circumstance of the exhibition, not independently of it – I thus wouldn't consider it an inherent "thing" of the item itself.
- I would consider it to be part of the _(physical) handling_ of an item in the case an exhibition note was stuck to the item itself and thus somewhat becoming a physical part of it, however, if it is only attached to e.g. a display box where the item is stored for display I would consider it physically separated from the item. If the latter is the case I wouldn't consider it fitting the definition for what `physDesc` is supposed to contain.

Personally I think that the information could better be encoded the way @rettinghaus proposed in his [comment](https://github.com/music-encoding/music-encoding/issues/879#issuecomment-966206994). However, since there is a great community behind MEI I propose to ask for usage examples of `exhibHist`.

**Comment by ahankinson** [comment]
I wouldn't read too much into the labelling of the MARC 3XX or 5XX sections between a 'note' and a 'physical description'. You'll notice that there are things like "Binding notes" and "Custodial history notes" in the 5XX, and those are very definitely physical descriptions.

The 3XX fields are primarily **structured** physical description, while the notes fields are more for lengthy prose-style description.

**Comment by bwbohl** [comment]
2022-01-28 ODD meeting: taking this from the way MEI was developed during the last years would be to keep `exhibHist` as it is but provide a more verbose documentation also illustrating possibilities to encode such events in history/eventList a a more machine-readable alternative.
Please prepare a pull request.

**Comment by riedde** [comment]
I think the idea upcoming in yesterdays meeting not to delete `<exhibHist>` but to provide an extended documentation instead could be the way to go.
While the metadata-ig tries to update the guidelines chapter 3 and to fill all the (big) gaps in documentation elements like `<exhibHist>` appear. Thank you all for helping questioning the meaning! But there is still one thing that is unsatisfactory, in my eyes.
I propose to move `<exhibHist>`, e.g. to `<physLoc>`, because it is  more a history/timeline description of physical locations than a description of the material itself. Maybe this step would invite to check the definition of `<physDesc>` and `<physLoc>`, if they need to be made a bit more precise.

**Comment by doerners** [comment]
If the community decides to keep `<exhibHist>` I fully support the proposal of @riedde to move the element. 

From what I grasped from yesterdays discussion during the ODD meeting, there seems to be cases where it might be necessary or favoured to write prose instead of encoding certain information in a (purely) machine-readable way. In that light one could argue that `<exhibHist>` is overly specific for providing an element to store 'note-like' information. Wouldn't it be sensible to have a more generic element that is allowed in different places to enable such encoding practice? I'm not sure if the `<annot>` element might be the one to use in that case.

**Comment by ahankinson** [comment]
I would actually be in favour of deprecating `<exhibHist>` for `<history>` lists, since they're fundamentally more expressive and, as we've seen, can capture both machine-readable data and prose. However, I also think it's important we have a clear model of what we're replacing it with. As I mentioned before, the one advantage that `<exhibHist>` has over a generic list is that it has the semantics of what it is built into the name, and those semantics are fixed as part of the specification. It is a "strongly typed", to borrow a term from programming.

If we use an open value attribute, such as `@class` then we lose the fixed semantics. If someone puts `class="exhibit"` and someone else puts `class="exhibition"` then we lose standardization and interoperability. MEI has historically been very conservative about standardizing the values of `@class` and `@type` -- we keep those open so that we have the ability to have flexible "local" encodings, but if an attribute is recognized as being worthy of standardization we move that to a fixed, named, and specific attribute.

To borrow from @rettinghaus's example, perhaps the change might look something like:

```xml
<history>
       <eventList label="conservation interventions">
          <event isodate="1995-01-12" eventType="conservation">
             <desc>Repaired binding</desc>
             <date>1995-01-12</date>
             <p>The front cover had become detached from the spine of the book due to use. This was fixed by applying 
             tape to re-join the cover to the spine, and a new leaf was inserted in the front and back.</p>
          </event>
          <event isodate="2005-11-22" eventType="conservation">
             <desc>New covers</desc>
             <date>2005-11-22</date>
            <p>The item was completely rebound with new front and rear boards.</p>
          </event>
       </eventList>
       <eventList label="list of exhibitions">
          <event isodate="2012-12-20" eventType="exhibition">
             <desc>Exhibition on book binding techniques.</desc>
             <date>2021-12-20</date>
             <p>Item was shown closed with the following caption: ...</p>
          </event>
          <event isodate="2019-04-20" eventType="exhibition">
             <desc>Part of an exhibition on music and culture.</desc>
             <date>2021-12-20</date>
             <p>Item was shown with the opening of ff. 2r and 3v, and the following caption: ...</p>
          </event>
       </eventList>
</history>
```

The new `@eventType` attribute would contain a semi-closed list of possible and probable events, and these would always be limited to the **physical** properties of the item (i.e., the `eventType` wouldn't have things like "composed" or "new edition" since these are not physical properties of the item.)

As for moving it from the physical description -- I'm not so sure. An exhibition of an item is necessarily physical, and in FRBR terms, the exhibition will always be tied to the `item` level. If we expand the nature of this to all possible events in all possible dimensions of an object, then we would have a hard time trying to enumerate them all.

**Comment by doerners** [comment]
Thank you @ahankinson! I'm totally in favour of deprecating `<exhibHist>` as well :)

I also totally understand your point that having semantics built into the name of – in this case – `<exhibHist>` can be advantageous. However, I feel it is somewhat limited since it only applies to a specific form of event. Thus, I personally really like the idea of introducing a new `@eventType` attribute although I would advise against it containing a semi-closed list of event types but rather to rely on a controlled vocabulary to derive possible values. I was thinking that the [LIDO](http://terminology-view.lido-schema.org/vocnet/?uriVocItem=http://terminology.lido-schema.org/&startNode=lido00409&lang=en&d=n&vocInfo=y) terminology could suffice here, as it knows [exhibitions](http://terminology.lido-schema.org/lido00225) among other events/event activities.
My main argument against limiting the possible values of `@eventType` to physical properties would be that `<history>` – and thus subsequently `<eventList>` and `<event>` – is allowed on all four levels of the WEMI-hierarchy and additionally as a child of `<physLoc>`. So if one wants to encode an event on the work or expression level they couldn't make use of `@eventType` if it only contains/would only allow values regarding physical properties. 

If the community can agree to deprecate `<exhibHist>` we probably wouldn't have to think about moving it. However, I understood that @riedde proposed to move it to `<physLoc>` which is tied to the `item` level, thus I don't really see a problem with the underlying semantics – please correct me if I'm wrong.

**Comment by kepper** [comment]
I'm not convinced to deprecate `<exhibHist>` – it just serves a different purpose. Consider you have an essay that introduces the exhibition history of a manuscript. That essay may not be an itemized list. You probably would not expect this to be machine-readable, but I think it's still a good idea to be able to keep that in MEI. All the suggested improvements on `<eventList>`s make sense, but to me, they don't justify to take away `<exhibHist>` – as long as we have good documentation explaining the different purposes they have…

**Comment by ahankinson** [comment]
An additional data point: The TEI msDesc guidelines use the `<custodialHist>` element for this purpose:

https://msdesc.github.io/consolidated-tei-schema/msdesc.html#TEI.custodialHist

**Comment by doerners** [comment]
I don't really see why one couldn't store the text of an essay about the exhibition history of a manuscript within one or more `<p>` elements inside of an `<event>`. Furthermore I think to keep `<exhibHist>` would favour the encoding of exhibitions  over all other possible types of historical events. What if I want to encode an essay about the preservation history of a manuscript? It would probably not make sense to encode that in `<exhibHist>` because the semantics don't fit. That was what I meant when stating that `<exhibHist>` is overly specific.

**Comment by ahankinson** [comment]
@doerners -- There is `<treatHist>` for that purpose: https://music-encoding.org/guidelines/v3/elements/treathist.html

**Comment by doerners** [comment]
I admit that was a bad example on my part. However, `<treatHist>` does neither list `<p>` nor `<desc>` under _May contain_. So how should an essay or prose be best encoded there?

**Comment by ahankinson** [comment]
I didn't say it was a *good* solution :-D It looks like that would indeed need some fixing to be fit for that purpose.

**Comment by kepper** [comment]
`<treatHist>` uses https://music-encoding.org/guidelines/dev/macro-groups/macro.struc-unstrucContent.html, which means it's either zero or more `<head>`s, followed by zero or more `<p>`, or it allows dropping in content directly (no paragraphs).

**Comment by kepper** [comment]
In other words, it does `<p>`. And yes, it could be improved with intermediate headings ;-)

**Comment by ahankinson** [comment]
Unless I'm missing something blindingly obvious, `<p>` isn't allowed, or at least, it isn't listed in the allowed elements.

Allowing plain text means that you can effectively only have a single paragraph for a given header, which is not sufficient for encoding longer text descriptions.

**Comment by kepper** [comment]
<img width="1249" alt="Bildschirmfoto 2022-02-01 um 12 23 46" src="https://user-images.githubusercontent.com/2078563/151960203-2c997e1b-5344-4249-a864-46d83cddedb5.png">

**Comment by kepper** [comment]
same for `<exhibHist>`…

**Comment by doerners** [comment]
@ahankinson I think be both got confused with the MEI version. You posted the link of MEI 3 while @kepper is referring to the current dev version of MEI :)

**Comment by ahankinson** [comment]
Whoops! You're right. Not sure how *that* happened. 😮‍💨 _(Narrator: It turns out he was missing something blindingly obvious.)_

**Comment by kepper** [comment]
I'm not saying either that it's perfect, but it's not as bad as it looks like – but we just jointly spotted that the docs for v4 have an error (not to speak of v3, but this was one of the improvements for v4…), because it's actually not listed there (but can be derived from looking at the ODD at the bottom). But that is a spearate issue ;-)

**Comment by rettinghaus** [comment]
@kepper why are you still not convinced? Or better said: what would it need to convince you to deprecate this overly specific element?

**Comment by kepper** [comment]
I just believe that it covers a different use case than any _*List_ does. In a way, it is syntactic sugar, but to `<history>`. While the _*Hist_ elements are prose / human-focussed, _*List_ __to me__ seem database / machine-focussed. Of course there are ways to use both of them in different ways, but this is my perception. I totally agree this needs clarification, but I don't see how one could replace the other without causing friction losses. Just because _someone_ doesn't need it this doesn't mean that no one needs it. I'm not completely opposed to deprecating things (including this), but this feels like a major conceptual overhaul that requires considering many more elements than just `<exhibHist>`… So what it needs to convince me? One or two multi-day in-person meetings of the Metadata IG that result in a well-thought proposal for revising more or less the complete header… (and this is no claim that the current state would be ideal)

**Comment by doerners** [comment]
We discussed this matter in the metadata IG today which yielded the following proposal, we see as an acceptable compromise between keeping the element as-is and deprecating it:

re-modell `<exhibHist>` (and in fact `<treatHist>` and `<treatShed>` as well, since these are modelled the same way) exactly the way `<provenance>` is modelled.

This would allow to encode extensive prose on one hand and structured or more machine-readable information on the other, since it would make it a child of `<history>` and thus allow to choose between one or more `<eventList>` elements or one or more `<p>`elements to be contained by it. As child elements to `<history>` they would be allowed within `<item>` and `<physLoc>`. This would resolve the argument that `<exhibHist>` doesn't seem sensible within `<physDesc>`.

What is debatable at this point and one thing that wasn't discussed is the fact that `<treatHist>` is indeed sensible within `<physDesc>` but wouldn't be allowed in there any more if we were to follow up on the proposal. Personally I think an easy  solution to this would be to allow `<history>` within `<physDesc>`.
