### ISSUE TITLE
Better tagging in Guidelines

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#913]
As discussed in #900 and #910 we should use more TEI elements to achieve better, semantically richer Guidelines. 

**Proposal**: 

- use `abbr` for all used abbreviations
- use `term` for all musical/technical terms (like "glissando") 
- add `@rend` to the former to add quotation marks automatically instead of hardcoding them
- use `name` for names of composers and works with `@ref` to point to additional information
- use `val` for all named attribute values in textual content

(This list could be extended.)

**Comment by musicEnfanthen** [comment]
Pinging @kepper since these questions (and their intended use-case) should be coordinated with the Editorial Board of the Guidelines.

**Comment by kepper** [comment]
In general, I think this is very helpful. It may take some time to implement this throughout the Guidelines, but I'm happy to accept the challenge (fully aware that I haven't found much time in the last couple of months…). One question, though: Shouldn't we just rely on CSS (`:before` and `:after`) instead of an additional `@rend`? Seems to be presentational only, and could help to keep the Guidelines tidy…

**Comment by bwbohl** [comment]
+1 for the CSS solution instead of `@rend`

**Comment by lpugin** [comment]
Since #938 has been merge I am closing it. This would require a significant work on the guidelines and the need of it is not very clear.
