### ISSUE TITLE
<componentList> in module MEI.header?

### ISSUE THREAD

**Issue by th-we** [music-encoding/music-encoding#923]
In [this commit](https://github.com/music-encoding/music-encoding/commit/cd39884a73284f97e860b52c39bca793a0307407#diff-875833397f5d1e47f1737b8e53e46440516b8d9099875605a55e3454a8540552L150) @pe-ro (among other things) renamed `<componentGrp>` to `<componentList>` and changed its `@module` value from `MEI.frbr` to `MEI.header`.  However, now `<componentList>` is the only element in the entire MEI specs where the `@module` value (`MEI.header`) differs from the file name (`MEI.frbr.xml`).

Is that an oversight or intentional? If intentional, maybe we should document that to avoid confusion.

**Comment by pe-ro** [comment]
This change was intentional.  Because `<work>` is in the `MEI.header` module and therefore can be used even when the FRBR module isn't "engaged", `<componentList>` should be there too.  It's not required by the ODD stylesheets that all definitions related to a particular module be located in the same file, but since it's true for every MEI element, it makes sense to move the definition of `<componentList>` to `MEI.header.xml`.

**Comment by musicEnfanthen** [comment]
Reopened as it will be closed with merge of PR #924

**Comment by rettinghaus** [comment]
#924 has been merged, so closing this now.

**Comment by musicEnfanthen** [comment]
Thanks!
