### ISSUE TITLE
edit/update schematron rule in `<history>`

### ISSUE THREAD

**Issue by doerners** [music-encoding/music-encoding#934]
Since `<exhibHist>` et.al. are now modelled after `<provenance>` (#911), they are children of `<history>`.  [`<history>`](https://music-encoding.org/guidelines/dev/elements/history.html) has defined a Schematron rule to prevent the use of `<acquisition>` and `<provenance>` at the `work` and `expression` levels. Also `<exhibHist>` et.al. should not be allowed on these levels, however the Schematron rule is not updated yet.

Personally, I think we should first discuss whether `<exhibHist>` et.al. should be allowed at the `manifestation` level in general or whether it would not make more sense to allow them at this level only in the case of encoding a `manifestation singleton`. However, since there is a general lack of information/descriptions for `manifestation singleton` (#906), I am not sure what such a rule might look like or whether there are considerations against such a restriction.

**Comment by bwbohl** [comment]
ODD Meeeting 2022-03:

You're comlpetely right the schematron rule should also apply to `exhibHist` and of course take into account `manifestation=singleton`. Will have a look at it, promise :-p

**Comment by rettinghaus** [comment]
@bwbohl Did you have a look?

**Comment by bwbohl** [comment]
Sorry for my longish silence been on holidays ;-)
Now I'm back and on it.

After a first peak I wonder whether:

1. The schematron rules should better be individualised and instead of reporting history with an error, report the respective disallowed element instead.
2. the rules should report an error or a warning, maybe the latter would be good in case of manifestation context, if the manifestation misses `@singleton=true`

Comments welcome
