### ISSUE TITLE
Do incipits encoded in MEI need to be scores?

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#936]
`incip` allows a `score` to store MEI encodings. I'm wondering why it then not also allows `part`, because this is what can be stored as PAE in `incipCode`. Would you need to use PAE for that, or do I just misunderstand the concept of `part`?

**Comment by KristinaRichts** [comment]
It would certainly be logical to offer the `part` element for selection here as well. I could imagine that the encoding options should be kept deliberately slim here, since one can also simply encode a single voice within the score element. Surely it is not meant that incipits of single voices should only be encoded in PAE.

**Comment by ahankinson** [comment]
My understanding is that `<part>` is used only in very special circumstances, generally when it is not possible or easy to extract single voices from a score into instrumental parts. My reading of the remarks on the `<part>` element suggest that it's used specifically when you are encoding a physical document, and the document you have is a single part. (e.g., a partbook, or a copy of an instrumental part from an entire orchestra).

In this case, you probably wouldn't encode an incipit for the part, since the incipit is an identifier for the whole piece, not just an extract of a single part. (As we discussed earlier). It might be that a part (e.g., the top line or tune) has the same notes as the score's incipit, but I don't think the two are semantically equivalent. 

So I don't think it's supposed to be used to only encode a single voice. For that, you would probably use the normal `score` mode, with just a single staff and a single layer. I would also presume that you could use the linking mechanisms (e.g., `@sameas`) to point into the score, if one is encoded in the `<music>` section.

**Comment by lpugin** [comment]
It seems that we have a consensus that `<part>` is not really necessary in `<incip>`. @pe-ro @fujinaga @kepper @musicEnfanthen
