### ISSUE TITLE
build: redesign guidelines build to match target folder structure

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#960]
When building the guidelines locally the resulting folder structure is not identical to the structure in the guidelines repo. Consequently local testing does not work 100%. We should inspect this and maybe move the copy actions executed by the GitHub Action script to be run in the ant build, instead.

**Comment by kepper** [comment]
I think we should come up with a plan on which assets are supposed to go where, and then adjust everything starting from our first steps. It would be easy to adjust output paths in the XSLT, so that we don't need to move things later on at all. Also, it would be good to clean up the location of CSS files…
