### ISSUE TITLE
Allow nested zones

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#971]
Currently [`zone`](https://music-encoding.org/guidelines/dev/elements/zone.html) only allows [`figDesc`](https://music-encoding.org/guidelines/dev/elements/figDesc.html) and [`graphic`](https://music-encoding.org/guidelines/dev/elements/graphic.html) as children. 

TEI allows nested [`zone`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-zone.html)s, which would be a preferable way to encode a clef's position within a measure box.  

```xml
<zone type="measure">
  <zone type="clef" />
</zone>
```

**Comment by pe-ro** [comment]
This deviation from TEI was by design.  Nested zones don't add any information not already present in the content markup.  In this case, the MEI markup explicitly encodes the parent/child relationship between measure and clef.  Also, adding coordinates to nested zones muddies the water a bit as it becomes less clear if the coordinates of the child zone are relative to the parent or not.  Making the zones "un-nested", it is (hopefully) clear that the coordinates of the child are NOT relative to its parent zone, but to the surface or graphic containing the zone(s).

**Comment by bwbohl** [comment]
I second this deviation from the TEI model. And also think that keeping the facsimile tree a flat (two-dimensional) space is adequate and more clear for describing a two-dimensional space. Just out of curiosity: Does any of you have a use-case at hand for a graphic nested in zone (because graphic is also possible in surface and even in facsimile)?

**Comment by rettinghaus** [comment]
You can provide images of details within a zone without specifying coordinates, e.g. compare https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-graphic.html
What bothers me more is that it is possible in MEI to nest a zone within graphic. I would like to see a use case for this one.

**Comment by bwbohl** [comment]
Ok, that seems to make sense, e.g., if you mark, let's say, the zone of a watermark that is not visible in your primary image file, and you supply a  thermographic detail image of the watermark.

```xml
<surface>
    <graphic target="rgb.jpg"/>
    <zone label="this is where the watermark is located" […]>
        <graphic target="watermark-thermo-detail.shot.jpg"/>
    </zone>
</surface>
```

**Comment by bwbohl** [comment]
> What bothers me more is that it is possible in MEI to nest a zone within graphic. I would like to see a use case for this one.

Picking up the watermark example again you could encode it the other way round, i.e.: 
You have a regular RGB and a thermographic image of the whole page:

```xml
<surface>
    <graphic target="rgb.jpg">
        <zone label="some area of interest" […] />
    </graphic>
    <graphic target="thermo.jpg">
            <zone label="watermark only visible in this representation" […] />
    </graphic>
</surface>
```

I'm just exploring, not sure if we should definitely stick to all those possibilities.

**Comment by rettinghaus** [comment]
I think that the notes on TEI's `zone` are quite explicit (and imho better than trying to force correct/logical encoding by design):

> The position of every zone for a given surface is always defined by reference to the coordinate system defined for that surface.

> A graphic element contained by a zone represents the whole of the zone.

And also better than allowing things like:

```xml
<facsimile>
  <surface>
    <zone>
      <graphic>
        <zone>
          <graphic>
            <zone>
              <graphic />
            </zone>
          </graphic>
        </zone>
      </graphic>
    </zone>
  </surface>
</facsimile>
```

**Comment by kepper** [comment]
There seemed to be consensus a long time ago. Discussed this again at 2022 dev meeting in Berlin. We will not be able to suppress bad use of MEI in all cases, so a simple "don't do that" is sufficient. Not even sure we need to update documentation for this…
